### ISSUE TITLE
Passport migrations executed against tenants.

### ISSUE THREAD

**Issue by ArtisanTinkerer** [spatie/laravel-multitenancy#102]
Hi, just installed Passport and I am getting this error when I create (and migrate) a  new tenant:

```Base table or view already exists: 1050 Table 'oauth_auth_codes' already exists ``` (surely this just means in the landlord, this is a new tenant db).

Can I just move the Passport migrations into the landlord directory?

**Comment by masterix21** [comment]
Hi @ArtisanTinkerer,

do you have already ignored the passport migrations in the service provider?

```php
// AppServiceProvider.php
// ...
public function register()
{
    Passport::ignoreMigrations();
}
// ...
```

**Comment by ArtisanTinkerer** [comment]
No but I will. Will this then just used the migrations in the database folder?

**Comment by masterix21** [comment]
Yes, will do

**Comment by monish-khatri** [comment]
I'm Still Facing this Issue. I've Added `Passport::ignoreMigrations();` in `app/Providers/AppServiceProvider.php` But now working as expected
Laravel : 9.30
Passport: 10.4
spatie/laravel-multitenancy: 2.3
