### ISSUE TITLE
Using Laravel Scheduler with Multitenancy

### ISSUE THREAD

**Issue by LukeAbell** [spatie/laravel-multitenancy#103]
Running `php artisan tenants:artisan schedule:run` loops through the tenants and runs the scheduled commands but Tenant::current() is null. I think I've narrowed this down to the scheduler calling an artisan command in a forked process which recalls `php artisan XXX` with whatever the command is (which bypasses the multi-tenancy call). 

Is there a way to make the scheduler tenant aware like the package currently does with queues?

Thanks!

**Comment by masterix21** [comment]
Hi @LukeAbell, are you sure that are you doing everything well?

See my example here:
https://github.com/spatie/laravel-multitenancy/issues/82#issuecomment-663771093

Please post your code. Thank you

**Comment by LukeAbell** [comment]
@masterix21 @freekmurze The issue only occurs when using `$schedule->command()` or `$schedule->exec()`. Running `$schedule->job()` on the works correctly.

**Comment by LukeAbell** [comment]
@freekmurze The issue also affects all of the Mailcoach commands. Turning them into Jobs works.

**Comment by masterix21** [comment]
@LukeAbell, thanks for your issue. 

I'm working over the solution, and in the next days, I will release the PR to fix it.

In the meanwhile, if you like to apply a temporary solution, you can use this trait with your tenant-aware commands:
```php
trait IsTenantAware
{
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $tenantIds = Arr::wrap($this->option('tenant'));

        return Tenant::query()
            ->when(! blank($tenantIds), fn ($query) => $query->whereIn('id', $tenantIds))
            ->cursor()
            ->map(fn ($tenant) => $tenant->execute(fn () => (int) $this->laravel->call([$this, 'handle'])))
            ->sum();
    }
}
```

Finally, change your command signatures appending `--tenant=*`.

**Comment by LukeAbell** [comment]
@masterix21 thank you!!

**Comment by masterix21** [comment]
I forgot to say that you could change your schedule method as follow:
```php
    protected function schedule(Schedule $schedule)
    {
        $schedule->command('tenant:aware:command');
    }
```

And you could call only
```bash
php artisan schedule:run
```

Thanks

**Comment by masterix21** [comment]
@LukeAbell the fix has been released.

**Comment by LukeAbell** [comment]
@masterix21 thank you!!
