### ISSUE TITLE
Undefined variable: host

### ISSUE THREAD

**Issue by rxng** [spatie/laravel-multitenancy#104]
Hi, I am following the instructions from https://docs.spatie.be/laravel-multitenancy/v1/installation/using-multiple-databases/

and am at the step where I am supposed to run 
`php artisan migrate --path=database/migrations/landlord --database=landlord `

However, I am getting this error:
`Undefined variable: host (SQL: select * from information_schema.tables where table_schema = landlord and table_name = migrations and table_type = 'BASE TABLE')`

I've checked my mysql, it is running, and I have created the database called landlord.

Just wondering why this might be occurring and if there is a fix?

**Comment by freekmurze** [comment]
Could you provide us with the complete stack trace?

**Comment by masterix21** [comment]
@rxng seems that you using an undefined `$host` variable in your `config/database.php` or in your `DatabaseSwitchTask`. As said @freekmurze, please post your stack trace. Thanks
