### ISSUE TITLE
Potential conflict with `Tenant::$guarded` when extending `Tenant`...

### ISSUE THREAD

**Issue by telkins** [spatie/laravel-multitenancy#109]
I'm extending the `Tenant` class with a class where I use `fillable`.  This conflicts with `Tenant::$guarded`.  Any thoughts...?

FYI...I'm not suggesting that this is an issue, although it might be.  I mainly wanted to hear ideas on what could/should be done.  It might be good to change `Tenant`, either dropping `$guarded` or replacing it with `$fillable`....but maybe it's fine to keep it...?

**Comment by masterix21** [comment]
Laravel `GuardsAttributes` trait declares` $ guarded = ['*'] `, and it means that all attributes aren't mass-assignable.

Tenant uses `$ guarded = []` to reset the default value, and it means that all attributes are mass-assignable.

I agree with your consideration: it's better to remove `$ guarded = []` from `Tenant` to keep nearer to the original` Model`, unless there is a valid reason that @freekmurze knows.

**Comment by freekmurze** [comment]
Let's remove `$guarded` from our model. If all our tests pass it's fine!

**Comment by masterix21** [comment]
Tested and released :) I'm closing it ;)

Thank you @telkins

**Comment by telkins** [comment]
Thx @masterix21 @freekmurze ...!

I wasn't sure what the best course of action was, but I'm glad you guys quickly/easily came to a decision. 💪
