### ISSUE TITLE
Docs 404 

### ISSUE THREAD

**Issue by renege** [spatie/laravel-multitenancy#112]
Hi,
The following URLs are 404
- https://docs.spatie.be/laravel-multitenancy/v1/using-tasks-to-prepare-the-environment/filesystems/
- https://docs.spatie.be/laravel-multitenancy/v1/using-tasks-to-prepare-the-environment/cache/

Found here: https://docs.spatie.be/laravel-multitenancy/v1/installation/using-a-single-database/#next-steps 

@freekmurze

**Comment by masterix21** [comment]
Fixed. Thank you

**Comment by upeksha1996** [comment]
"use separate filesystems per tenant" link in https://spatie.be/docs/laravel-multitenancy/v1/installation/using-multiple-databases redirecting to introduction page. Is this a mistake?

**Comment by masterix21** [comment]
@upeksha1996 yes, seems a mistake. Could you fix it with a PR, please?
