### ISSUE TITLE
Using with Laravel Passport.

### ISSUE THREAD

**Issue by ArtisanTinkerer** [spatie/laravel-multitenancy#113]
How are you using this with Passport?

Do you have your oauth tables in the landlord or tenants? I was thinking tenants but oauth_clients should be in the landlord since the clients are related to the application, not tenants.

I'm trying to follow this: https://medium.com/@wannymiarelli/laravel-multi-tenancy-with-passport-10ce9b6a1c21 but when I do ```php artisan passport:install``` I get:

```Base table or view not found: 1146 Table 'landlord.oauth_clients' ```

**Comment by masterix21** [comment]
I have the OAuth tables in the landlord (for landlord purposes) and in the tenant (for tenant purposes).

It's really important to add `Passport::ignoreMigrations()` to your AppServiceProvider. Next, you can publish the passport migrations inside your `database/migrations/landlord` and `database/migrations/tenants`.

Finally, you have two ways:
- extending your DatabaseSwitchTask to switch your database default connection
- extending all Passport models to understand if you are in the tenant or the landlord.

We had discussed a lot about it:
- https://github.com/spatie/laravel-multitenancy/issues/29
- https://github.com/spatie/laravel-multitenancy/issues/62
- https://github.com/spatie/laravel-multitenancy/issues/102
