### ISSUE TITLE
Unable to run migrate tenant database.

### ISSUE THREAD

**Issue by shahvirag** [spatie/laravel-multitenancy#118]
Using multi-database setup.

![spatie-multitenancy](https://user-images.githubusercontent.com/24240840/91057555-f9b86f80-e644-11ea-90e6-97eccb61d022.png)

- php artisan tenants:artisan "migrate:fresh", this works fine.
- php artisan tenants:artisan "migrate", this command doesn't work.

Laravel: 7.x
PHP: 7.4.7
Database: Mysql 5.7

**Comment by masterix21** [comment]
Hi @shahvirag, please follow [the documentation](https://docs.spatie.be/laravel-multitenancy/v1/installation/using-multiple-databases/#migrating-tenant-databases) and add the `--database=` parameter.

Thanks
