### ISSUE TITLE
Issues testing multitenancy...

### ISSUE THREAD

**Issue by telkins** [spatie/laravel-multitenancy#121]
This issue is created to continue to work through what I think are issues with this package, laravel, testing multitenancy, or....my own approach to this whole thing.  🤓 

I've been working with @masterix21 , who's been fantastic at helping me and I hope he continues to do so.  (No pressure...!  😛 )

I have a repo here that (hopefully) demonstrates the issue(s) that I'm trying to deal with: https://github.com/telkins/laravel-multitenancy-test

To be clear, this repository attempts to replicate a couple of important-to-me things that I'm doing in the app that currently uses this package:
- each tenant has its own database
- upon a tenant's `created` event, a job is dispatched that is meant to provision the new tenant's database
- the provisioning job is **non-tenant-aware** and actually uses the landlord connection
- provisioning involves creating the new tenant's database and migrating it
- most of my tests involve a single tenant...and I don't think I have any real problems with them
- my issues lie in the tests that I want/need that involve having more than one tenant

So...the current issue can be seen by cloning the repo, spinning it up, and then running the tests.  If the landlord connection is a connection that should have transactions against it, then the second test will fail (see assertion in `setUp()` method).  If the landlord connection doesn't have transactions against it, then all but the first test are run against "polluted" data.

Of course, if the landlord connection is rolled back each time, then when migrations take place at the beginning of a test run (as things are currently written), then there will be no tenants listed to "roll back" via `migrate:fresh`.

So...a bit of a complicated issue, in my opinion.  I'm hoping someone can address this and help point me in a good direction. 🤓 

Alright...I'm done for now. I'll wait for some feedback.  👍 💪 👍

**Comment by telkins** [comment]
FYI...some related conversation can be found at the now-closed PR: #117.

**Comment by masterix21** [comment]
@telkins, the problem isn't the package or Laravel but MySQL itself.

Your code logic involves that when you create a tenant, create a database automatically. 

MySQL has implicit commit statements, and `CREATE DATABASE` is one of these. It means that if you create a tenant, your event system will create a database before your rollback: useless because your `CREATE DATABASE` had already committed the changes.

https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html

That's all 🥇

**Comment by masterix21** [comment]
@telkins, can I close the issue?

**Comment by telkins** [comment]
> @telkins, can I close the issue?

Sorry...I thought I responded to this when you first posted the question.  I'll close it...and re-open it or a new one if/when it's necessary.

Thx so much for your help, btw...!  🤓
