### ISSUE TITLE
Missing required parameters for route

### ISSUE THREAD

**Issue by AdamNimDev** [spatie/laravel-multitenancy#123]
This package looks like just what I need, but there must be an easier solution to this problem.

```
Route::domain('{domain}.example.com')->middleware('tenant')->group(function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
});

```

Throws 

```
Illuminate\Routing\Exceptions\UrlGenerationException

Missing required parameters for [Route: dashboard] [URI: dashboard]
```

All of the solutions on the web suggest creating a middleware to inject the domain (and then forgetting it again, to keep things uncluttered) but I'm wondering if I've overlooked something as this is a core feature of a multi-tenancy package. 

What is the best solution for this? TIA

**Comment by masterix21** [comment]
Why did you need to specify the domain?

If you use the tenant middleware the route is already "tenant-aware".

```php
Route::group(function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
})->middleware('tenant');
```
