### ISSUE TITLE
Subdomain support

### ISSUE THREAD

**Issue by bhushan** [spatie/laravel-multitenancy#126]
lets suppose I have saas called.. `saas.com` so what i want is when user registers on `saas.com` 
he/she will get access to there tenant from `something.saas.com`

but if they provide there domain with us then it should also work with `theredomain.com`

I hope you are getting my point.

I am working on currently.. Will send PR.. Lets see how far i go..

**Comment by bhushan** [comment]
there should be configuration array like 
```php
excluded_subdomains => [
'www'
];
```
like this

**Comment by freekmurze** [comment]
Thanks for your suggestion, regarding tenant finder functionality, I think we want to keep things as they are for now.
