### ISSUE TITLE
Multi-Databse Tenant Migration Invalid Catalog

### ISSUE THREAD

**Issue by chris-rutherfurd** [spatie/laravel-multitenancy#130]
I have setup the multi-database option for multitenancy. My database config is...

    /*
    	 * Landlord Database Connection
    	 */
    	'landlord' => [
    		'driver' => 'mysql',
    		'url' => env('DATABASE_URL'),
    		'host' => env('DB_LANDLORD_HOST', '127.0.0.1'),
    		'port' => env('DB_LANDLORD_PORT', '3306'),
    		'database' => env('DB_LANDLORD_DATABASE', 'forge'),
    		'username' => env('DB_LANDLORD_USERNAME', 'forge'),
    		'password' => env('DB_LANDLORD_PASSWORD', ''),
    		'unix_socket' => env('DB_SOCKET', ''),
    		'charset' => 'utf8mb4',
    		'collation' => 'utf8mb4_unicode_ci',
    		'prefix' => '',
    		'prefix_indexes' => true,
    		'strict' => true,
    		'engine' => null,
    		'options' => extension_loaded('pdo_mysql') ? array_filter([
    			PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
    		]) : [],
    	],
    	
    	/*
    	 * Tenant Database Connection
    	 */
    	'tenant' => [
    		'driver' => 'mysql',
    		'url' => env('DATABASE_URL'),
    		'host' => env('DB_TENANT_HOST', '127.0.0.1'),
    		'port' => env('DB_TENANT_PORT', '3306'),
    		'database' => null,
    		'username' => env('DB_TENANT_USERNAME', 'forge'),
    		'password' => env('DB_TENANT_PASSWORD', ''),
    		'unix_socket' => env('DB_SOCKET', ''),
    		'charset' => 'utf8mb4',
    		'collation' => 'utf8mb4_unicode_ci',
    		'prefix' => '',
    		'prefix_indexes' => true,
    		'strict' => true,
    		'engine' => null,
    		'options' => extension_loaded('pdo_mysql') ? array_filter([
    			PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
    		]) : [],
    	],

I have two entries in my tenants mysql table with the database fields being `sh1219` and `sh1220` and both are existing databases on the same server as the landlord database but when I run `php artisan tenants:artisan "migrate"` I get an `Illuminate\Database\QueryException` with the message...

    SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected

I have double checked my .env file and the database server details are correct in there and I have run tinker to check the loaded multitenancy config and database config and they are all correct but I am still getting this error.

My default connection is the tenant connection and the tenants database key is valued at `null` so that the multitenancy command can automatically fill the database in.

I can see that the command is getting the list of all tenants in the tenants table as it displays 

    Running command for tenant 'some tenant' (id: 1)...

**Comment by masterix21** [comment]
I use landlord as default connection. About the other problems, change `migrate` to `migrate --database=tenant`:

https://spatie.be/docs/laravel-multitenancy/v1/installation/using-multiple-databases#migrating-tenant-databases

**Comment by chris-rutherfurd** [comment]
> I use landlord as default connection. About the other problems, change `migrate` to `migrate --database=tenant`:
> 
> https://spatie.be/docs/laravel-multitenancy/v1/installation/using-multiple-databases#migrating-tenant-databases

I have tried that and still not working

**Comment by masterix21** [comment]
Are you using the database switch task in the right way?

**Comment by p4rz1val** [comment]
Im facing the same issue, here's the flare error: https://flareapp.io/share/w5BkKLm8#F52

An in my case it seems to be related to the auth middleware if i remove the auth middleware then everything works fine:
```
Route::middleware('tenant')->group(function() {
    Auth::routes();
});

Route::middleware(['tenant', 'auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
});
```
Im using a custom Tenant Finder (by session)

```
    use UsesTenantModel;

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        // If there's no tenant session
        if (empty(session('tenant_id'))) {
            Tenant::forgetCurrent();
            $request->session()->forget('ensure_valid_tenant_session_tenant_id');

            return redirect(route('workspace.show'));
        }

        // Validate the tenant exists
        $tenantId = session('tenant_id');
        $tenant = $this->getTenantModel()::where('id', $tenantId)->first();

        // If there's a tenant session and the tenant exists
        if (!empty($tenant)) {
            // Make the tenant the current one
            $tenant->makeCurrent();
            // And save the tenant on the session
            $request->session()->put('tenant_id', $tenant->id);

            return $next($request);
        }

        // If tenant doesnt exist
        Tenant::forgetCurrent();

        $request->session()->forget('tenant_id');
        $request->session()->forget('ensure_valid_tenant_session_tenant_id');

        return redirect(route('workspace.show'));
    }
```
but i dont even hit the middleware before the exception

**Comment by chris-rutherfurd** [comment]
> 
> 
> Are you using the database switch task in the right way?

I am using the `php artisan tenants:artisan "migrate --database=tennant"` task which is meant to automate the switching by iterating through each tenant and applying the migrations to each tenants database. I have not changed this command at all.

**Comment by chris-rutherfurd** [comment]
@p4rz1val - I don't have any route middleware attached as this is a greenfield laravel installation that I started with. I was wanting to add the multitenancy capabilities and build up the necessary base tenant migrations before I started in on user authentication.

**Comment by masterix21** [comment]
@chris-rutherfurd, have you followed the documentation about the database switching?
https://spatie.be/docs/laravel-multitenancy/v1/using-tasks-to-prepare-the-environment/switching-databases

**Comment by chris-rutherfurd** [comment]
> 
> 
> @chris-rutherfurd, have you followed the documentation about the database switching?
> https://spatie.be/docs/laravel-multitenancy/v1/using-tasks-to-prepare-the-environment/switching-databases

That was it thanks @masterix21, I had failed to add the database switch class to the config. Thanks.
