### ISSUE TITLE
Nothing to migrate for tenant

### ISSUE THREAD

**Issue by bremg** [spatie/laravel-multitenancy#131]
I cannot get migrations to work with this package. 

php artisan tenants:artisan migrate

Gives lists my tenants but says there is nothing to migrate. 

Even when I add a new tenant with an empty database. 

When I run migrate:fresh it shows the migrations running on each tenant, but doesn't run them on the tenants, instead it runs them all on the landlord. 

What am I doing wrong?

Config (part of it):

    'tenant_finder' => null,
    'switch_tenant_tasks' => [
        Spatie\Multitenancy\Tasks\SwitchTenantDatabaseTask::class,
    ],
    'tenant_artisan_search_fields' => [
        'id','name','database'
    ],

I do use a custom tenant model:

```
class Website extends Tenant
{
    protected $fillable = [
        'client_id',
        'name',
        'url',
        'database'
    ];
```

Hopefully someone can point me in the right direction. 

Does it need a tenant_finder maybe?

**Comment by masterix21** [comment]
https://spatie.be/docs/laravel-multitenancy/v1/installation/using-multiple-databases#migrating-tenant-databases

Your tenant migrations can't work without the database parameter. Check the documentation.

**Comment by bremg** [comment]
Maybe I should have added more information. 

The landlord/tenant functionality is currently working. 
All that isn't is migrating, that's why im confused.

But I guess I will dive into it or write my own migrator

**Comment by bremg** [comment]
Ah I see whats wrong: 

https://spatie.be/docs/laravel-multitenancy/v1/advanced-usage/making-artisan-commands-tenant-aware#using-the-tenantsartisan-command

I uses this page in the documentation but that's not working. 

https://spatie.be/docs/laravel-multitenancy/v1/installation/using-multiple-databases#migrating-tenant-databases
This has the right commands. 

I guess they should update the documentation since this is very confusing. 

Either way thanks

**Comment by masterix21** [comment]
@bremg, if you think something is wrong in the documentation, you could help us change it: documentation files are in the same repository of package. You would very helpful for the community. Thanks
