### ISSUE TITLE
[Question] During testing, my tenant finder is not being called

### ISSUE THREAD

**Issue by grantholle** [spatie/laravel-multitenancy#132]
I have a custom tenant finder where I'm doing a `dd` to see how things are working. When doing a normal request in the browser to my /login route, it does dump and die.

I have written a test that for authentication as a tenant. It never call my tenant finder. My test only works when I manually call `$tenant->makeCurrent()`. Below, this test fails. My tenant finder is never called during the test. 

Am I missing something to set up to test my finder class?

```php
public function test_can_auth_to_right_tenant()
{
    $tenant = Tenant::first();
    // Only works when this is uncommented
    // $tenant->makeCurrent();
    $user = $tenant->users->random();

    $this->post('http://tenants.domain.test/login', [
        'email' => $user->email,
        'password' => 'secret',
    ]);
    $this->assertAuthenticatedAs($user);
}
```

Not shown: I have seeds for tenants and users.

Thank you!

**Comment by masterix21** [comment]
The problem could be your URL. Try to add these lines to your setup method and give us a feedback.

```php
Event::listen(MadeTenantCurrentEvent::class, fn (Tenant $tenant) => URL::forceRootUrl('http://'. $tenant->host));
Event::listen(ForgotCurrentTenantEvent::class, fn (Tenant $tenant) => URL::forceRootUrl(env('APP_URL')));
```

Thanks

**Comment by grantholle** [comment]
Thanks for that snippet. I have a switcher task that you suggested in #65. I also adjusted my test to be really sure it was the correct url:

```php
public function test_can_auth_to_right_tenant()
{
    $tenant = Tenant::first();
    // $tenant->makeCurrent();
    $user = $tenant->users->random();

    $this->post("http://{$tenant->domain}/login", [
        'email' => $user->email,
        'password' => 'secret',
    ]);
    $this->assertAuthenticatedAs($user);
}
```

I've tinkered in the `MultitenancyServiceProvider` and discovered that when running phpunit, `$this->app->runningInConsole()` is `true`. Forcing that conditional makes things run smoothly.

```php
protected function configureRequests(): self
{
    // This is true, so it's never detected :/
    if (! $this->app->runningInConsole()) {
        $this->determineCurrentTenant();
    }

    return $this;
}
```

I don't know if this is normal behavior for Laravel? I've never encountered this before. I'm running the tests inside phpstorm so it might be a configuration issue on my end. I'm using the default `phpunit.xml` that comes with Laravel and the configuration has the right paths to the autoloader and `phpunit.xml`.

**Comment by grantholle** [comment]
This works, but it's not the right solution

```php
protected function configureRequests(): self
{
    if (! $this->app->runningInConsole() || $this->app->environment('testing')) {
        $this->determineCurrentTenant();
    }

    return $this;
}
```

**Comment by grantholle** [comment]
Ok... Had to look at the underlying `runningInConsole()` call. I don't know if this is the right solution either, but I've added an entry in my `phpunit.xml` to have...

```xml
<server name="APP_RUNNING_IN_CONSOLE" value="false"/>
```

and things work normally.

**Comment by bryanjamesmiller** [comment]
@masterix21 I have this same issue.  Could this check be removed?  What benefit is it providing?

```if (! $this->app->runningInConsole()) {```

**Comment by masterix21** [comment]
@bryanjamesmiller, can't be removed because `MultitenancyServiceProvider` is always called: with `php artisan ...` too.

Please follow it: https://github.com/spatie/laravel-multitenancy/issues/132#issuecomment-688558050

**Comment by gssj85** [comment]
> Ok... Had to look at the underlying `runningInConsole()` call. I don't know if this is the right solution either, but I've added an entry in my `phpunit.xml` to have...
> 
> ```
> <server name="APP_RUNNING_IN_CONSOLE" value="false"/>
> ```
> 
> and things work normally.

That was a great finding, thank you very much.
