### ISSUE TITLE
Setting value in database column when using single database approach

### ISSUE THREAD

**Issue by kaleidoscope-niraj** [spatie/laravel-multitenancy#134]
On running migrations as per the docs, for multi-tenancy with a single database for all tenants, there is a table with `database` fieldset as unique. Should we override it? There is no clear path in doc explaining multi-tenancy using single database approach.

**Comment by masterix21** [comment]
Yes, you can override the table removing it: the field `database` is used only with multiple database.

**Comment by kaleidoscope-niraj** [comment]
Just a question, how do you use the tenant model in another table to maintain the relationship? Should we do it ourselves like setting tenant_id in its related table in the scenario of a single database?

**Comment by masterix21** [comment]
I never used the package for the single database scenario, but yes, you should implement the `tenant_id` column.

An idea could be to create a query scope:
```php
/*
 * Example scope
 */
class TenantScope implements Scope
{
    public function apply(Builder $builder, Model $model)
    {
        $builder->where('tenant_id', '=', Tenant::current()->id);
    }
}

/*
 * Model
 */
class YourModelTenantAware extends Model
{
    protected static function booted()
    {
        static::addGlobalScope(new TenantScope);
    }
}
```

**Comment by masterix21** [comment]
@kaleidoscope-niraj, I'm closing the issue because isn't related to a package problem, but feel free to continue the discussion here.

Thanks
