### ISSUE TITLE
problem with spatie DomainTenantFinder

### ISSUE THREAD

**Issue by manserod75** [spatie/laravel-multitenancy#135]
Hi, I try to change the original configuration of **DomainTenantFinder** because I want get the tenant as follow:

- www.mydomain.com/tenant1
- www.mydomain.com/tenant2

so I replace the findForRequest() method of DomainTenantFinder by:

_$name = $request->segment(1);
 return $this->getTenantModel()::whereName($name)->first();_

Also I have wroten   all routes for each tenant.

The problem is when I try to login: 
**SQLSTATE[42S02]: Base table or view not found: 1146 Table 'landlord.users' doesn't exist (SQL: select * from `users` where `id` = 2 and `users`.`deleted_at` is null limit 1)**

I dont know why is trying to use landlord connection. 

If I use the original code in DomainTenantFinder, run perfect:
**$host = $request->getHost();
return $this->getTenantModel()::whereDomain($host)->first();**

Could anyone to tell me how configure the spatie package to switch tenants using url (www.mydomain.com/tenantx)??

thank you

**Comment by masterix21** [comment]
In the `DomainTenantFinder` the first segment should be always a tenant. Have you changed your auth routes to be used from www.mydomain.com/tenant1/{auth-routes} (/login, etc)?

Please explain better your approach. Thanks

**Comment by manserod75** [comment]
Hello, thank you very much for your answer. Sorry for my english. it is very bad.

The answer to your question is yes. I have changed routes so that tenat's users can do login:

that is tenant routes:
,,,
Route::prefix('tenantName')->namespace('\App\Admin\Controllers')->group(function(){
                  // Login
                  Route::get('login')->name('login')
                      ->uses('LoginController@showLoginForm');
                  Route::post('login')->name('login.attempt')
                      ->uses('LoginController@login');

                  // AUTH
                  Route::middleware('auth')->group(function () {

                      // Logout
                      Route::post('logout')->name('logout')
                          ->uses('LoginController@logout');

                      // Dashboard
                      Route::get('/')->name('dashboard')->uses('DashboardController');

                      // Users
                      BaseCrudRouter::routes('users', 'UsersController');
                      Route::get('/users/{user}/impersonate')->name('impersonate')
                          ->uses('UserImpersonateController@impersonate');
                      Route::get('/users/impersonate/leave')->name('impersonate.leave')
                          ->uses('UserImpersonateController@leave');
                  });
              });

And the first segment of the url must be tenant name, of course. Also this tenant exist in tenants table of landlord database. And User table exists in tenant ddbb.

I have installed the spattie package and configured it with author instructions: The author use symbolics links to define tenats but this way is not good for me. I need to define tenants using the first segment of the urlso I replace the findForRequest() method of DomainTenantFinder by:

$name = $request->segment(1);
return $this->getTenantModel()::whereName($name)->first();

That change do login correctly but show the following error:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'landlord.users' doesn't exist (SQL: select * from users where id = 2 and users.deleted_at is null limit 1)

if I go to home page of tenant, all is ok, I can surfing in the web.

I have tried several solutions to solve but no work (to make a new guard o force to change the default database)

I think that if my tenancy system work with synbolic links it should work in my way and no need to make big changes.

Do you have any idea?? 

thank you very much indeed

**Comment by masterix21** [comment]
Are you using the UsesTenantConnection trait in your User model?

**Comment by manserod75** [comment]
Hi masterix21, thank you very much for your answer.

Yes, I have use that trait in User model.

**Comment by masterix21** [comment]
If you can, please publish your code in a public repository to help me to dig inside.

Thanks

**Comment by masterix21** [comment]
If you can, please publish your code in a public repository to help me to dig inside.
I'm closing the issue because it is not related to the package, but feel free to continue the discussion. 

Thanks

**Comment by manserod75** [comment]
Hi!, this is my repository: https://github.com/manserod/multitenancy

I begin this project using author instructions and become **working perfectly**. But, in order to get the tenant using url like (mydomain.test/tenantx I change ONLY 2 files: DomainTenantFinderand.php and Web.php (routes).

With this changes, the login/register no work properly.

**Comment by masterix21** [comment]
Sorry, your web.php has no sense.

Why are you using a `foreach` to check all tenants? So, have you seen that your auth-routes have duplicated names?

[Please read it](https://spatie.be/docs/laravel-multitenancy/v1/installation/base-installation#protecting-against-cross-tenant-abuse) and add to your `$middlewareGroups` the 'tenant' group.

So, change your web.php with:
```php
Route::group([
    'middleware' => 'tenant',
    'prefix' => '/{tenant}',
], function () { /* all your routes but without auth routes */ });
```

Finally, remove your auth routes like originals and not duplicate these for all your tenants: when a user does a login, you will redirect him to the right tenant.

I hope that's all.
