### ISSUE TITLE
Questions regarding tenancy filsystems

### ISSUE THREAD

**Issue by Franco2911** [spatie/laravel-multitenancy#138]
Hello,
thank you for this package.

At the moment I am learning Laravel and in the same time trying the multitenancy.

To use a different filesystem disk for each tenant I made a new task with this code.

```
class FilesystemTask implements SwitchTenantTask
{
    /** @var Application */
    protected $app;

    /** @var array */
    public $originalPaths = [];

    public function makeCurrent(Tenant $tenant): void
	{
		$this->setTenantFileSystem($tenant);
                Artisan::call('storage:link');
	}

	public function forgetCurrent(): void
	{
		//
	}

	protected function setTenantFileSystem(Tenant $tenant)
    {
        config()->set('filesystems.disks.tenant.url', env('APP_URL') . "/assets/customer{$tenant->id}");

        config()->set('filesystems.links',[
            public_path("customer{$tenant->id}") => storage_path("customer{$tenant->id}" . '/app/public'),
            public_path('storage') => storage_path('app/public'),
        ]);
    }
}
```

at this point all works fine, but I am not sure that is the right way to do this.

1. Is this the right way to use the filesystem?
2. When do you use the forgetCurrent()?
3. is this Artisan::call('storage:link'); necessary?
4. there is a way to use the filesystem without a symlink?

Thank you for help
Best regards

**Comment by masterix21** [comment]
Hi, @Franco2911.

1. Yes, using a custom FilesystemTask
2. It's required when you change the tenant or restore the landlord status
3. It's wrong to change the symlink because you'll get a concurrency error.
4. I'll be repetitive, but remove the symlink from there 😇

Another error could be the assets directory because all files are in the storage directory. So, move it to `"/storage/"` and finally, if you need to store public files, use the public directory (symlinked before, but only for the first deploy of your app).

I'm closing the issue, but feel free to continue the discussion. Thanks.

**Comment by Franco2911** [comment]
Thank you for your advices,
Like I said I am learning Laravel and Multinancy and I am not sure to understand all what you told me.

In my tests I imagine a public folder with interface assets and for each tenant a "public" folder for tenant datas like documents, images, logos etc...

With my actual code I create a symlink for each tenant and one symlink for for the public folder. The tenant folder was created at the tenant creation.

```
config()->set('filesystems.links',[
            public_path("customer{$tenant->id}") => storage_path("customer{$tenant->id}" . '/app/public'),
            public_path('storage') => storage_path('app/public'),
        ]);
```
3. I am not changing the symlink it is added for each tenant `public/customer1000/images/myLogo.png` per example.
If this is wrong like i understood, how can I use the tenant files in blade or react interface?

Maybe, you some example without giving me the entire solution, need to understand how all work together.

Thank you for your help
Best regards
