### ISSUE TITLE
Middleware identification = Invalid catalog name: 1046 No database selected

### ISSUE THREAD

**Issue by dambridge** [spatie/laravel-multitenancy#141]
Completely lost on this error. I'm using a middleware (IdentifyTenant) to determine tenants like so:

```php
    public function handle(Request $request, Closure $next)
    {
        if ($request->session()->has('current_tenant')) {

            $currentTenantId =  $request->session()->get('current_tenant');

            /** @var Tenant $tenant */
            $tenant = $this->getTenantModel()::where('id', $currentTenantId)->first();
            $tenant->makeCurrent();

            return $next($request);

        } else {

            throw new NotFoundHttpException;

        }
    }
```

Kernel.php:
```php
    'tenant' => [
        \App\Http\Middleware\IdentifyTenant::class,
        \Spatie\Multitenancy\Http\Middleware\NeedsTenant::class,
        \Spatie\Multitenancy\Http\Middleware\EnsureValidTenantSession::class,
    ]
```
I'm not actually sure the middleware is even 'running' per se, as no dd() even works in it. I do, however, see it listed in the request stack and if I put garbage in it, it will error out as expected...

I'm using Laravel 8 with Fortify/Jetstream, and this error occurs after registration and redirection to the Dashboard

**Comment by masterix21** [comment]
Hi @dambridge, your route uses `Route::get(...)->middleware('tenant')`?

**Comment by masterix21** [comment]
I'm closing the issue because isn't related to the package, but feel free to continue the talk here ;)
