### ISSUE TITLE
Can't use route params in TenantFinder

### ISSUE THREAD

**Issue by ragulka** [spatie/laravel-multitenancy#143]
I'm trying to identify the tenant by path and have created the following custom TenantFinder:

```php
public function findForRequest(Request $request): ?Tenant
{
    $slug = $request->route('tenant');

    $request->route()->forgetParameter('tenant');

    return $this->getTenantModel()::whereSlug($slug)->first();
}
```

The problem is that I get a `Call to a member function forgetParameter() on null` error. I also noticed that `dd($slug)` will return null, but if I `dd($slug)` inside the controller action, it does return the route param value.

I tried disabling the `NeedsTenant` middleware on my tenant routes so I could manually determine the current tenant, but it looks like this package will try to find the tenant on each request regardless if it's a tenant route or not.

When the app boots, the service provider goes through the following parts:

* https://github.com/spatie/laravel-multitenancy/blob/master/src/MultitenancyServiceProvider.php#L29
* https://github.com/spatie/laravel-multitenancy/blob/master/src/MultitenancyServiceProvider.php#L99
* https://github.com/spatie/laravel-multitenancy/blob/master/src/MultitenancyServiceProvider.php#L62

This means that it's trying to find the tenant in app boot, which is probably too early for route params to work.

I also find it's rather unexpected that it would try to determine the tenant on each request.

**Comment by masterix21** [comment]
Skip your custom TenantFinder and move your logic inside a Middleware.

**Comment by masterix21** [comment]
I'm closing the issue because isn't related to the package, but feel free to continue the talk here ;)
