### ISSUE TITLE
Unable to prefix cache

### ISSUE THREAD

**Issue by webmastervinay** [spatie/laravel-multitenancy#147]
**Laravel Version: 7.x**

I followed the steps to prefix cache and put it in the SwtichTenantTask array.

```
use Spatie\Multitenancy\Models\Tenant;

class PrefixCacheTask implements SwitchTenantTask
{
    protected ?string $originalPrefix;

    public function __construct()
    {
        $this->originalPrefix = config('cache.prefix');
    }

    public function makeCurrent(Tenant $tenant): void
    {
        $this->setCachePrefix("tenant_{$tenant->id}");
    }

    public function forgetCurrent(): void
    {
        $this->setCachePrefix($this->originalPrefix);
    }

    protected function setCachePrefix(string $prefix): void
    {
        config()->set('cache.prefix', $prefix);

        $storeName = config('cache.default');

        app('cache')->forgetDriver($storeName);
    }
}

```

Unfortunately, the cache prefix is not working even after forgetDriver is called and I am getting first tenant cache value when obtaining cache value after switching to second tenant.

I even tried @themsaid [video](https://www.youtube.com/watch?v=Ibd8stzF1KQ) and pull the [repo](https://github.com/themsaid/multitenancy-example) and then call forgetDriver function after setting prefix.

```
  // App\Tenant model
    public function configure()
    {
        config([
            'database.connections.tenant.database' => $this->database,
            'cache.prefix' => $this->id
        ]);

        DB::purge('tenant');

        app('cache')->forgetDriver(config('cache.default')); // cache.default is "file"

        return $this;
    }
```

But the cache value what I am getting is the latest cache value set by any tenant.

![image](https://user-images.githubusercontent.com/5024049/95009990-9e19d280-0643-11eb-835b-059a17db5719.png)

Is there anything I am missing?

**Comment by freekmurze** [comment]
I'm thinking this problem might be caused by a cached config. Are you sure the task is being called?

If the problem persist, please add a failing test here: https://github.com/spatie/laravel-multitenancy/blob/master/tests/Feature/Tasks/PrefixCacheTaskTest.php
