### ISSUE TITLE
Seeders only for landlord

### ISSUE THREAD

**Issue by netdjw** [spatie/laravel-multitenancy#148]
Is there any way to create seeders only for landlord database?

I tried to put seeders into `/database/seeders/landlord/` folder, but doesn't helped.

**Comment by masterix21** [comment]
Hi @netdjw,

in your DatabaseSeeder class, you could verify if the tenant exists: if it doesn't exist, you could call a LandlordSeeder class.

**Comment by netdjw** [comment]
Could you give me an example code, please? Your documentation page say `No results found for query "LandlordSeeder"` and my installed version of your package doesn't contains any `LandlordSeeder` class.

**Comment by kurucu** [comment]
Hi @netdjw, there's an example for this here: https://spatie.be/docs/laravel-multitenancy/v1/installation/using-multiple-databases#seeding-tenant-databases
