### ISSUE TITLE
Make sure that tenants:artisan switches back to the original tenant / landlord

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-multitenancy#149]
In order to fix this issue: https://github.com/spatie/laravel-schedule-monitor/issues/26

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this. If none comes in, I'll take care of it myself soon.

**Comment by masterix21** [comment]
Don't worry; I'll take a look within this week.

**Comment by freekmurze** [comment]
Thanks @masterix21, much appreciated!

**Comment by masterix21** [comment]
Update about the issue.

@freekmurze, as I wrote in the [previous issue](https://github.com/spatie/laravel-schedule-monitor/issues/26), `tenants:artisan` already switches back to the original tenant/landlord.

Check it:
https://github.com/spatie/laravel-multitenancy/blob/7519e3cfbefe1092d358409a4df0f4b0058fd06e/src/Commands/Concerns/TenantAware.php#L34

I tried to simulate the user's bug but seems that it works. I will dig better this weekend.

**Comment by masterix21** [comment]
@freekmurze, I'm closing the issue because was a misconfiguration in the original issue.
