### ISSUE TITLE
Issue with Finding tenant using middleware

### ISSUE THREAD

**Issue by jamesh-purr** [spatie/laravel-multitenancy#150]
Hello,

I appear to be having an issue with the package finding the tenant when using the tenant middleware. I have gone through the docs quite a few times and I geniuneally cant see where I have gone wrong. I am using the default tenant finder/switchdata task. Please see my code below. If you point me where things are going wrong I would appreicate it.

multitenancy.php
```php
<?php
use App\Models\Tenant;
use Spatie\Multitenancy\Actions\ForgetCurrentTenantAction;
use Spatie\Multitenancy\Actions\MakeQueueTenantAwareAction;
use Spatie\Multitenancy\Actions\MakeTenantCurrentAction;
use Spatie\Multitenancy\Actions\MigrateTenantAction;
use Spatie\Multitenancy\Tasks\SwitchTenantDatabaseTask;
use Spatie\Multitenancy\TenantFinder\DomainTenantFinder;

return [
/*
* This class is responsible for determining which tenant should be current
* for the given request.
*
* This class should extend Spatie\Multitenancy\TenantFinder\TenantFinder
*
*/
'tenant_finder' => DomainTenantFinder::class,

/*
 * These fields are used by tenant:artisan command to match one or more tenant
 */
'tenant_artisan_search_fields' => [
    'id',
],

/*
 * These tasks will be performed when switching tenants.
 *
 * A valid task is any class that implements Spatie\Multitenancy\Tasks\SwitchTenantTask
 */
'switch_tenant_tasks' => [
    SwitchTenantDatabaseTask::class,
],

/*
 * This class is the model used for storing configuration on tenants.
 *
 * It must be or extend `Spatie\Multitenancy\Models\Tenant::class`
 */
'tenant_model' => Tenant::class,

/*
 * If there is a current tenant when dispatching a job, the id of the current tenant
 * will be automatically set on the job. When the job is executed, the set
 * tenant on the job will be made current.
 */
'queues_are_tenant_aware_by_default' => true,

/*
 * The connection name to reach the tenant database.
 *
 * Set to `null` to use the default connection.
 */
'tenant_database_connection_name' => 'tenant',

/*
 * The connection name to reach the landlord database
 */
'landlord_database_connection_name' => 'landlord',

/*
 * This key will be used to bind the current tenant in the container.
 */
'current_tenant_container_key' => 'currentTenant',

/*
 * You can customize some of the behavior of this package by using our own custom action.
 * Your custom action should always extend the default one.
 */
'actions' => [
    'make_tenant_current_action' => MakeTenantCurrentAction::class,
    'forget_current_tenant_action' => ForgetCurrentTenantAction::class,
    'make_queue_tenant_aware_action' => MakeQueueTenantAwareAction::class,
    'migrate_tenant' => MigrateTenantAction::class,
],
];
```

web.php
```php
<?php
Route::middleware('tenant')->group(function() {

    Route::get('/', function () {
        return 'hello';
    });
});
```

kernel.php
```php
<?php

 protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
        'tenant' => [
            \Spatie\Multitenancy\Http\Middleware\NeedsTenant::class,
            \Spatie\Multitenancy\Http\Middleware\EnsureValidTenantSession::class
        ],

        'api' => [
            'throttle:api',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];
```

DB - tenants
| domain name  | database |
| ------------- | ------------- |
| test.local  | test1  |

Database.php
```php
<?php

'tenant' => [
            'driver' => 'mysql',
            'url' => env('TENANT_DATABASE_URL'),
            'host' => env('TENANT_DB_HOST', '127.0.0.1'),
            'port' => env('TENANT_DB_PORT', '3306'),
            'database' => null,
            'username' => 'root',
            'password' => '',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],

        'landlord' => [
            'driver' => 'mysql',
            'url' => env('LANDLORD_DATABASE_URL'),
            'host' => env('LANDLORD_DB_HOST', '127.0.0.1'),
            'port' => env('LANDLORD_DB_PORT', '3306'),
            'database' => 'landlord',
            'username' => 'root',
            'password' => '',
            'unix_socket' => env('LANDLORD_DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],
```

.env
```php
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:hFDbaEmcHArPtN1+5vSXan7k34GQUlUYLKRNySjVKtc=
APP_DEBUG=true
APP_URL=http://website-designer.local

LOG_CHANNEL=stack

LANDLORD_DB_CONNECTION=landlord
LANDLORD_DB_HOST=127.0.0.1
LANDLORD_DB_PORT=3306
LANDLORD_DB_DATABASE=landlord
LANDLORD_DB_USERNAME=root
LANDLORD_DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
```

Tenant Model (My custom tenant model)
```php
<?php
namespace App\Models;

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Spatie\Multitenancy\Models\Tenant as DefaultTenant;

class Tenant extends DefaultTenant
{
    public static function booted()
    {
        static::creating( fn(Tenant $model) => $model->createDatabase() );
    }

    public function createDatabase()
    {
//        $this->database = "tenantdb_" . uniqid();
//        $this->save();
//
//        $db = DB::connection();
//
//        $charset = $db->getConfig('charset');
//        $collation = $db->getConfig('collation');
//
//        $db->statement('CREATE DATABASE ' . $this->getDatabaseName() . " CHARACTER SET `$charset` COLLATE `$collation`");
//
//        Artisan::call('tenants:artisan', [
//            "artisanCommand" => "migrate --database=tenant",
//            "--tenant" => $this->id,
//        ]);
    }
}
```

ERROR
Spatie\Multitenancy\Exceptions\NoCurrentTenant
The request expected a current tenant but none was set. 

I can't see anything wrong with what I have done. So please enlighten me :D

**Comment by freekmurze** [comment]
Could you please format the code in issue better? Thanks!

**Comment by jamesh-purr** [comment]
> Could you please format the code in issue better? Thanks!

SORRY @freekmurze !!, github code tags suck!. I have created some pastebins.

**Comment by masterix21** [comment]
@jamesh-purr, I have edited the code for you. 

About your issue, are you catch the error opening the landlord URL or the tenant URL? I'm asking it because you are using the tenant middleware on the root path, and it could be used by the landlord too.

**Comment by jamesh-purr** [comment]
> @jamesh-purr, I have edited the code for you.
> 
> About your issue, are you catch the error opening the landlord URL or the tenant URL? I'm asking it because you are using the tenant middleware on the root path, and it could be used by the landlord too.

@masterix21 thanks for doing that! It wasn't clear 3 back ticks were needed for the code block :D 

I see where you are coming from on the route being same as the landlord. I actually only did that to make it more simple. I actually had it like this.

```
Route::middleware('tenant')->group(function() {
    Route::get('/', function () {
        return 'hello';
    });
    Route::group(['middleware' => ['role:Administrator']], function () {
        Route::prefix('shop-admin')->group(function () {
            Route::name('shop-admin.')->group(function () {
                Route::get('/', [ShopAdminDashboard::class, 'index'])->name('dashboard');
            });
        });
    });
});
```

This still doesn't work. No matter the url I have the same error. I can access the urls if I take them out of the middleware but then the site wont be tenant aware and I can login etc as it tries to use the default db. If you would like full access to the repo let me know. I am just a bit stuck and I am not sure where the issue is :(

PS thanks again for trying to help.

**Comment by masterix21** [comment]
I'm sorry for the stupid question, but, are you sure that your URL is an existing tenant URL?

**Comment by jamesh-purr** [comment]
> I'm sorry for the stupid question, but, are you sure that your URL is an existing tenant URL?

Of course there is no silly questions when trying to help :P 

Please see attached, The landlord tenants table contains the below. I then have the test1 db created and migrated.

![WhatsApp Image 2020-10-16 at 09 58 01](https://user-images.githubusercontent.com/42927247/96439365-a0149180-11fe-11eb-9c34-f2957bf9d8ac.jpeg)

**Comment by masterix21** [comment]
Okay. You are in error using http://website-designer.local or using HTTP://test1.local ?

**Comment by jamesh-purr** [comment]
> Okay. You are in error using http://website-designer.local or using [HTTP://test1.local](HTTP://test1.local) ?

I just double checked and I updated the routes file like so

```
Auth::routes();
Route::get('/', function () {
    return 'hello';
});

// Landlord Admin routes
Route::group(['middleware' => ['role:Administrator']], function () {
    Route::prefix('landlord-admin')->group(function () {
        Route::name('landlord-admin.')->group(function () {
            Route::get('dashboard', [ DashboardController::class, 'index' ])->name('dashboard');
        });
    });
});

// ShopAdmin Admin routes
Route::middleware('tenant')->group(function() {
    Route::get('/', function () {
        return 'hello';
    });
    Route::group(['middleware' => ['role:Administrator']], function () {
        Route::prefix('shop-admin')->group(function () {
            Route::name('shop-admin.')->group(function () {
                Route::get('/', [ShopAdminDashboard::class, 'index'])->name('dashboard');
                Route::get('/', [ShopAdminDashboard::class, 'index'])->name('dashboard');
            });
        });
    });
});
```

And I did some debugging on the middleware and I can there isn't a connection being used? I am not sure why?

![Screenshot 2020-10-19 at 16 20 34](https://user-images.githubusercontent.com/42927247/96471446-44aac980-1227-11eb-9843-dd12ae61be46.png)

**Comment by masterix21** [comment]
I see "www.test1.local" in your URL, but you have only "test1.local" in your database. Could it be the problem?

**Comment by jamesh-purr** [comment]
> I see "www.test1.local" in your URL, but you have only "test1.local" in your database. Could it be the problem?

Hey great spot! but unfortunately that wasn't it. Again I have been doing some digging and I can see the landlord databaseis hit and it finds the tenant in the DB. However again the model connection is null hence it not finding the tenant db data.

I have tried no longer using custom tenant model I still have the same issue

![Screenshot_2020-10-19 Screenshot](https://user-images.githubusercontent.com/42927247/96473609-c56ac500-1229-11eb-8e41-c4a211d59171.png)


There is 100% an issue with my db setup but what and where again i don't know :(

**Comment by masterix21** [comment]
Please post the output of your `php artisan route:list`

**Comment by CW92** [comment]
Attached is the output from `php artisan route:list` on the same project

<img width="1141" alt="Screenshot 2020-10-19 at 17 04 00" src="https://user-images.githubusercontent.com/47077926/96476657-6c049500-122d-11eb-9401-e91a37c417be.png">

**Comment by masterix21** [comment]
Please post the query log using the laravel-debugbar because, for me, you have a problem with the URL.

Thanks

**Comment by CW92** [comment]
It appears as though it isn't firing any requests.

![_20201019_175629.JPG](https://user-images.githubusercontent.com/47077926/96485316-770ef380-1234-11eb-95e4-3c706440506e.JPG)

**Comment by jamesh-purr** [comment]
> Please post the query log using the laravel-debugbar because, for me, you have a problem with the URL.
> 
> Thanks

Hey @masterix21 

Please see attached. I am pretty confident there is a db connection issue some where. Its not hitting the landlords tenants table correctly and then setting the connection for the tenant

![Screenshot 2020-10-19 at 17 59 42](https://user-images.githubusercontent.com/42927247/96487314-f3093b80-1234-11eb-80a7-7a19c0cac9dd.png)

**Comment by jamesh-purr** [comment]
Hey @masterix21 

Thanks for all your help. I managed to find the issue and it was url related. dumb-ass.com i was being! Sorry for taking so long to relise it!

I will close this now!

**Comment by masterix21** [comment]
It was my first suggestion, anyway. I’m happy that you found a solution.

Have a nice day!
