### ISSUE TITLE
Share some Cache Values with All Tenants while using Cache Prefixing

### ISSUE THREAD

**Issue by anwardote** [spatie/laravel-multitenancy#153]
Hi,

I am in a situation where I need to use Cache Prefix and at the same time, I need global Cache Values which should be shared with all Tenants.

Example: 
**Situation 1:** I have a Department list which list will be different according to Tenant... so, in this case, I would like to use the Prefixing caching system.

**Situation 2:** I also have some settings list which will be the same for all Tenants, In this case, I would like to use global cache (without prefix cache) system so that one cache key is being used globally. Because I think, I will be helpful for redis memory.

Has there any way to solve this situation?

Thank you in advance

Anwar

**Comment by masterix21** [comment]
What do you think to use `Landlord::execute(fn () => Cache::get('your-shared-key'));`?

**Comment by anwardote** [comment]
@masterix21 

Thank you. Yea, It might be a solution.

But I am hoping to get **LandlordCache**, **SharedCache** type solution with easy settings and usages. In the multitenancy application, this feature is very important.

Waiting for @freekmurze comments regarding this feature

**Comment by freekmurze** [comment]
Could you just use two different cache connections? One for the tenants (that you swap for each tenant using a task), and one connection for the landlord cache?

That way we wouldn't have to modify anything in our package.

**Comment by masterix21** [comment]
@freekmurze, if I’m not wrong, the cache prefix is a global parameter in the Laravel configuration. Using multiple stores doesn't solve the problem (i think): I'll take a look.

**Comment by masterix21** [comment]
I can confirm what @freekmurze said: we can use different cache stores. For example:

```php
// config/cache.php
return [
    'default' => env('CACHE_DRIVER', 'redis'),

    'stores' => [
        'redis' => [
            'driver' => 'redis',
            'connection' => 'cache',
        ],
        'landlord' => [
            'driver' => 'redis',
            'connection' => 'cache',
            'prefix' => 'landlord',
        ],
    ],
];
```

Now, we can use different cache stores in this way:
```php
cache()->driver('landlord')->put('who', 'Landlord cache');

$tenant = Tenant::first();
$tenant->makeCurrent();
cache()->put('who', $tenant->name .' cache');

echo cache()->get('who') . PHP_EOL; // output: Tenant 1 cache
echo cache()->driver('landlord')->get('who') . PHP_EOL; // output: Landlord cache
```

Great and simple! Wonderful 🥰
