### ISSUE TITLE
Registering users on a tenant subdomain results in "Database connection [mysql] not configured"

### ISSUE THREAD

**Issue by bryanjamesmiller** [spatie/laravel-multitenancy#155]
Hi, thanks for the great package.

I carefully followed your documentation and I have a simple basic install working, as I can seed users for each tenant and then the users for only the corresponding tenant appear as expected when I visit each tenant's subdomain.  I can see this working on my login/registration pages generated by laravel-frontend-presets/tailwindcss.  I haven't made any adjustments to the scaffolding provided by laravel-frontend-presets/tailwindcss.  However, when I try to register a new user (or reset a password), and I'm on a tenant's subdomain, I am given a "Database connection [mysql] not configured" error.  I don't have a `mysql` connection defined, I only have a `landlord` and a `tenant` connection (as the documentation recommends).

I'm wondering what the best way to get all the routes provided by Auth::routes(); to recognize the tenant connection that is otherwise working as expected (since I can see the seeded users just for that tenant on the user registration page)?  It's clearly recognizing the tenant database connection to display those users, but why is the wrong connection (mysql) being used for user registration (and possibly other behind-the-scenes items that should be scoped to the current tenant like Observers and Jobs)?

It seems to me like something in laravel-frontend-presets/tailwindcss may be overriding the tenant connection that is being set by spatie/laravel-multitenancy?

**Comment by bryanjamesmiller** [comment]
I figured out a partial solution, but I'm wondering what is the expected setting here.  In config/database.php, I had this:

`'default' => env('DB_CONNECTION', 'mysql'),`

and when I changed it to this, it fixed the issue:

`'default' => env('DB_CONNECTION', 'tenant'),`

Is `tenant` supposed to be the `default` config value here?

**Comment by masterix21** [comment]
My suggestion is to change your `DB_CONNECTION` in the .env file.

Next, for your routes, use the `tenant` middleware (see the doc).

**Comment by masterix21** [comment]
Keep your `tenant` connection parameters empty, so if they are present, they are filled by `SwitchDatabaseTask`, and you should be sure that points to the correct connection.
