### ISSUE TITLE
Question: Register service porvider after tenant tasks 

### ISSUE THREAD

**Issue by mostafakram** [spatie/laravel-multitenancy#160]
Sorry if this is not the right place to ask questions. 

I have a SwitchTenantTask that define some configs according to the tenant 

```php
config($addedConfigs);
```

And these configs i mark them as null in their config files the same way the tenant connection config is handled 

I faced an issue that a package service provider was calling the config values before the `switch_tenant_tasks` get called so the config value for it is always null 

To handle this i added removed this package from `composer.json` auto-discover 
```json
"extra": {
    "laravel": {
        "dont-discover": [
            "vendor/package"
        ]
    }
}
```

and created a new task called RegisterServiceProviders that is inserted under the configs task and it does one thing 

```php
    public function makeCurrent(Tenant $tenant): void
    {
        app()->register(
            \Vendor\ServiceProvider::class
        );
    }
```

is this a correct approach for doing such a thing ? 

Thanks in advance

**Comment by mostafakram** [comment]
Actually i found another solution 
i have removed both "vendor/package" and "spatie/laravel-multitenancy" from auto discovery 
and registered both manually in `app.php` making `Spatie\Multitenancy\MultitenancyServiceProvider::class`  registered before the other package's service provider

**Comment by masterix21** [comment]
> Actually i found another solution 
> 
> i have removed both "vendor/package" and "spatie/laravel-multitenancy" from auto discovery 
> 
> and registered both manually in `app.php` making `Spatie\Multitenancy\MultitenancyServiceProvider::class`  registered before the other package's service provider 

It sounds delicious: it’s the right way.
