### ISSUE TITLE
Tenants migration exit with exit code when no tenants found and kill the github action flow

### ISSUE THREAD

**Issue by netdjw** [spatie/laravel-multitenancy#162]
When I try to deploy the project with this package - and of course in the beginning I don't have any tenants - next command exit with an error code:

`php artisan tenants:artisan "migrate --database=tenant"`

The result is:

```
No tenant(s) found.
Error: Process completed with exit code 255.
```

I belive this isn't an error... this is just an initial case and nothing to do.

Is there any way to exit without error code in this case?

**Comment by masterix21** [comment]
Hi @netdjw,

```bash
➜  landlord a tenants:artisan "migrate --database=tenant"
No tenant(s) found.
➜  landlord
```

how we can simulate your error? 

Thanks

**Comment by netdjw** [comment]
I think if you create a brand new project and don't put any records into your database tenants table. All migration is done, but nothing to seed.

**Comment by masterix21** [comment]
Hi @netdjw, I have tried, but I can't get the error `Error: Process completed with exit code 255.`.

I'm closing the issue, but feel free to continue the discussion here. Thanks.
