### ISSUE TITLE
Call to a member function prepare() on null

### ISSUE THREAD

**Issue by udiptaweb** [spatie/laravel-multitenancy#165]
i am trying to run the code below inside controller

Artisan::call("tenants:artisan down --tenant={$tenant->id}");

and it shows the error
Call to a member function prepare() on null

What might be the error here?.
Although it works fine while running from console.

**Comment by masterix21** [comment]
The standard down command creates a file called `down` in the storage path; when it exists, the application returns a Service Unavailable message (error 503): all functionalities are not available from the web (but only from console).

I'm not sure if changing the storage path per tenant will help you to isolate the "down" command per tenant, so, after all these considerations, I think it's better to implement your own logic to put one or more tenants in a "down" state, because using the default one could occur any unexpected error like yours.

**Comment by udiptagogoi** [comment]
> The standard down command creates a file called `down` in the storage path; when it exists, the application returns a Service Unavailable message (error 503): all functionalities are not available from the web (but only from console).
> 
> I'm not sure if changing the storage path per tenant will help you to isolate the "down" command per tenant, so, after all these considerations, I think it's better to implement your own logic to put one or more tenants in a "down" state, because using the default one could occur any unexpected error like yours.

Well I have actually changed the storage path per tenant and showing this error after that.I am getting the same error while trying to use Artisan::call("tenants:artisan migrate --tenant={$tenant->id}") after creating a new tenant and database. But the database migrated successfully.

**Comment by masterix21** [comment]
Are you using a custom task? Please post your code.

Thanks

**Comment by udiptaweb** [comment]
No i am not using a custom task.

Using the below code to create new tenant with database create and migration. It successfully creates tenant, database and migrated. But after that it shows the above error message.
`try {
            if ($this->isTenantExists($this->domain)) {
                throw new Exception("Error Processing Request", 1);
            }
            $tenant = Tenant::create([
                'name' => $this->name,
                'domain' => $this->domain,
                'database' => $this->database,
            ]);
            if ($this->isDatabaseExists($this->database)) {
                throw new Exception("Error Processing Request", 1);
            }
            $charset = config("database.connections.mysql.charset", 'utf8mb4');
            $collation = config("database.connections.mysql.collation", 'utf8mb4_unicode_ci');
            $query = "CREATE DATABASE IF NOT EXISTS $this->database CHARACTER SET $charset COLLATE $collation;";

            DB::statement($query);
            Artisan::call("tenants:artisan migrate --tenant={$tenant->id}");
            $this->emit('alert', ['type' => 'success', 'msg' => "A new tenant {$this->name} has been created"]);
        } catch (\Throwable $th) {
            $this->emit('alert', ['type' => 'success', 'msg' => "Server error. Please try again later"]);
            Log::error($th);
        }`

**Comment by masterix21** [comment]
If all steps are completed, the problem isn't in these code lines. What happens next? Do you have events and listeners?

**Comment by udiptagogoi** [comment]
No i dont have event and listeners. After completing migration it throws the error below

![NXalJ](https://user-images.githubusercontent.com/28784995/99148692-2b266180-26af-11eb-806e-31cbee1fb4de.png)

**Comment by udiptaweb** [comment]
No i dont have event and listeners. After completing migration it throws error below
![NXalJ](https://user-images.githubusercontent.com/57178072/99148767-a4be4f80-26af-11eb-9e7e-ee2ba703b245.png)

**Comment by masterix21** [comment]
Please post the error stacktrace (full)

**Comment by udiptagogoi** [comment]
This is the complete trace

https://flareapp.io/share/353rlAn7

**Comment by masterix21** [comment]
It seems that the session driver causes the issue. Try to switch the driver to file (only for test), and give us feedback.

Thanks

**Comment by udiptagogoi** [comment]
Oh yes!. It's a session driver issue. Thnak you very much.

**Comment by cjmcdonn** [comment]
Any information on how to resolve this while still keeping `SESSION_DRIVER=database`? It seems that any time I try and switch connections mid-request I end up with the same error: `Call to a member function prepare() on null`. For example, I am trying to look up alpha subdomain users from the admin subdomain.

Changing to `SESSION_DRIVER=file` fixes the error, but I don't think that is a permanent solution for me.

**Comment by eswachsman** [comment]
Same issue for me. Why is this closed?

**Comment by masterix21** [comment]
@cjmcdonn (and @eswachsman) are you using the tenant database connection as default?

**Comment by eswachsman** [comment]
Yes

config/database.php:
`'default' => env('DB_CONNECTION', 'tenant'),`

.env:
`DB_CONNECTION=tenant`

**Comment by masterix21** [comment]
This is the problem: landlord should be the default connection.

**Comment by eswachsman** [comment]
@masterix21 still the same issue.

**Comment by eswachsman** [comment]
For me, I have the issue even when `SESSION_DRIVER=file`

**Comment by masterix21** [comment]
Try with `php artisan optimize:clear`

**Comment by eswachsman** [comment]
That seemed to do it. Thanks so much!!

Good command to remember...

**Comment by Libero-Software** [comment]
> Any information on how to resolve this while still keeping `SESSION_DRIVER=database`? It seems that any time I try and switch connections mid-request I end up with the same error: `Call to a member function prepare() on null`. For example, I am trying to look up alpha subdomain users from the admin subdomain.
> 
> Changing to `SESSION_DRIVER=file` fixes the error, but I don't think that is a permanent solution for me.

Did you ever find a solution? I`m having the same error. When using database session, i get the same error.

**Comment by truthytech** [comment]
@libero-developer did you ever resolve this? I have the same issue.
