### ISSUE TITLE
i am getting erro when trying to install

### ISSUE THREAD

**Issue by Ghyanmitra** [spatie/laravel-multitenancy#166]
composer require "spatie/laravel-multitenancy:^1.0"

  [Composer\Downloader\TransportException]
  getaddrinfo() thread failed to start

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...

**Comment by masterix21** [comment]
Sorry, but it seems a connection problem.

I'm closing it, but feel free to continue the discussion. Thanks
