### ISSUE TITLE
Unique rules does not work

### ISSUE THREAD

**Issue by rezuankassim** [spatie/laravel-multitenancy#167]
- Laravel Multitenancy Version: 1.6.9
- Laravel Version: v8.12.3
- PHP Version: 7.4.10

### Description:
I was unable to use unique rules when creating new records under tenant's database when using multi-database approach.
I got the error below.
<img width="1229" alt="Screenshot 2020-11-16 at 9 39 04 AM" src="https://user-images.githubusercontent.com/53212160/99204113-937c5c80-27ef-11eb-9b7e-bc166858c2e1.png">

When I run `config()->get('database.connections')` in Livewire mount method, I get the following result.
<img width="453" alt="Screenshot 2020-11-16 at 9 40 52 AM" src="https://user-images.githubusercontent.com/53212160/99204204-e6561400-27ef-11eb-99d9-c4538a59ab0e.png">

When I run `config()->get('database.connections') in Livewire methods, I get the following results.
<img width="453" alt="Screenshot 2020-11-16 at 10 12 12 AM" src="https://user-images.githubusercontent.com/53212160/99205754-6a11ff80-27f4-11eb-99c8-597bc1a6c143.png">

**Comment by masterix21** [comment]
Hi @rezuankassim. Please post your validation rules.

Thanks

**Comment by rezuankassim** [comment]
Hi @masterix21 thanks for replying,

I have fixed the issued I have facing, it is because of Livewire is using `web` middleware for its `livewire/message` ajax call and my `web` middleware does not have 
```
\Spatie\Multitenancy\Http\Middleware\NeedsTenant::class
\Spatie\Multitenancy\Http\Middleware\EnsureValidTenantSession::class
```
Therefore I added a custom middleware for `livewire/message` to check if the user is a `landlord` or a `tenant`, if it is a `tenant` then I will run the two middleware above.

**Comment by masterix21** [comment]
It sounds good. Thanks for your share.
