### ISSUE TITLE
syntax error, unexpected '$tenant' (T_VARIABLE), expecting ')'

### ISSUE THREAD

**Issue by TychaK** [spatie/laravel-multitenancy#168]
I added a virtual domain that points to the Laravel application with the Spatie Multitenancy and got the following issue:

![Screenshot from 2020-11-17 13-36-57](https://user-images.githubusercontent.com/11659515/99379832-38736400-28da-11eb-9a3b-8825fa82d59a.png)

PHP 7.4
Laravel 7.29

How do we solve this?

**Comment by masterix21** [comment]
Are you sure that you are on PHP 7.4?

**Comment by TychaK** [comment]
Yes I'm on PHP 7.4

php -v

PHP 7.4.11 (cli) (built: Oct 18 2020 19:39:25) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies

**Comment by masterix21** [comment]
Are you sure that you are not using a different version for PHP-fpm than PHP-cli? Please post your phpinfo output from your web server. Thanks.

**Comment by TychaK** [comment]
Hi,

My bad, The issue was completely unrelated to the package. I've been able to fix the issue.

Thank you for your assistance and the package!
