### ISSUE TITLE
Fix documentation link

### ISSUE THREAD

**Issue by clablancherie** [spatie/laravel-multitenancy#169]
Hi,

When i click on that link : https://spatie.be/docs/laravel-multitenancy/v1/using-tasks-to-prepare-the-environment/filesystem/ at the bottom of this page https://spatie.be/docs/laravel-multitenancy/v1/installation/using-multiple-databases , i'm redirected to https://spatie.be/docs/laravel-multitenancy/v1/introduction

This page seems to not exist, so maybe just delete the href or create the page please (My favorite solution <3)

Regards,

**Comment by masterix21** [comment]
I don't know why the @freekmurze's team has removed these links, but if you think that the pages are useful, please make a PR.

Thank you
