### ISSUE TITLE
Question...

### ISSUE THREAD

**Issue by KatiaSishost** [spatie/laravel-multitenancy#172]
hello... im making app multi tenant... but 1 app... using laravel 8

example:

shop1.example.com
shop2.example.com
shop3.example.com

i have the service working well.. but the users need register into shop1_db.... shop2_db etc... y need use multiple database to shop1... shop2... shop3... etc... but... only 1 database users... into a main example.com

**Comment by masterix21** [comment]
Yes, you can, creating only one user model in the landlord environment using the `usesLandlordConnection` trait. If you are using the same *.example.com domain, it's simple to share the session. 

I'm closing the issue because it isn't related to a package problem, but feel free to continue the discussion.

Thanks

**Comment by KatiaSishost** [comment]
Well...  in User Model...

`<?php

namespace App\Models;

use Spatie\Multitenancy\Models\Concerns\UsesLandlordConnection;

class User extends Authenticatable
{

    use usesLandlordConnection;
`

i added this...now i can login and register (in subdomain.localhost:8000" in the main database... but... i have a problem..

when i try to enter at "localhost:8000/login" or "localhost:8000/register" 

`Spatie\Multitenancy\Exceptions\NoCurrentTenant
The request expected a current tenant but none was set.`

how to add a login and register in main domain without add record in tenants table for main domain? im using laravel8 with jetstream livewire..

**Comment by KatiaSishost** [comment]
Other detail... only can register user in sub-domain if in they database have the user database, session and more... but it save the info in the main database o.O

**Comment by masterix21** [comment]
If your User exists in the landlord context, you should remove the tenant-aware middleware from the login (and register) routes.
