### ISSUE TITLE
Run migrations for single tenant

### ISSUE THREAD

**Issue by bloomlive** [spatie/laravel-multitenancy#173]
Hey!

Very cool project, still trying it out, will send a postcard once I've verified my use-case. However, didn't find this in documentation, maybe I'm missing something: how to migrate a single tenant only? The problem is, if I migrate all the tenants and I run migrations on registration, it doesn't scale all too good, because I'll have to check migrations table for possibly thousands of tenants. 

If I could run migrations for one tenant and then run the looping one only after new deployments, that would be very nice. Is this supported and I just missed it, or should I try to figure out my own implementation?

**Comment by masterix21** [comment]
Hi @bloomlive, you can use the "--tenant=[your-tenant-id]" parameter.
