### ISSUE TITLE
not support php 8.0

### ISSUE THREAD

**Issue by simonproud** [spatie/laravel-multitenancy#174]

**Comment by Nielsvanpach** [comment]
We accept a PR for this

**Comment by freekmurze** [comment]
I've made the tests run for PHP 8, but haven't tagged a release just yet. There's one test that uses Redis seems to be failing. I don't see the cause/solution. Feel free to PR a fix. After this we can safely tag PHP 8 support

**Comment by sluxzer** [comment]
> I've made the tests run for PHP 8, but haven't tagged a release just yet. There's one test that uses Redis seems to be failing. I don't see the cause/solution. Feel free to PR a fix. After this we can safely tag PHP 8 support

is there any update on this @freekmurze ?

**Comment by freekmurze** [comment]
No, otherwise I would have posted it here.

**Comment by sluxzer** [comment]
We'll patiently wait for it then :)

thank you.

**Comment by freekmurze** [comment]
It seems like the latest version already supports PHP 8

https://github.com/spatie/laravel-multitenancy/blob/1.6.10/composer.json

**Comment by Paradinight** [comment]
Hello,
"php": "^7.4", should be "php": "^7.4|^8.0",

**Comment by freekmurze** [comment]
The latest version now supports PHP 8
