### ISSUE TITLE
[QUESTION] Best Practice..

### ISSUE THREAD

**Issue by KatiaSishost** [spatie/laravel-multitenancy#177]
Hello, I am programming a sales system, multi store ... in my current system I have 1 database per store (multi database) ... so that people can enter their subdomain example shop1.domain.com or shop2.domain.com... and buy specifically to that store ... but I want to do at the same time .. that entering domain.com enter my site which will be to be able to search for these businesses and compare them by prices, votes and others ... like Pedidos Ya? ...

My question is, is it better to use multiple databases or to use a single one? I want all clients to register on my website and to be able to buy in all stores as well ... and that the data of those clients be shared with the other stores at the same time

**Comment by masterix21** [comment]
Nobody could say to what is right or not because only you know the project. Both approaches are valid; my suggestion is to use what you think is better for you. I'm closing the issue, but feel free to continue the discussion here.
