### ISSUE TITLE
Need help for unit test

### ISSUE THREAD

**Issue by NatachaH** [spatie/laravel-multitenancy#178]
Hi !

First, thank you for this nice package :-)

In my project I want to do some basic tests, like create, edit and delete a user. Before install the multitenancy package my test work just fine. But now when I run my test I have this error:
`Invalid catalog name: 1046 No database selected`

For information, in my phpunit.xml i use:
`<server name="DB_CONNECTION" value="sqlite"/>`
`<server name="DB_DATABASE" value=":memory:"/> `

And I'm using the multiple databases (I guess that why i got some trouble...)

I'm totally new with php unit test and I just don't understand how to test the actions of a tenant. 

Can you give me an exemple of basic test and tell me which file/configuration I should use ? 

Thank you for your help.

**Comment by masterix21** [comment]
There are many issues already closed with the same topic. 

Check it: https://github.com/spatie/laravel-multitenancy/issues/97
And it: https://github.com/spatie/laravel-multitenancy/blob/master/tests/TestCase.php

Thanks
