### ISSUE TITLE
Broken link in the documentation

### ISSUE THREAD

**Issue by undjike** [spatie/laravel-multitenancy#183]
Hello, just want to report a broken link in the documentation [filesystem per tenant](https://spatie.be/docs/laravel-multitenancy/v1/using-tasks-to-prepare-the-environment/filesystem/). At https://spatie.be/docs/laravel-multitenancy/v1/installation/using-multiple-databases.

![image](https://user-images.githubusercontent.com/57102409/103353770-0133cd80-4aaa-11eb-9c87-9255ca4e8098.png)

**Comment by masterix21** [comment]
We are sorry about it. If you like, add a PR to fix it.

Thanks
