### ISSUE TITLE
Target class [currentTenant] does not exist.

### ISSUE THREAD

**Issue by jovvybersamin** [spatie/laravel-multitenancy#184]
I have two tenants admin and shop.

I was trying to access admin.tenancy.test to get the details of the admin tenant.

In my welcome.blade.php
` <p>{{ app('currentTenant') }}</p>`

I also added this on my multitenancy.php config file:

`'tenant_finder' => Spatie\Multitenancy\TenantFinder\DomainTenantFinder::class,`

Inside the app\Kernel.php
 ```
 'tenant' => [
            \Spatie\Multitenancy\Http\Middleware\NeedsTenant::class,
            \Spatie\Multitenancy\Http\Middleware\EnsureValidTenantSession::class
        ]
```

But I received this error, what went wrong?

```
Illuminate\Contracts\Container\BindingResolutionException
Target class [currentTenant] does not exist
```

**Comment by jovvybersamin** [comment]
Silly me, I found the issue. The domain name value in my tenants table is different it's using localhost instead of {domain}.multitenancy.test

**Comment by rickymerby** [comment]
Hi i have same issue
