### ISSUE TITLE
Do I need EnsureValidTenantSession middleware? 

### ISSUE THREAD

**Issue by biholaindrasinh** [spatie/laravel-multitenancy#185]
In my application, I have multiple tenants for a single user when I switch tenants then I am getting 401 response from EnsureValidTenantSession middleware. I am using Laravel Sanctum SPA authentication. My routes are stored in api.php. Do I need EnsureValidTenantSession middleware?

**Comment by masterix21** [comment]
`EnsureValidTenantSession` protect your tenants from cross-session use between domains. If you don't need it, you could remove it.

I'm closing the issue, but feel free to continue the talk.

**Comment by lasseeee** [comment]
For anyone else having this question. Watch the second video Mohamed posted here: https://divinglaravel.com/multi-tenancy-in-laravel

**Comment by valh1996** [comment]
> `EnsureValidTenantSession` protect your tenants from cross-session use between domains. If you don't need it, you could remove it.
> 
> I'm closing the issue, but feel free to continue the talk.

Thank you for your answer so if I understand correctly this does not apply to a Restful API? Sessions do not apply in this case. But should we secure differently?
