### ISSUE TITLE
Is clearing the session when switching tenants all I need to really do?

### ISSUE THREAD

**Issue by lasseeee** [spatie/laravel-multitenancy#189]
All I do when I'm switching tenants, after identifying them using the TenantFinder, I send a `GET` request to this controller to clear the session and redirect:

```
class SwitchTenantController extends Controller
{
    public function __invoke(Request $request, Tenant $tenant)
    {
        $sessionKey = 'ensure_valid_tenant_session_tenant_id';
        $request->session()->forget($sessionKey);

        return redirect()->route('tenants.home', $tenant);
    }
}

```

Is this really all I need to do when running on a single database and after adding the two middlewares?

It works flawlessly, it just seems like I might be missing something essential?

**Comment by masterix21** [comment]
Sorry, but I don't understand what you need. Have you already [read it](https://spatie.be/docs/laravel-multitenancy/v1/installation/base-installation#protecting-against-cross-tenant-abuse)?

**Comment by lasseeee** [comment]
I now realize my use case might be a different than most. I allow authorizing on the root domain and all sub domains (`SESSION_DOMAIN=.mydomain.test`, notice the preceeding dot), to allow users to belong to multiple tenants and switch between them on the fly via a dropdown menu. I have a middleware to check if they actually belong to the tenant they try to view. I would therefore not need the attached middleware to check the session, as the session is already valid everywhere, and instead check if the user is in the `user_tenant` pivot table. Sometimes writing out your thoughts helps. Thanks for publishing and maintaining this package.

**Comment by rahuls1071** [comment]
> I now realize my use case might be a different than most. I allow authorizing on the root domain and all sub domains (`SESSION_DOMAIN=.mydomain.test`, notice the preceeding dot), to allow users to belong to multiple tenants and switch between them on the fly via a dropdown menu. I have a middleware to check if they actually belong to the tenant they try to view. I would therefore not need the attached middleware to check the session, as the session is already valid everywhere, and instead check if the user is in the `user_tenant` pivot table. Sometimes writing out your thoughts helps. Thanks for publishing and maintaining this package.

Hi lasseeee, Can you please let me know how you have implemented this.

**Comment by dambridge** [comment]
> I now realize my use case might be a different than most. I allow authorizing on the root domain and all sub domains (`SESSION_DOMAIN=.mydomain.test`, notice the preceeding dot), to allow users to belong to multiple tenants and switch between them on the fly via a dropdown menu. I have a middleware to check if they actually belong to the tenant they try to view. I would therefore not need the attached middleware to check the session, as the session is already valid everywhere, and instead check if the user is in the `user_tenant` pivot table. Sometimes writing out your thoughts helps. Thanks for publishing and maintaining this package.

Am working on the exact same setup. Would be keen to see how you approached it.

**Comment by lasseeee** [comment]
I packaged up the custom solution some time ago to use in some other repos: https://github.com/lasseeee/laravel-multitenancy

Hope it helps you out. Any feedback welcome :)

**Comment by lasseeee** [comment]
My setup differs a little since I'm using a single DB for all tenants, and the file session driver. Since users are authenticated for all subdomains (to be able to switch between them without having to login again) I'll check in a middleware if they've been given access to the tenant subdomain they're trying to access.
