### ISSUE TITLE
What to put in .env and how to get DB to adhere to tenant database

### ISSUE THREAD

**Issue by cverster** [spatie/laravel-multitenancy#191]
Hi there

I started using this package and I love it so far!
I have two questions though..

Firstly, what should go in my .env file? currently I have the DB_DATABASE as set to my landlord database, but I'm not sure what database settings should be when using this package? Here is my current .env DB setup using MySQL:

```
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=landlord
DB_USERNAME=[myuser]
DB_PASSWORD=[mypass]
```

Then I want to know how to make the DB class adhere to a tenant database? Currently, I use
```
'tenant_finder' => Spatie\Multitenancy\TenantFinder\DomainTenantFinder::class,
```
and it works great when I use the right domain, but I have a pivot table that I access through the DB class as follows:

```
Schema::create('shift_person', function (Blueprint $table) {
            $table->id();
            $table->uuid('shift_id');
            $table->unsignedBigInteger('person_id');
            $table->integer('number_of_applicants');

            $table->foreign('shift_id')
                ->references('id')
                ->on('shifts');

            $table->foreign('person_id')
                ->references('id')
                ->on('persons');
        });
```
and I try to insert to it like this:
```
DB::table('shift_person')->insert([
                    'shift_id' => $shift->id,
                    'person_id' => $person_object['person_id'],
                    'number_of_applicants' => $person_object['number_of_applicants']
                ]);
```

When I try this, it tells me it can't find the pivot table on the landlord database. I'm assuming that the DB class will look at the database I have stored in DB_DATABASE by default, but how can I specify that it should look at the Tenant database similar to using the
```
use Spatie\Multitenancy\Models\Concerns\UsesTenantConnection;
```
class on a model?

**Comment by rawilk** [comment]
You should be able to use `DB::connection('tenant')->table('shift_person')->...` to insert the data into your tenant database. You may need to ensure you have a current tenant before you execute that though.

**Comment by masterix21** [comment]
`DB` facade, without a specified connection, will use always your default connection from your environment file. You can specify the connection as @rawilk suggested to you, or you improve the code using an Eloquent pivot model (please read the Laravel documentation about it).

Thanks
