### ISSUE TITLE
How to run migration for only one specific tenant?

### ISSUE THREAD

**Issue by netdjw** [spatie/laravel-multitenancy#192]
Is there any way to run a migration for only one specific tenant?

For example:

```
php artisan tenants:artisan "migrate --path=database/migrations/client-specific/myFavoritTenant --database=tenant" --tenant=myFavoritTenant
```

Or do you plan add this feature to the package?

**Comment by thijssimonis** [comment]
This is already possible. The `tenants:artisan` command is tenant aware. You can use `--tenant=value` and default it wil search on domain column. You can change this setting in `multitenancy.tenant_artisan_search_fields`.
