### ISSUE TITLE
Passing arguments and options if use quotes around not work

### ISSUE THREAD

**Issue by cmoualis** [spatie/laravel-multitenancy#193]
Hello,

I use Laravel 8 and when I run the command 
`php artisan tenants:artisan "migrate --seed"`

I have the answer The "--seed" option does not exist.

Thank you in advance for your reply

**Comment by masterix21** [comment]
Sorry, what you mean with "--seed" option doesn't exist?

Laravel migrate command has the --seed option: I'm using both migration and seed in my project with Laravel 8.x, without any pain.

I'm closing the issue but feel free to reply.

**Comment by Konafets** [comment]
I have the same problem. When running Artisan via the `tenants:artisan` command, the options of a command are not working.

Thats the output:

```
php artisan tenants:artisan "migrate --seed"

The "--seed" option does not exist.
```
