### ISSUE TITLE
Option: Multiple database connections

### ISSUE THREAD

**Issue by BartMommens** [spatie/laravel-multitenancy#194]
Hello all,

I've been looking for a multitenant solution last couple of days, reading up on multiple packages and gathering some information. This package seems to be elegant, small & lightweight. One part of the multi database approach isn't clear at the moment.

When setting up multi database approach you have two connections "Landlord and tenant"

```php
'connections' => [
    'tenant' => [
        'driver' => 'mysql',
        'database' => null,
        // other options such as host, username, password, ...
    ],

    'landlord' => [
        'driver' => 'mysql',
        'database' => 'name_of_landlord_db',
        // other options such as host, username, password, ...
    ],
```

What i understand from this approach is that all tenant databases point to a single MSQL server. 

Most shared hostings create a unique host for each database you create on your hosting e.g. tenantA.db.webhosting.be contains database for tenant A. So when create a Database for tenant B,C, ... Z you will have to switch connections as well.
This would also be used if for example a client wants to host the database on their own server.

Is there a way to configure the setup to support multiple 'tenant' connections? 

Thank you for your feedback

Best regards,
Bart

**Comment by masterix21** [comment]
Hi, @BartMommens.

Yes, you can. You should add the columns `host` and `port`, so using your custom `SwitchTenantDatabaseTask` you could do what you like to do.

I'm closing the issue but feel free to continue the talk here.

Thanks

**Comment by BartMommens** [comment]
Hi @masterix21,

Thanks for the feedback, i was taking a look at the `SwitchTenantDatabaseTask` yesterday and figured out i have to rewrite that. I'm still trying to decide whether to create a new database table to the landlord containing all the needed connection information or use .env files with the information in them like so: (storing all the info in a db table seems a bit risky or am i wrong)

`.env.tenant.xxx`

inside that file: 
`TENANT_DB_HOST=XXXX`

```
// inside SwitchTenantDatabaseTask
$dotenv = Dotenv::createImmutable(base_path(),'.env.tenant.laravel');
$dotenv->safeLoad();
$host = getEnv('TENANT_DB_HOST');
//Pass that variable to the connection
```

Since it's only my second Laravel project and i don't have full knowledge about Laravel i was wondering about the connection purging.

`DB::purge($tenantConnectionName);`

As i understand Laravel caches the connection so purging before reconnecting is best approach, is caching only applied to the current instance of the application or does it affect all running instances?

i'm not sure if it's safe to use a single name for a connection. Wouldn't it case some bugs or issues if you have for example 10 tenant instances running with heavy traffic? Since all 10 have a different database connection (shared hosts) - I might be paranoid but better to check i guess.

Thanks in advance for your insight.

Best regards,
Bart

**Comment by masterix21** [comment]
I'm using a single name for the tenant database connection and, in my project, the connection details are stored in the landlord database.

You can crypt the connection details that you store in the landlord database to decrypt when needed. Make your choice. Happy coding!

**Comment by BartMommens** [comment]
@masterix21 Thanks for your opinion, i'm gonna do some additional test and figure out which approach to take!

Thank you and happy coding :)

**Comment by codetestmg** [comment]
@BartMommens .i am also looking for similar thing.could you please provide final code of SwitchTenantDatabaseTask.

Thanks

**Comment by BartMommens** [comment]
Hey @codetestmg,

Unfortunately i have had the time to continue on this project so far. I was still researching the best approach to handle this. 
The code above is the latest version that i have. I hope to continue on this project mid March beginning of April.

Basically i would stick to their SwitchTenantDatabaseTask. And just load the connection details from a separate .env file per customer.  Or use masterix21's approach by extending the tenant model to contain all the details of the connection in the landlord database. But make sure it's encrypted ;) 

Bart

**Comment by BartMommens** [comment]
@masterix21 , do you manage your landlord database with a separate Laravel project? Or is it all part of one project?

**Comment by masterix21** [comment]
I have only one project, but it doesn't mean that this is the right approach. It would be best if you did what you think it's easy for you

**Comment by BartMommens** [comment]
> I have only one project, but it doesn't mean that this is the right approach. It would be best if you did what you think it's easy for you

Hmmm, i think i have a weird case of multi tenancy... each tenant has it's own database (obviously) but also his own users collection and those users are never in the landlord database. Landlord would be somekind of configuration dashboard...

For example i doubt google admins log in on the client side of their Saas App :) It's kinda mindboggeling sometimes 🤯

**Comment by masterix21** [comment]
Your scenario isn't weird, don't worry. I can suggest using the domain to separate the landlord routes from tenant(s) routes.

**Comment by BartMommens** [comment]
Hey @masterix21,

How did you solve extending the Tenant model and using the custom tenant model in switchTenantTasks?

We are having an issue using a custom tenant model switchTenantTask 

#250 

Sorry to bother you with this 😅
