### ISSUE TITLE
Is there a guide on creating the tenant sign up process?

### ISSUE THREAD

**Issue by eswachsman** [spatie/laravel-multitenancy#195]
Is there a guide anywhere online on creating the tenant sign up process? As far as I understand it, what would be need is:

- A subdomain that is not tenant aware, for users to sign up (get.example.com etc.), but only one route should be available (/register), or am I just overcomplicating it and there is a simpler way?
- When a new tenant signs up: add a tenant to the landlord table, create a new tenant table, run all migrations and redirect to new subdomain
- In my case, I will also call a 3rd party billing provider to register the new tenant

I am mainly stumped with the first part

**Comment by masterix21** [comment]
I don't know if already exists a guide, but the steps are easy:
- create a domain in the same way you could create a user (through a form)
- execute your database migrations from a queue job
- send a welcome email to the fresh owner :)
- so, any other step 

What else?
