### ISSUE TITLE
TenantFinder logic not activated in tests?

### ISSUE THREAD

**Issue by ndeblauw** [spatie/laravel-multitenancy#196]
In my own TenantFinder logic, I'm writing the tenant id in the session. You can easily imagine this from the existing DomainTenantFinder:
```php
    public function findForRequest(Request $request):?Tenant
    {
        $host = $request->getHost();
        $tenant = $this->getTenantModel()::whereDomain($host)->first();
        session()->put('tenant_id', $tenant->id);
        return $tenant;
    }
```
When checking things in the browser (laravel debugbar), all goes well.
![image](https://user-images.githubusercontent.com/4344869/108097749-d8c85880-7082-11eb-958d-fbb51c688f2b.png)

However, when running a simple test (like below, for simplicity I hardcoded the values), the session variable is not set
```php
    /** @test */
    public function check_for_cookie()
    {
        $response = $this->get('http://boszicht.test');
        $response->assertStatus(200);
        $response->assertSessionHas('tenant_id', 2);
    }
```
which results in a failing test
```
Failed asserting that null matches expected 2.
Expected :2
Actual   :null
```
Am I overlooking something? Should I include something to be able to test my own TenantFinder functionlity? Or should I test it differently?

**Comment by masterix21** [comment]
Hi @ndeblauw, using `$this->get(...)`, you won't crawl the tenant URL.

Replace your test like so:
```php
    /** @test */
    public function check_for_cookie()
    {
        URL::forceRootUrl('http://boszicht.test')
        $response = $this->get('/');
        $response->assertStatus(200);
        $response->assertSessionHas('tenant_id', 2);
    }
```

Is it solved?

Thanks

**Comment by ndeblauw** [comment]
Hi @masterix21 , thanks for your suggestion. However, **problem is not solved**, as this results in exactly the same error as my original test (I used the `Illuminate\Support\Facades\URL` for `URL`).

**Comment by masterix21** [comment]
What happens using like so?
```php
    public function check_for_cookie()
    {
        URL::forceRootUrl('http://boszicht.test')
        $response = $this->get('http://boszicht.test/'); // change it
        $response->assertStatus(200);
        $response->assertSessionHas('tenant_id', 2);
    }
```

If it doesn't work, please verify if the `$response` content output is the page you're looking for.

**Comment by ndeblauw** [comment]
The `$response` is for the correct url (both in my original implementation and in both your implementations). How do I know for certain? I added extra information in the view and check for this info as well.

```php
$response->assertStatus(200);
$response->assertSee('Url: http://boszicht.test'); //new
$response->assertSee('Tennant id: 2'); //new
```
The first two assertions pass without a problem, the third one fails.

In my blade template file, I added the following info:
```blade
Url: {{ Url()->current() }}<br/>
@if(\App\Models\Tenant::checkCurrent() )
  Tennant id: {{app('currentTenant')->id }}<br/>
  Tennant details: {{app('currentTenant') }}
@else
  Landlord
@endif
```
This works well, as can be seen in the screenshot below, where I use the browser to visit the http://boszicht.test url
![image](https://user-images.githubusercontent.com/4344869/108192912-1f669300-7115-11eb-8f9e-87d2fe5c0a4a.png)

So, what else can I try, to trigger the TenantFinder logic in tests?

**Comment by masterix21** [comment]
Is your code in a public repo? Can I test it?

**Comment by ndeblauw** [comment]
I've made a public repo that isolates the issue: https://github.com/ndeblauw/lernejo-test

**Comment by ndeblauw** [comment]
Hi Luca, thanks for taking a further look. If you need extra info/clarifications, don't hesitate to ask!

**Comment by masterix21** [comment]
@ndeblauw the problem seems to be Laravel test logic itself because using `$this->get` the test executes a fake request always on the landlord domain (lernejo.test).

Try with these replaces:
```php
$client = Http::get($url); // was: $response = $this->get($url);

$this->assertEquals($status, $client->status()); // was: $response->assertStatus($status); 
$this->assertStringContainsString('Url: '. $url); // was: $response->assertSeeText('Url: '.$url);
```

I don't know if exists a better solution, but it works.

**Comment by ndeblauw** [comment]
Hi @masterix21,

Thanks for looking into this. 

Unfortunately, your solution doesn't work on my local development machine. Every Http:get() request for another domain than the main one (lernejo.test) fails and leads to a 404. Thus, no matter what my test configuration or even local setup is, all calls to the subdomains (gazelle.lernejo.test) and domains (gazelle.test) in the test lead to a 404.

And what makes it even more annoying: running my (original) tests on a different setup, where a simple multitenancy detection is used, does result in all green for the tests. What is that other setup?
- basically just a middleware that is always applied (=added to the 'web' group) --> you can find code it below
- it implements the same logic as in my `DomainAndSubdomainTenantFinder ` method
- but sets a session variable (the Kevin McKee approach), instead of returning a tenant
- that session variable is used in the rest of the app (and in the test) to return the selected tenant --> you can find test below

I know, it's simpler and less powerful. But it proves that the tests are working for both the subdomains and domains. Which is not the case for the `laravel-multitenancy` package. I did some further source diving, but could not find what is causing the reported issue. Sorry not being able to help you further.

The middleware
```
<?php

namespace App\Http\Middleware;

use App\Models\Tenant;
use Closure;
use Illuminate\Http\Request;

class IdentifyTenant
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle(Request $request, Closure $next)
    {
        if (! session()->has('tenant_id')) {
            $host = $request->getHost();
            $pos = strpos($host, env('LANDLORD_DOMAIN'));

            // Landlord site
            if (substr($host, 0, 12) === env('LANDLORD_DOMAIN')) {
                ray("Detected LANDLORD for <{$host}>")->color('green');

                return $next($request);
            }

            // Domain
            if ($pos === false) {
                $tenant = Tenant::where('domain', '=', $host)->sole();
                session()->put('tenant_id', $tenant->id);
                ray("Detected TENANT, using DOMAIN - for <$host>: {$tenant->name}")->color('purple');
            }

            // Subdomain
            if (is_numeric($pos)) {
                $tenant = Tenant::where('subdomain', '=', substr($host, 0, $pos - 1))->first();

                if ($tenant === null) {
                    ray("ERROR - subdomain <{$host}> does not exist")->color('red');
                    abort(500, 'Tenant not found');
                }

                if ($tenant->use_domain) {
                    return redirect("http://{$tenant->domain}");
                }

                session()->put('tenant_id', $tenant->id);
                ray("Detected TENANT, using SUBDOMAIN - for <$host>: {$tenant->name}")->color('blue');
            }
        }

        return $next($request);
    }
}
```

The test (as you can see, it's largely identical to the original test)
```
<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class DomainTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp();

        \App\Models\Tenant::create([
            'name' => 'De Gazelle',
            'subdomain' => 'gazelle',
            'domain' => 'gazelle.test',
        ]);

        \App\Models\Tenant::create([
            'name' => 'Het Boszicht',
            'subdomain' => 'boszicht',
            'domain' => 'boszicht.test',
            'use_domain' => true,
        ]);
    }

    public function siteDataProvider()
    {
        return [
            1 => ['url' => 'http://lernejo.test', 'status' => 200, 'redirect' => null, 'tenant_id' => null],
            2 => ['url' => 'http://gazelle.test', 'status' => 200, 'redirect' => null, 'tenant_id' => 1],
            3 => ['url' => 'http://boszicht.test', 'status' => 200, 'redirect' => null, 'tenant_id' => 2],
            4 => ['url' => 'http://gazelle.lernejo.test', 'status' => 200, 'redirect' => null, 'tenant_id' => 1],
            5 => ['url' => 'http://boszicht.lernejo.test', 'status' => 302, 'redirect' => 'http://boszicht.test', 'tenant_id' => 2],
            6 => ['url' => 'http://toverbol.lernejo.test', 'status' => 500, 'redirect' => null, 'tenant_id' => null],
        ];
    }

    /** @test @dataProvider siteDataProvider */
    public function check_if_domains_can_be_reached($url, $status, $redirect, $tenant_id)
    {
        $response = $this->get($url);
        $response->assertStatus($status);

        // Happy paths
        if ($status == 200 && $tenant_id !== null) {
            $response->assertSessionHas('tenant_id', $tenant_id);
        }

        // Happy path With a redirect
        if ($status == 302) {
            $response->assertRedirect($redirect);
            $response->assertSessionMissing('tenant_id');

            $this->followingRedirects();
            $response = $this->get($url);
            $response->assertSessionHas('tenant_id', $tenant_id);
        }
    }
}
```

**Comment by masterix21** [comment]
I have used MacOS with Valet installed: with Valet, you can create the alias domains. Works.

I'm sorry for the stupid question, but are you sure that your aliases are online? 

I'm closing the issue because it isn't related to a package bug, but feel free to continue to talk about it. Thanks.

**Comment by rabrowne85** [comment]
@masterix21/@ndeblauw I've been following this issue as I've been struggling with a similar/related/same(?) issue and I've tried the various suggestions made thus far, but to no avail.

I have just been able to get my set up to work after some serious digging around in the code. This is what I've just done to get my setup working:

1. Remove `APP_URL` entries from `.env.testing` and `phpunit.xml`
2. Add `LANDLORD_DOMAIN` entry to `.env.testing` and leave this as just the final part of the domain i.e. landlord.test
3. In the `TestCase.php::setUp()` function change to the following:

```php
    protected function setUp(): void
    {
        $_ENV['APP_URL'] = 'https://www.'.env('LANDLORD_DOMAIN');
        parent::setUp();

        $this->setupTenantDatabaseTransactions();

        $this->tenant1 = Tenant::whereSubdomain('t1')->first();
        $this->tenant2 = Tenant::whereSubdomain('t2')->first();

        Event::listen(MadeTenantCurrentEvent::class, function () {
            Config::set('app.url', $this->getUrl());
            URL::forceRootUrl($this->getUrl());
            $_ENV['APP_URL'] = $this->getUrl();
            $this->refreshApplication();
        });
        Event::listen(ForgotCurrentTenantEvent::class, function () {
            Config::set('app.url', $this->getUrl());
            URL::forceRootUrl($this->getUrl());
            $_ENV['APP_URL'] = $this->getUrl();
            $this->refreshApplication();
        });
    }
```
4. Update your test to do something like the following (n.b. I'm using PEST but this should be easily translated):
```php
<?php

beforeEach(function () {
    $this->tenant1->makeCurrent();
});

it('has login page', function () {
    $this->get('/login')->assertStatus(200);
});

```

From what I can tell the key is to update the environment variable on the fly and then refresh the application every time the tenancy changes or reverts to the landlord to ensure that the request that is sent [here](https://github.com/spatie/laravel-multitenancy/blob/62a67c9abfa1ae1f17f106b6aebb1f5c0cbe5670/src/MultitenancyServiceProvider.php#L60) uses the configured APP_URL rather than reverting to the value set in the `.env.testing` and/or `phpunit.xml` files.

As this is "hot off the press" it's a bit "rough and ready", and improvements should be possible, but hopefully this will help someone else who's struggling with a similar issue. I'd also be interested if this helps you @ndeblauw.

For reference I'm running valet on macos and I have ensured that my landlord and subdomains are all activated and working and this is my `SubdomainTenantFinder.php`:

```php
<?php

namespace App\TenantFinder;

use Illuminate\Http\Request;
use Spatie\Multitenancy\Models\Concerns\UsesTenantModel;
use Spatie\Multitenancy\Models\Tenant;
use Spatie\Multitenancy\TenantFinder\TenantFinder;

class SubdomainTenantFinder extends TenantFinder
{
    use UsesTenantModel;

    /**
     * Find the tenant by subdomain.
     *
     * @param Request $request Request
     *
     * @return ?Tenant The tenant to use
     */
    public function findForRequest(Request $request): ?Tenant
    {
        $host = $request->getHost();

        list($subDomain) = explode('.', $host, 2);

        if (false === in_array($subDomain, ['www', 'admin'])) {

            return $this->getTenantModel()::whereSubdomain($subDomain)->first();
        }

        return null;
    }
}
