### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by kamilkozak** [spatie/laravel-multitenancy#199]
What about the documentation? Why is the link [https://spatie.be/docs/laravel-multitenancy](https://spatie.be/docs/laravel-multitenancy) not working?

**Comment by hiddebraun-ma** [comment]
Docs are back online

**Comment by masterix21** [comment]
Thanks for the issue

**Comment by freekmurze** [comment]
Sorry for the inconvenience, we experienced a small hickup on our server
