### ISSUE TITLE
Slugs not working in route

### ISSUE THREAD

**Issue by virgiltu** [spatie/laravel-multitenancy#200]
Is this by design? I cant return the variable in the url.

This will return {tenant}  and will not return $name  . Form what I know it should return $name not {tenant}

![image](https://user-images.githubusercontent.com/7761519/108469943-04dc0900-723e-11eb-90a5-244204c79fb0.png)

This will return $name

![image](https://user-images.githubusercontent.com/7761519/108470014-20dfaa80-723e-11eb-8fda-e35f37b704bb.png)

**Comment by masterix21** [comment]
Hi @virgiltu, sorry but it seems a package unrelated Laravel issue.

I'm closing the issue but keep us updated. Thanks.

**Comment by virgiltu** [comment]
This is definitely a tenancy issue. Routes with slugs do not work in the tenant route. They work fine outside. So you cant call app('currentTenant');  outside the tenant route.

**Comment by masterix21** [comment]
If you think it's related to the package, we are happy to merge the PR that will fix the issue.

Thanks for your support.

**Comment by meetshah8530** [comment]
yes facing same issue 
please help

**Comment by masterix21** [comment]
https://github.com/spatie/laravel-multitenancy/issues/233
