### ISSUE TITLE
No TenantAware Command Concern when Installing on Windows

### ISSUE THREAD

**Issue by cverster** [spatie/laravel-multitenancy#201]
When I installed this package using composer on windows, I checked and there is no TenantAware.php file under /vendor/spatie/laravel-multitenancy/Commands/Concerns. There actually isn't even a Concerns folder.

I tried reinstalling, but not luck.

What I'm trying to achieve is to make my artisan commands tenant aware using the TenantAware trait, as they are looking at my landlord database instead of my tenant database when I run them.

**Comment by masterix21** [comment]
Sorry, I have no windows installations. I hope that someone with Windows will help you.

**Comment by ndeblauw** [comment]
Hi @cverster 

I've checked in my installation, and the file is present. See screenshot below.

It's a simple assumption, but could you somehow be confused between
- the namespace `Spatie\Multitenancy\Commands\Concerns` 
- the actual path `vendor/spatie/laravel-multitenancy/src/Commands/Concerns/TenantAware.php`
(and thus, forgot to check inside the `src` directory?)

![image](https://user-images.githubusercontent.com/4344869/109294622-b7f3c600-782d-11eb-8d22-7fb5b19ec2de.png)

**Comment by masterix21** [comment]
The issue seems to be unrelated to the package. I'm closing here, but feel free to continue to talk about it.

Thanks.
