### ISSUE TITLE
Using Multitenancy with oauth2-client

### ISSUE THREAD

**Issue by rachael21coates** [spatie/laravel-multitenancy#203]
I have set up a project using this package and it works fine. I have also set up a project which allows me to use SSO to log in with Azure active directory. I am trying to get both working together. I'm using valet too in my test environment. After authenticating with the microsoft server I have a callback defined in the .env file like this OAUTH_REDIRECT_URI=http://localhost:8000/callback 
How can I specify the callback URL based on the currentTenant in the .Env file? or have you any suggestions on how I can get over this barrier. 
Thanks

**Comment by masterix21** [comment]
Hi @rachael21coates.

You can't use the `.env` file for runtime changing parameters. I suggest using a config file in `config/your-config.php`, so with a custom task, you could change the parameter dynamically.

I'm closing the issue because it isn't related to a package bug, but feel free to continue to talk here.

Thanks

**Comment by rachael21coates** [comment]
Thanks for your reply. I figured out a solution and thought I should answer here in case anyone else is looking for it. 
I am using Laravel UI with auth and oauth2-client so I was able to override the callback URL in the .env file by getting the current tenant in the loginController and setting the callback URL in that file to be tenant specific before the request is made. 
`// Initialize the OAuth client
      $tenant = Tenant::current();
      $URL='https://'.$tenant->name.'.test/callback';
      $oauthClient = new \League\OAuth2\Client\Provider\GenericProvider([
        'clientId'                => config('azure.appId'),
        'clientSecret'            => config('azure.appSecret'),
        'redirectUri'             => $URL,
       ......`

**Comment by masterix21** [comment]
Thanks for your share. Happy coding :)
