### ISSUE TITLE
How to setup a welcome page on primary domain

### ISSUE THREAD

**Issue by kasperhartwich** [spatie/laravel-multitenancy#208]
Hi. I would be nice if the documentation covered how to setup a welcome page and maybe a signup on the primary domain.
At default it just throw a "The request expected a current tenant but none was set." exception.

**Comment by michaeldaly** [comment]
Hi @kasperhartwich 

I am currently working through the same type of set up, I can provide an example of what I am doing, perhaps you can adapt it to suit your specific needs.

To enable routing on the primary domain, I am using a route group as the fallback underneath my Tenant routes, like this:

```
Route::domain('{tenant}.' . config('app.url'))->middleware('tenant')->group(function() {
    Route::get('/', function () {
        ...
    });

    // Your tenant specific routes
});

Route::group(['domain' => config('app.url')], function () {
    Route::get('/', function () {
        return view('admin.welcome');
    });

   // Your primary domain application routes, including registration and any other admin functionality you would like to expose to your users
});
```

In order to achieve this, you need to place your tenant middleware as a new group within the `app/Http/Kernel.php`, like so:

```
 /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],

        'tenant' => [
            \Spatie\Multitenancy\Http\Middleware\NeedsTenant::class,
            \Spatie\Multitenancy\Http\Middleware\EnsureValidTenantSession::class,
        ],

        'api' => [
            'throttle:api',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];
```

This allows you to add the `tenant` middleware to any route you choose to against the tenant, and it won't automatically apply to every domain as part of the `web` group.

**New Tenant Database**
During registration, I am creating a new tenant like this:

_CustomTenant is a simple model I have created which extends Spatie's MultiTenant Tenant model_

To get started, this can be placed in an action class and called by the controller during user registration:

```
 $tenant = CustomTenant::create([
      'name' => $tenantName,
      'domain' => $tenantName . config('app.url'),
      'database' => Str::limit($tenantName, 50) . '-' . Carbon::now()->timestamp, // I am temporarily giving the database a name to satisfy the table definition (can't be null), but the real name is set during the $tenant->createDatabase() call. I will refactor this later.
  ]);

  $tenant->createDatabase();
```

**CustomTenant.php**
```
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Spatie\Multitenancy\Models\Tenant;

class CustomTenant extends Tenant
{
    use HasFactory;

    protected $table = 'tenants';

    public function createDatabase()
    {
        $this->database = 'tenant-' . $this->id . '-' . Carbon::now()->timestamp;
        $this->save();

        $db = DB::connection();

        $charset = $db->getConfig('charset');
        $collation = $db->getConfig('collation');

        $db->statement("CREATE DATABASE `$this->database` CHARACTER SET `$charset`  COLLATE `$collation`");

        Artisan::call('tenants:artisan', [
            'artisanCommand' => 'migrate --database=tenant',
            '--tenant' => $this->id,
        ]);
    }
}
```

Let me know if any of this helps?

**Comment by masterix21** [comment]
Feel free to create a PR with the doc page.

I'm closing here because isn't a package issue, but feel free to continue the discussion. 

Thanks.

**Comment by Kmap-Holdings** [comment]
@michaeldaly do you ever get the following error with your setup? 

![image](https://user-images.githubusercontent.com/80934965/158334106-4e87d8b3-cb72-4482-982e-3d999ce8b4d0.png)

my route looks as follows:

![image](https://user-images.githubusercontent.com/80934965/158334580-4a73ef07-08f6-4b31-87d1-96388277a9bf.png)

**Comment by Kmap-Holdings** [comment]
tenant route list:

![image](https://user-images.githubusercontent.com/80934965/158335001-91e59a4b-428f-45ed-9b9c-8cf41af0efa8.png)

I have everything else working and can create tenants and so forth, just stuck here. I'm sure its a user issue.

**Comment by Kmap-Holdings** [comment]
The following approach works though

![image](https://user-images.githubusercontent.com/80934965/158337963-9a7af166-135b-44ec-8355-c071607bd7b1.png)

**Comment by Kmap-Holdings** [comment]
so my code looks like this incase anyone gets stuck here in the future, which I doubt.

![image](https://user-images.githubusercontent.com/80934965/158338144-6712ce62-0b12-43a9-b9a0-3d79d8a6a2b1.png)

**Comment by Kmap-Holdings** [comment]
I would also advise that you place your landlord routes first. I tried to place them after tenants. Gave me an issue after I restarted and cleared the cache. Maybe it's just my machine, but all works well now.
