### ISSUE TITLE
Unable to locate publishable resources.

### ISSUE THREAD

**Issue by chriship** [spatie/laravel-multitenancy#210]
Hi,

I seem to be getting the error 'Unable to locate publishable resources.' when I run the command to publish the config file. This happens with a fresh Laravel 8 install. To replicate:

```
composer create-project laravel/laravel test.multi.tenancy
cd test.multi.tenancy
composer require "spatie/laravel-multitenancy"
php artisan vendor:publish --provider="Spatie\Multitenancy\MultitenancyServiceProvider" --tag="config"
```

EDIT: running `php artisan vendor:publish --provider` and then selecting the correct number does work.

**Comment by masterix21** [comment]
Hi @chriship, please try with:
```bash
php artisan vendor:publish --provider="Spatie\Multitenancy\MultitenancyServiceProvider" --tag="multitenancy-config"
```
