### ISSUE TITLE
Landlord as 'super admin'

### ISSUE THREAD

**Issue by chriship** [spatie/laravel-multitenancy#212]
I'd like to use the landlord database to hold super admin users who have the ability to create new tenants once logged in. Has anyone managed to do this?

So if I log on via localhost:8000 I use the landlord database
If i log on via {tenant}.localhost:8000 I use the corresponding tenant database

When I try to log in without a subdomain, I get a `No database selected` error from mysql. So somehow I need to select the Landlord database when there is no subdomain, but I'm not sure how.

**Comment by masterix21** [comment]
Are you using `DB_CONNECTION=landlord` in your .env file?

I'm closing the issue because isn't related to the package, but feel free to continue the talk.

**Comment by chriship** [comment]
Hi @masterix21.

If I use `DB_CONNECTION=landlord` in the .env file I can log in using localhost through the landlord database. However, the tenant database is then not used when I try to log in via `{tenant}.localhost` (it still tried to use the landlord database).

Should I be switching which database is chosen in the AppServiceProvider?

**Comment by chriship** [comment]
I guess one way I could achieve it would be to have my super-admin within the tenant database like so:

name: superadmin
domain: localhost
database: landlord

But that feels a little odd to have the 'landlord' inside the 'tenant' table.

**Comment by masterix21** [comment]
Database switch should be done by a task, [like so](https://spatie.be/docs/laravel-multitenancy/v2/using-tasks-to-prepare-the-environment/creating-your-own-task#breadcrumb).
