### ISSUE TITLE
No tenant detected

### ISSUE THREAD

**Issue by Ammar09** [spatie/laravel-multitenancy#213]
Hello everyone,
I would like to share my issue.
I have followed all instructions on the Docs page + followed some tutorials on Youtube
But still got failure result as shown below:

**The request expected a current tenant but none was set.**

for your info I am using version 1
I appreciate your cooperation

**Comment by masterix21** [comment]
Seems to be a problem related to your tasks. Are you using the default `SwitchTenantDatabaseTask`?

**Comment by Ammar09** [comment]
yes, my brother, I am using the default **SwitchTenantDatabaseTask**

Now the tenants' route is working, the landlord route still show the response:
**The request expected a current tenant but none was set.**

**Comment by Ammar09** [comment]
everything is settled now >> thank you so much
