### ISSUE TITLE
The migration is not working

### ISSUE THREAD

**Issue by mprince2k18** [spatie/laravel-multitenancy#214]
I tried to migrate the landlord migrations. It not migrating./
![image](https://user-images.githubusercontent.com/43857625/113038957-efe98280-91b8-11eb-9678-810d9bb7d7b5.png)

**Comment by malblack** [comment]
php artisan vendor:publish --provider="Spatie\Multitenancy\MultitenancyServiceProvider" --tag="multitenancy-migrations"
