### ISSUE TITLE
vendor:publish ERROR: Unable to locate publishable resources.

### ISSUE THREAD

**Issue by santiagazo** [spatie/laravel-multitenancy#215]
Laravel 8.0
PHP 8.0
Added package via composer - no errors
tried to publish provider via:
`php artisan vendor:publish --provider="Spatie\Multitenancy\MultitenancyServiceProvider" --tag="config"` and
`php artisan vendor:publish --provider="Spatie\Multitenancy\MultitenancyServiceProvider" --tag="migrations"`

returned error: `Unable to locate publishable resources.`

I ran a composer update and then checked the files in vendor and found the MultitenancyServiceProvider located in src. Nonetheless, after running it again the same error was returned. 

How can I fix this?

**Comment by santiagazo** [comment]
I manually did it by copying the files to database>migrations>landlord>create_landlord_tenants_table.php and config>multitenancy.php from the vendor folder - gonna try and run with this, please let me know if there's anything else I'm missing that needed to get done when these were copied (aside from entering my own config on them).

**Comment by malblack** [comment]
I think Spatie need to update the docs! you can run these two commands
php artisan vendor:publish --provider="Spatie\Multitenancy\MultitenancyServiceProvider" --tag="multitenancy-migrations"
php artisan vendor:publish --provider="Spatie\Multitenancy\MultitenancyServiceProvider" --tag="multitenancy-config"

**Comment by masterix21** [comment]
I can confirm what @malblack said. I'm closing the issue.

**Comment by santiagazo** [comment]
Thanks all.

**Comment by masterix21** [comment]
@santiagazo thanks for your PRs.

**Comment by santiagazo** [comment]
Welcome. Glad I could contribute to a Spatie project! I've never done a PR on an open-source project before, that was fun. Thanks for helping me make it happen.
