### ISSUE TITLE
Using Multitenancy with laravel-permission

### ISSUE THREAD

**Issue by sys-auditing** [spatie/laravel-multitenancy#222]
Hi,
i have a laravel project with permissions management based on top of laravel-permission.
I would like to convert this project to multitenancy (with multi databases approch) and figure out how to use it with laravel-permission package.

Thank you

**Comment by masterix21** [comment]
I'm not a `spatie/laravel-permission` guru, but I'm using the package in the projects without any pain. If you already have configured your tenant cache isolation, there are no other special things. 

I repeat isn't necessary, but the paranoic people might improve the code tasks like so:
```php
class SwitchPackagesTask implements SwitchTenantTask
{
    protected ?string $originalSpatiePermissionCacheKey;

    public function makeCurrent(Tenant $tenant): void
    {
        $this->originalSpatiePermissionCacheKey = PermissionRegistrar::$cacheKey;
        $this->setup($tenant);
    }

    private function setup(Tenant $tenant)
    {
        PermissionRegistrar::$cacheKey = 'spatie.permission.cache.tenant.' . Str::slug($tenant->host);
        app()->make(\Spatie\Permission\PermissionRegistrar::class)->forgetCachedPermissions();
    }

    public function forgetCurrent(): void
    {
        PermissionRegistrar::$cacheKey = $this->originalSpatiePermissionCacheKey;
        app()->make(\Spatie\Permission\PermissionRegistrar::class)->forgetCachedPermissions();
    }
}
``` 

I hope it will help you. Give me feedback to share with the community, please. 

Thanks.

**Comment by sys-auditing** [comment]
Thank you @masterix21, i'll test it.
Do you think if i install the multitenancy on top of my existing project that will not damage the project?

**Comment by masterix21** [comment]
If it's your local environment, there are no problems: you can discard the changes using git.

Don't risk what you can't lose: it's a financial best practice.

**Comment by sys-auditing** [comment]
Hi, can you plz tell me how can i isolate the cache?

**Comment by sys-auditing** [comment]
How can i use isolation cache, i'm using file as CACHE_DRIVER?
