### ISSUE TITLE
Using responsecache package with multitenancy

### ISSUE THREAD

**Issue by milosevicn** [spatie/laravel-multitenancy#227]
Hello,

I am using `laravel-multitenancy` package. On my project, I've got code for managing the data for models on a `landlord` side and all the other code is on `tenant`. 
Now, I want to cache all the `get` requests sent on `tenant` and would like to use `laravel-responsecache` for this purpose. Another request is to clear the cache on model `created/updated/deleted` (there is an example of this behaviour inside `laravel-responsecache` documentation, coded as a `trait` called `ClearsResponseCache`).
The problem is that I would need to create this trait on a `landlord` side to trigger `ResponseCache::clear()` on a `tenant` side. 
Would this be possible and do I need to install `laravel-responsecache` on both `landlord` and `tenant`?

Here is my try to achieve this, but it's unsuccessful since `ResponseCache` is undefined on `landlord` cause I haven't installed the package there:

```php
namespace App\Traits;

use Spatie\Multitenancy\Models\Tenant;

trait ClearsResponseCache
{
    public static function bootClearsResponseCache()
    {
        self::created(function () {
            Tenant::current()->execute(function () {
                dispatch(ResponseCache::clear());
            });
        });

        self::updated(function () {
            Tenant::current()->execute(function () {
                dispatch(ResponseCache::clear());
            });
        });

        self::deleted(function () {
            Tenant::current()->execute(function () {
                dispatch(ResponseCache::clear());
            });
        });
    }
}
```

**Comment by masterix21** [comment]
I'm not using the `spatie/laravel-responsecache` package, but seeing their first documentation page on GitHub seems that you could solve the problem using a custom `CacheProfile` or the tags.

@freekmurze, can you confirm it? Thanks.

**Comment by freekmurze** [comment]
That code looks good 👍

**Comment by milosevicn** [comment]
> I'm not using the `spatie/laravel-responsecache` package, but seeing their first documentation page on GitHub seems that you could solve the problem using a custom `CacheProfile` or the tags.
> 
> @freekmurze, can you confirm it? Thanks.

Okay, will try, thanks
