### ISSUE TITLE
use separate filesystems per tenant?

### ISSUE THREAD

**Issue by scramatte** [spatie/laravel-multitenancy#228]
Hello,

Can you give me some clue how can I  use separate filesystems per tenant?
I need to store files, images and views per tenant 

Thank you for the help

Regards

**Comment by masterix21** [comment]
Add a disk in the config filesystem, named for example "tenants", and create a Switch Task to change the `filesystem.disks.tenants` config array.

I'm closing the issue because isn't related to a package bug, but feel free to continue the discussion. Thanks.

**Comment by lvillacin** [comment]
Linking here a previous post that might be helpful https://github.com/spatie/laravel-multitenancy/issues/29#issuecomment-636491631
