### ISSUE TITLE
@can blade directive issue 

### ISSUE THREAD

**Issue by sys-auditing** [spatie/laravel-multitenancy#229]
Hi,
i'm using @can blade directive to check user permissions, but it's seems not working.

when calling `` auth()->user()->roles `` i get result with connection `` tenant``, and for permission ``Role::findByName(auth()->user()->getRoleNames()->first())->permissions`` i got ``mysql`` as connection.

Do you have any idea?

Thanks

**Comment by sys-auditing** [comment]
i fixed the issue by adding ``UsesTenantConnection`` to Spatie Permission model, but is't a best way to do (make a change on vendor files) ?

**Comment by sys-auditing** [comment]
ok thank you @masterix21, do you have code example ?

**Comment by masterix21** [comment]
```php
config('database.default', 'tenant')
```

but you should create your own `DatabaseSwitchTask`.
