### ISSUE TITLE
Registration flow question

### ISSUE THREAD

**Issue by dambridge** [spatie/laravel-multitenancy#23]
Looks great, and so far so good. Cheers!

I've got an initial setup in which a user registers, a tenant is created and its db created. Wondering your thoughts on best approach to complete the process.

I'm thinking of dispatching a job for seeding the tenant database (using Artisan::call) like so: 
```
Artisan::call('tenants:artisan migrate --seed', [
            '--tenant' => [$this->tenant->id],
        ]);
```

and inserting the User. I understand I can make jobs tenant-aware, but my auth routes are outside the tenant subdomain. Can I still use makeCurrent() here somehow? Or do I need to manually pass the new Tenant Id directly to the job at this stage?

**Comment by dambridge** [comment]
Hmm, I think I overlooked the simplicity of $tenant->makeCurrent().

**Comment by dambridge** [comment]
Update. This seems to run properly:
`Artisan::call('tenants:artisan "migrate --seed" --tenant=' . $this->tenant->id);`

However, I now get this:
```
Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[HY000] [1049] Unknown database 'a0eb5d78-9c85-48ae-8d21-4981a4d93643' in /home/vagrant/code/sites/troovy/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31
```

I have a tenant prefix of 'tenant_' on tenant databases. Does the Artisan command just look at $tenant->database perhaps, without adding prefix? Checking...

**Comment by dambridge** [comment]
Ultimately, I think I tracked it down to a missing config setting. Didn't have the default connection set to 'tenant'.

**Comment by martincarvalho** [comment]
Hey @dambridge , how did you fix the `command does not exist` issue?

My artisan call is pretty much exactly like yours:
`Artisan::call('tenants:artisan "migrate --seed" --tenant=' . $this->id);`

But I'm still getting:
`Symfony\Component\Console\Exception\CommandNotFoundException
The command "tenants:artisan" does not exist.`

This is how my `createDatabase()` method looks like:

```
    public function createDatabase()
    {
        DB::statement('CREATE DATABASE `'.$this->database.'`');
        Artisan::call('tenants:artisan "migrate --seed" --tenant=' . $this->id);
    }
```

**Comment by dambridge** [comment]
Hi @martincarvalho 

Still working through this. This call works perfectly when I have it in a *job* (I have made all jobs tenant aware by default in the config).
`Artisan::call('tenants:artisan "migrate --seed" --tenant=' . $this->tenant->id);`

However... it fails when I run it in a controller directly with the same error! Very strange, still looking at it.

**Comment by dambridge** [comment]
If it works in my job, then something about environment/context must be at play is my thinking. Not sure if this is relevant, but found this in the MultiTenancy service provider:
```
if ($this->app->runningInConsole()) {
            $this
                ->registerPublishables()
                ->bootCommands();
        }
```

```
protected function bootCommands(): self
    {
        $this->commands([
            TenantsArtisanCommand::class,
        ]);

        return $this;
    }
```

Maybe this means the command is only available from within console? And because jobs run 'out of process' it works?

**Comment by dambridge** [comment]
This is greasy, but it works in controller:
`exec('cd ' . base_path() . ' && php artisan tenants:artisan "migrate --seed" --tenant=' . $tenant->id);`

**Comment by freekmurze** [comment]
In the vendor of your app, move that `bootCommands` outside of `runningInConsole` and see if just using `Artisan::call`. work for the command. If it does, I'd accept a PR that makes this change in the package 👍

**Comment by martincarvalho** [comment]
After moving the `bootCommands` outside of `runningInConsole` I got the `Artisan ::call` to work IF in a controller.
It does not work if called inside the `Tenant` model.
If possible I'd like to create the database AND run the migration inside the `createDatabase()` method on my `Tenant` model, as suggested in the documentation.
Is this possible?

**Comment by 4ice** [comment]
In case anyone else experiences this issue in the future, this is how your should write the Artisan command:

```
        Artisan::call('tenants:artisan', [
            'artisanCommand' => 'migrate --database=' . $this->tenant->db_connection,
            '--tenant' => [$this->tenant->id],
        ]);
```
