### ISSUE TITLE
loginAs on dusk tests

### ISSUE THREAD

**Issue by p4rz1val** [spatie/laravel-multitenancy#230]
Im trying to login in my dusk tests however i keep getting the `Invalid catalog name: 1046 No database selected` error, i have no problems running HTTP tests and actingAs() a user it's only on dusk.

Here's my test:

```
public function test_user_can_see_dashboard_page()
{
    $this->tenant = Tenant::find(1);
    $this->tenant->makeCurrent();

    // Database connection is fine here we get the current tenant database
    //
    // dd(DB::connection()->getDatabaseName());
    // returns "tenant_hahn_inc7256"

    $this->browse(function (Browser $browser) {
        $user = User::find(1);

        // dd($user);
        //
        // output:
        // #attributes: array:14 [
        //    "id" => 1
        //    "name" => "Super"
        //    "email" => "admin@example.com"
        //    ...
        // ]

        $browser->loginAs($user->id)
            ->visitRoute('home')
            ->assertSee('Hi');
    });
}
``` 

and my .env: 
```
DB_CONNECTION=tenant

LANDLORD_DB_HOST=127.0.0.1
LANDLORD_DB_PORT=3306
LANDLORD_DB_DATABASE=myrooms
LANDLORD_DB_USERNAME=root
LANDLORD_DB_PASSWORD=

TENANT_DB_HOST=127.0.0.1
TENANT_DB_PORT=3306
TENANT_DB_USERNAME=root
TENANT_DB_PASSWORD=
```

**Comment by p4rz1val** [comment]
More than anything i want to know if there's something special about setting up dusk with laravel-multitenancy or the issue is more on my side, thanks! :partying_face:

**Comment by masterix21** [comment]
@p4rz1val, sorry for the delayed response but I'm so busy these days.

I have successfully simulated a browser call using Laravel Dusk like so:
![image](https://user-images.githubusercontent.com/6555012/116938708-805d2c00-ac6b-11eb-9cf2-7f994b6d92be.png)

**Comment by masterix21** [comment]
I'm closing the issue due to inactivity, but feel free to reply here. Thanks
