### ISSUE TITLE
Laravel Multi Tenancy Query Builder use wrong database

### ISSUE THREAD

**Issue by sys-auditing** [spatie/laravel-multitenancy#231]
I want to do a simple query with query builder.

`` DB:table('users')->select('username')->get(); // i would like use this ``

But use wrong database landlord even i'm using tenant aware. If I use the model it works fine.

`` User::select('username')->get(); ``

How can I solve this problem?

**Comment by masterix21** [comment]
@sys-auditing, using the `DB` Facade you should specify the connection name like so: `DB::connection('tenant')->table('users')->...`.

I'm closing the issue because it is not related to a package bug. Thanks.

**Comment by sys-auditing** [comment]
yes i have just use the same thing, but always the connection was the wrong one, i'm using DB facade inside a Job.

**Comment by masterix21** [comment]
Is the job TenantAware?

**Comment by sys-auditing** [comment]
yes, 

`` // multitenancy.php ``
`` 'queues_are_tenant_aware_by_default' => true,``

**Comment by masterix21** [comment]
`schedule:run` executes scheduled commands, not jobs. The jobs are processed by `queue:work`.

If your command should be TenantAware, use the `TenantAware` trait in your command.

**Comment by sys-auditing** [comment]
Sorry for waisting your time
i have this,
``//Consol\Kernel.php``
`` if (Tenant::current()){
            Tenant::all()->eachCurrent(function(Tenant $tenant) use ($schedule) {
                $schedule->job(new GenerateStats)->everyMinute();
            }); 
        } ``

**Comment by sys-auditing** [comment]
I see, i'm checking the current tenant in order to separate scheduled task from admin panel that use landloard connection and tenant.

So, GenerateStats job used for only tenant connection, and in my crontab i have two lines : 
```shell
* * * * * cd /var/www/html/project/ && /usr/bin/php artisan schedule:run >> /tmp/crontab.Landlordlaravel
* * * * * cd /var/www/html/project/ && /usr/bin/php artisan tenants:artisan schedule:run >> /tmp/crontab.Tenantlaravel 
```

That's why i'm using the condition ``Tenant::current``

**Comment by masterix21** [comment]
`tenants:artisan` already runs your command for each tenant, and using your code, you will run the scheduling for each tenant for how many tenants you have. To understand, if you have 3 tenants, every tenant is used from the `schedule:run` three times.

Finally, are you using the TenantAware interface for your job?

**Comment by sys-auditing** [comment]
yes, ``GenerateStats`` job implements ``TenantAware``
sorry i dont understand your point of view about ``schedule:run`` with tenant case.
