### ISSUE TITLE
route variables problem

### ISSUE THREAD

**Issue by meetshah8530** [spatie/laravel-multitenancy#233]
multi tenancy spatie route slugs problem - 

```php
Route::domain('{tenant}.localhost')->middleware('tenant')->group(function(){
     Route::prefix('owner')->middleware(['auth', 'owner'])->group(function () {
         Route::get('/Entries/edit/{id}',function($id){
               echo $id;
       });
    });		
});		
```

output gives tenant name

**Comment by masterix21** [comment]
@meetshah8530, if you use `{tenant}` as a route parameter, it will be passed inside your grouped routes. To understand better what happen, replace `echo $id` with `print_r(func_get_args());`.

I'm closing here because it isn't related to a package issue. Thanks.
