### ISSUE TITLE
Laravel Maintenance Mode with Spatie’s multi tenancy package

### ISSUE THREAD

**Issue by sys-auditing** [spatie/laravel-multitenancy#237]
Hi, 

i would like to make maintenance mode per tenant, so by calling tenants:artisan command :
```php
php artisan tenants:artisan "down --render="errors::503" --secret='secret'" --tenant=1
```
puts all tenants in maintenance mode.

There"s any idea to figure out this issue?

NB: Using Laravel 8
Thank you

**Comment by masterix21** [comment]
Currently, you can't. Feel free to create a PR to implements the feature. Thank you.
