### ISSUE TITLE
migration issue

### ISSUE THREAD

**Issue by Kobershan** [spatie/laravel-multitenancy#239]
Im using the latest Spatie Multitenancy package with laravel 8 and php 8. I have followed the documentation and when i try to migrate the file in my landlord subfolder of migrations, (which does contain the create landlords tenants table), using php artisan migrate --path=database/migrations/landlord --database=landlord it returns migration table created nothing to migrate, even though i can see the table in the folder which needs to be migrated. ive used the recommended php artisan vendor:publish --provider="Spatie\Multitenancy\MultitenancyServiceProvider" --tag="multitenancy-migrations" to create the table  in the landlords folder. Any idea how i can run the migration for the table within the folder?

**Comment by BartMommens** [comment]
@Kobershan ,

Check #238,
Manual fix is to rename folder and file of the landlord folder.

**Comment by masterix21** [comment]
Duplicated. I'm closing here.
