### ISSUE TITLE
Multitenancy + Activity Log

### ISSUE THREAD

**Issue by dambridge** [spatie/laravel-multitenancy#24]
Can't seem to get the connection working with Activity Log. I've tried both setting `'database_connection' => 'tenant',` in config.activitylog, as well as `config(['activitylog.database_connection' => 'tenant']);` in a tenant middleware. I continue to get this error:

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tenant_d62db5ba-bcaa-498f-a8eb-b8af00b8e119.activity_log' doesn't exist (SQL: select count(*) as aggregate from `activity_log`) 
```

**Comment by freekmurze** [comment]
Could you dump the database config right before that exception is thrown?

**Comment by dambridge** [comment]
@freekmurze Hey there, determined it was because I was not properly authenticated. All good!
