### ISSUE TITLE
SwitchTenantTask makeCurrent function accept custom Tenant model

### ISSUE THREAD

**Issue by iurylippo** [spatie/laravel-multitenancy#250]
It's possible to make the Tenant parameter flexible on implementing this interface? it's forcing to pass a `Spatie\Multitenancy\Models\Tenant`

![image](https://user-images.githubusercontent.com/35785386/120567375-fded9680-c3e7-11eb-88b9-e096c0e02a1e.png)

**Comment by danijelk** [comment]
Why is that bad though?

**Comment by BartMommens** [comment]
> Why is that bad though?

Well it's not "bad" but i think what he's trying to do is creating a new SwitchTask that uses a Custom Tenant model. Currently i'm also figuring out how to do it. Since when you create a custom SwitchTenantTask with your own custom Tenant model he doesn't accept it i think.

**Comment by iurylippo** [comment]
> @danijelk
> 
> > Why is that bad though?
> 
> Well it's not "bad" but i think what he's trying to do is creating a new SwitchTask that uses a Custom Tenant model. Currently i'm also figuring out how to do it. Since when you create a custom SwitchTenantTask with your own custom Tenant model he doesn't accept it i think.
> 
> For example i'm creating a custom tenant model that doesn't have domain or database in the tenants table but in a settings table since i require multiple database connections to different servers.

Yeah, my situation is just like that, I have a custom tenant model with differentes columns that extends the Spatie Tenant class, and will not switch database via domain, so, i have to create a custom task also, when i was creating and implementing this interface: SwitchTenantTask, the IDE itself complained about not passing a Spatie\Multitenancy\Models\Tenant as parameter on makeCurrent function

**Comment by danijelk** [comment]
We run custom Tasks with our own Tenant model with custom attributes, as long as you extend the Spatie Tenant you shouldn't have an issue, feel free to write the issue in detail so all can help.

**Comment by iurylippo** [comment]
> We run custom Tasks with our own Tenant model with custom attributes, as long as you extend the Spatie Tenant you shouldn't have an issue, feel free to write the issue in detail so all can help.

I've alredy extends te Tenant class, illustrative images:

![image](https://user-images.githubusercontent.com/35785386/120651649-63c43780-c455-11eb-8a83-c72d6024bc02.png)
![image](https://user-images.githubusercontent.com/35785386/120651895-a554e280-c455-11eb-9f50-89bab72809b5.png)
![image](https://user-images.githubusercontent.com/35785386/120652038-c0275700-c455-11eb-8f30-72e377d1b422.png)

**Comment by BartMommens** [comment]
Mmmm in my case is almost similar: 

The custom model

CustomTenant.php:

    namespace App\Models;
    
    use Spatie\Multitenancy\Models\Tenant;
    
    class CustomTenant extends Tenant
    {
        protected $table = 'tenants';
    
        public function settings(){
            return $this->hasOne(<img width="1110" alt="Screenshot 2021-06-03 at 15 27 07" src="https://user-images.githubusercontent.com/19632282/120652585-30e36900-c480-11eb-900b-a2ce2f8a44d3.png">,'tenant_id');
        }
    }

config\multitenancy.php:

    return [
       'tenant_model' => App\Models\CustomTenant::class,
    ]

SwitchTenantConfigTask.php

    namespace App\Tasks;
    
    use App\Models\CustomTenant;
    use \Spatie\Multitenancy\Tasks\SwitchTenantTask;
    
    class SwitchTenantConfigTask implements SwitchTenantTask
    {
    
        public function makeCurrent(CustomTenant $tenant): void
        {
            // TODO: Implement makeCurrent() method.
            config([
                'session.domain' => $tenant->settings->domain,
            ]);
        }
    
        public function forgetCurrent(): void
        {
            config([
                'session.domain' => null
            ]);
        }
    }

So the CustomTenant model extends the Tenant model but with an additional function and protected $table = 'tenants'

if i remove them both it works ...

**Comment by BartMommens** [comment]
additional info running v2.1.3 on PHP 8.0.3 dunno if it matters :)

**Comment by danijelk** [comment]
I see, I didn't pay close attention to our task, we actually have
`public function makeCurrent(Spatie\Multitenancy\Models\Tenant $tenant): void`

even with our custom Tenant, this still gives us the correct tenant, but I can see that IDE wise it would be better to have the correct Model here.

Guess you can do a PR with an interface instead of the current Model setup so it's easier to implement.

**Comment by masterix21** [comment]
An interface is a good point of view, but it means creating a major release to avoid breakdown. I will work over it asap if @freekmurze agrees with me.

**Comment by freekmurze** [comment]
I'm thinking I want to leave things as they are. If you extend the default model there should be no problems at all.

To fix IDE autocompletation, add a docblock that helps the IDE to determine that `$tenant` holds an instance of you custom tenant model.

**Comment by BartMommens** [comment]
Extending the Default `Spatie\Multitenancy\Models\Tenant` doesn't seem to be working ... tried several things all result in same error : 

`Symfony\Component\ErrorHandler\Error\FatalError
Declaration of App\Tasks\System\Tenant\SwitchTenantConfigTask::makeCurrent(App\Models\System\Tenant\CustomTenant $tenant): void must be compatible with Spatie\Multitenancy\Tasks\SwitchTenantTask::makeCurrent(Spatie\Multitenancy\Models\Tenant $tenant): void`


Custom tenant model:

```php
namespace App\Models\System\Tenant;

use Spatie\Multitenancy\Models\Tenant as BaseTenantModel;

class CustomTenant extends BaseTenantModel
{
    protected $table = 'tenants';

    public function settings(){
        return $this->hasOne(TenantSettings::class, 'tenant_id');
    }
}
```

config/multitenancy.php


```php
return [
'tenant_model' => \App\Models\System\Tenant\CustomTenant::class,
]

```


customSwitchTenantTask

```php
namespace App\Tasks\System\Tenant;


use App\Models\System\Tenant\TenantSettings;
use Illuminate\Support\Facades\App;
use Spatie\Multitenancy\Tasks\SwitchTenantTask;

use App\Models\System\Tenant\CustomTenant as Tenant;

class SwitchTenantConfigTask implements SwitchTenantTask
{

    public function makeCurrent(Tenant $tenant): void
    {
        //TODO CHANGE CONFIG HERE

    }

    public function forgetCurrent(): void
    {
        //TODO
    }
}
```

Running PHP 8.0.3

**Comment by danijelk** [comment]
> ```
> use App\Models\System\Tenant\CustomTenant as Tenant;
> ```


As mentioned your method makeCurrent needs to be like the original one, so you can't use CustomTenant here

`    public function makeCurrent(Tenant $tenant): void`


Set it to Spatie\Multitenancy\Models\Tenant and you will be fine, it will still be CustomTenant here, so it will work as you expect, as Freek said you can add docblock for IDE autocomplete.

**Comment by BartMommens** [comment]
@danijelk thanks for pointing that out. Must of misinterpreted that part 🙃
