### ISSUE TITLE
choosing tenant based on user

### ISSUE THREAD

**Issue by James4645** [spatie/laravel-multitenancy#257]
I'm want to confirm. If I am going to have one shared Users table for all tenants then say a User belongs to a Tenant. So that `Auth::user()->tenant` would give the the current users tenant instance would I just write a custom TenantFinder class that has a findForRequest() that returns `Auth::user()->tenant`. Then it'll run the tasks to setup the correct tenant. Am I understanding this correctly.

**Comment by thapaPrabhat** [comment]
I m also trying to find tenant using auth user by writing a custom Tenantfinder, but the problem is that the Custom tenant finder will show auth()->user() null.

Is there something i missed ?
