### ISSUE TITLE
Resolve jobs by tenant

### ISSUE THREAD

**Issue by avidal2433** [spatie/laravel-multitenancy#258]
Hello, with this package it is possible to resolve jobs by tenant through the command:

`php artisan tenants:artisan 'queue:work' --tenant=p`

But without saving the jobs in the landlord database if not in the tenant database?

I require it because I have to migrate a normal system to multi tenancy and I do not want to have problems with registered jobs because they will not have the tenancy_id

**Comment by masterix21** [comment]
You can, but means you should start many queue worker for many tenants. I'm closing here because isn't an issue related to the package, but feel free to reply.
