### ISSUE TITLE
Using horizon single DB my queued mails are from a wrong tenant

### ISSUE THREAD

**Issue by rogier-dev** [spatie/laravel-multitenancy#261]
Hi all,

Im developing a system where the tenant can email from their own domain. The thing is that the emails are send from wrong tenants when i use Mail::queue. Synced operations are correct.

I dump() the **** out of the flow for sending the email, logging the send() and queue() and handle() and every time i see the correct tenant with the correct config('mail.from.name').

I noticed that my horizon default queue has 2 processes and when i make 6 tentants and mail with everyone of them the sender mail_from HEADER is 1 of the first 2 tentants, never all 6. The mail contents are from all 6 the tenantsso thats correct.

I think the queue sets the tenant on first run but never updates them, although if i log makeCurrent() the function is called every time.

Using latest laravel and latest multitenancy.

Hope anyone can point me in the right direction.

Kind regards,

Rogier

Edit: Forgot to mention that i overwrite the default config('mail.from') in the makeCurrent() method (which works great!) but not when sending emails via queue.

**Comment by rogier-dev** [comment]
Could it be that the default email.from.name and email.from.address are bootstrapped before the tenant is set? So when the email is send the config is already been read?

**Comment by masterix21** [comment]
@rogier-dev, if you can, please create a public repository on GitHub with the wrong code. I will dig deep. Thanks.

**Comment by masterix21** [comment]
I'm closing here due to inactivity.

**Comment by masterix21** [comment]
https://github.com/spatie/laravel-multitenancy/discussions/561
