### ISSUE TITLE
Files not rendering after install

### ISSUE THREAD

**Issue by muarachmann** [spatie/laravel-multitenancy#263]
Hi there, +1 for such a package which has eased my life on migrating my app to a multi-tenant one. However, while playing with this I noticed my files (to be specific found in `/storage/app/xxx`) are no longer rendered. I am using the 
`response()->file($path, $headers);` to render files to the browser which works perfectly. Since i used this package, files don't seem to render.  Keep showing like broken when I try to preview it in the new tab and the file does exists everything is okay ... path, headers etc

<img width="829" alt="Screen Shot 2021-07-08 at 10 55 47" src="https://user-images.githubusercontent.com/16350814/124902748-25351600-dfdb-11eb-90f4-0d9486cda729.png">

Digging, I thought it might have to do with the filesystem of which I created a task below

```
class FilesystemTask implements SwitchTenantTask
{
    /**
     * @param Tenant $tenant
     */
    public function makeCurrent(Tenant $tenant): void
    {
        $this->setTenantFilesystem($tenant);
    }

    /**
     *
     */
    public function forgetCurrent(): void
    {
        $this->setTenantFilesystem();
    }

    protected function setTenantFilesystem(?Tenant $tenant = null): void
    {
        config()->set('filesystems.disks.tenant', [
            'driver' => 'local',
            'root' => storage_path('app'),
            'visibility' => 'public',
        ]);
    }

}
```

PS: I am working on two branches **develop**, **multitenant-test** when I switch back to a) files render well but on the other branch it gives the above results. Any help would be appreciated thanks.

**Comment by masterix21** [comment]
Did you have made the storage symlink?

**Comment by muarachmann** [comment]
> storage

Hi @masterix21 thanks for your reply and I could finally see the error. I almost had a grey hair my bad. Looks like I left a blank space in my `Task` file - reference https://laracasts.com/discuss/channels/laravel/image-is-being-thrown-as-a-white-blank-image

Closing this thanks

**Comment by masterix21** [comment]
Thanks for your share. Happy coding :)
