### ISSUE TITLE
Migrating Tenant Databases - Multi Database

### ISSUE THREAD

**Issue by wahyubaskara** [spatie/laravel-multitenancy#27]
I've been follow all steps in the documentation, from creating landlord and tenant db connection then create a couple of rows in the tenants table with correct database name. After that i ran this command `php artisan tenants:artisan migrate` but the result always give me error: `Invalid catalog name: 1046 No database selected `

Full error message:
<img width="1412" alt="Screen Shot 2020-05-29 at 11 59 14" src="https://user-images.githubusercontent.com/17234155/83219793-da27bd00-a1a3-11ea-81a1-11a3b5e18e6c.png">

My database config:
<img width="698" alt="Screen Shot 2020-05-29 at 12 00 45" src="https://user-images.githubusercontent.com/17234155/83219871-11966980-a1a4-11ea-9c1f-20869e3bed17.png">

My tenants table in landlord database:
<img width="1020" alt="Screen Shot 2020-05-29 at 12 02 44" src="https://user-images.githubusercontent.com/17234155/83219987-5cb07c80-a1a4-11ea-9517-6f5f81ecd43b.png">

My local databases:
<img width="335" alt="Screen Shot 2020-05-29 at 12 03 53" src="https://user-images.githubusercontent.com/17234155/83220032-810c5900-a1a4-11ea-8e1e-1bbf523867a6.png">

My multitenancy.php config file:
![carbon](https://user-images.githubusercontent.com/17234155/83220408-77372580-a1a5-11ea-9f2b-7a5e89dce5c8.png)

**Comment by martincarvalho** [comment]
@wahyubaskara 
try updating: 
` 'tenant_finder' => null,`
to:
`'tenant_finder' => Spatie\Multitenancy\TenantFinder\DomainTenantFinder::class,`

**Comment by wahyubaskara** [comment]
Not work, same error occurred

**Comment by freekmurze** [comment]
What is the output of `config('multitenancy')` in a tinker session?

**Comment by wahyubaskara** [comment]
Sorry, how can i get the output?

**Comment by freekmurze** [comment]
Run `php artisan tinker`

**Comment by wahyubaskara** [comment]
Here is the result

<img width="731" alt="Screen Shot 2020-05-29 at 23 44 43" src="https://user-images.githubusercontent.com/17234155/83278598-6ec30700-a206-11ea-9c52-4ad88eacb3ac.png">

**Comment by wahyubaskara** [comment]
okay here is 
![carbon](https://user-images.githubusercontent.com/17234155/83280019-99ae5a80-a208-11ea-9624-486b26da2500.png)

**Comment by juanparati** [comment]
@wahyubaskara: try to change:

`"default" => "mysql"`

by

`"default" => "tenant" `

**Comment by wahyubaskara** [comment]
Solved! You saved me, thank you👍

**Comment by kurucu** [comment]
> @wahyubaskara: try to change:
> 
> `"default" => "mysql"`
> 
> by
> 
> `"default" => "tenant"`

Oh my word, this has been tripping me up! Is this in the docs?

**Comment by masterix21** [comment]
@kurucu, no, isn't in the docs because the default connection is a state of mind: depends on your project and your approach.

**Comment by Saimon-git** [comment]
hello spatie guys and @freekmurze 
I am contacting you because I have a problem with the multitenacy package, I can not get the connection to the tenant to work, I have as default connection "tenant" this is the error that I throw
```
SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected (SQL: SHOW FULL TABLES WHERE table_type = 'BASE TABLE')
```

![Screen Shot 2021-04-29 at 21 07 55](https://user-images.githubusercontent.com/17747710/116935948-bb8c3a80-ac2c-11eb-86b3-4217d06d7dd0.png)

**Comment by masterix21** [comment]
@Saimon-git, have you followed the [documentation](https://spatie.be/docs/laravel-multitenancy/v2/using-tasks-to-prepare-the-environment/switching-databases#breadcrumb)?

**Comment by Saimon-git** [comment]
> @Saimon-git, have you followed the [documentation](https://spatie.be/docs/laravel-multitenancy/v2/using-tasks-to-prepare-the-environment/switching-databases#breadcrumb)?

thanks @masterix21

**Comment by refaatgamal** [comment]
I have the same error but all above i made it and still this problem exist
![bruno-kelzer-LvySG1hvuzI-unsplash](https://user-images.githubusercontent.com/18501757/120207170-64c65080-c22c-11eb-83b3-6309f9876261.jpg)

**Comment by masterix21** [comment]
@refaatgamal are you using the SwitchDatabaseTask?

**Comment by refaatgamal** [comment]
Yes and now all tenants works well but I can't make landlord working but tenants works

**Comment by masterix21** [comment]
@refaatgamal, I'm sure it's a misconfiguration issue. Please dig inside reading our documentation. Thanks.

**Comment by refaatgamal** [comment]
Already working as docs but landlord didn't work how can I login as landlord I make virtual domains in local host for tenants but when I go to project direct with out tenant domain it gives me no database selected issue

**Comment by arslanakram1** [comment]
@refaatgamal got any solution on this issue? I'm trying to implement the laravel multitenancy and facing the same issue that you mentioned in your last comment. Thanks

**Comment by masterix21** [comment]
Sorry, but I still think that is a coding problem. Please create a GitHub repository with your sample code that generates the errors: I'll try to help asap.

**Comment by Azmeer-crescent** [comment]
I am having the exact same problem after doing this:
`"default" => "tenant"`

I can login to tenants but NOT to landlord account. getting the same error as:
[refaatgamal](https://github.com/refaatgamal) commented [on May 31, 2021](https://github.com/spatie/laravel-multitenancy/issues/27#issuecomment-851524475)

**Comment by Noor600** [comment]
I got this bug 
![Screenshot 2022-03-28 215157](https://user-images.githubusercontent.com/62808626/160475998-9a72d507-0088-4714-be86-6743feda47fd.png)

**Comment by Noor600** [comment]
`'default' => 'tenant',

    /*
    |--------------------------------------------------------------------------
    | Database Connections
    |--------------------------------------------------------------------------
    |
    | Here are each of the database connections setup for your application.
    | Of course, examples of configuring each database platform that is
    | supported by Laravel is shown below to make development simple.
    |
    |
    | All database work in Laravel is done through the PHP PDO facilities
    | so make sure you have the driver for your particular database of
    | choice installed on your machine before you begin development.
    |
    */

    'connections' => [

        'sqlite' => [
            'driver' => 'sqlite',
            'url' => env('DATABASE_URL'),
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
            'foreign_key_constraints' => env('DB_FOREIGN_KEYS', true),
        ],

        'mysql' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],

        'tenant' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => null,
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],
    
        'landlord' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => 'landlord',
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],`

**Comment by Noor600** [comment]
@masterix21 Is there a solution to this problem ?

**Comment by masterix21** [comment]
Please post your `Admin` model

**Comment by Noor600** [comment]
`class Admin extends Authenticatable {
	use Notifiable;
	protected $table = 'admins';
	protected $fillable = [
		'email',
		'name',
		'photo_profile',
		'password',
		'group_id',
		'remember_token',
	];

	protected $hidden = ['password'];

	public function group_id() {
		return $this->hasOne(\App\Models\AdminGroup::class, 'id', 'group_id');
	}

	public function role($name) {
		$exists_group_id = $this->getConnection()
			->getSchemaBuilder()
			->hasColumn($this->getTable(), 'group_id');
		if ($exists_group_id) {
			$explode_name = explode('_', $name);

			if (!empty($this->group_id()->first())) {
				$role = $this->group_id()->first()->role()->where('name', $explode_name[0])->first();
				if (!empty($role) && $role->{$explode_name[1]} == 'yes') {
					return true;
				} else {
					return false;
				}
			} else {
				return false;
			}
		} else {
			return false;
		}
	}

}`

**Comment by Noor600** [comment]
SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected (SQL: select * from `settings` order by `id` desc limit 1) (View: D:\delivery\resources\views\admin\login.blade.php)
I think this problem not related with Admin model

**Comment by Noor600** [comment]
I created two databases and two domains 
php artisan serve --port=8001

 in two domain I got this problem

**Comment by Noor600** [comment]
Ok I Will prepare the models
 thanks bro ❤️❤️❤️

**Comment by Noor600** [comment]
@masterix21  unfortunately the same problem
:(
I need an urgent solution

**Comment by masterix21** [comment]
The open-source package philosophy lies in free cooperation: so, if you are here to search an urgent solution, the best way is to dig inside the code to found it by yourself.

Anyway, please create a public GitHub repository with your code to help me to understand where are *your* errors. Thanks.

**Comment by Noor600** [comment]
ok
thanks 3>

**Comment by Noor600** [comment]
@masterix21  I created new repo and I invited you

**Comment by abdallah0128318** [comment]
@masterix21 
here I have all things work very good but my problem is just I can`t migrate tenant database tables after the tenant is created 
here is my code 
```
protected static function booted()
    {
        static::creating(fn(User $model) => $model->createDatabase());
    }

    public function createDatabase()
    {
        // add logic to create database

        DB::connection()->statement('CREATE DATABASE tenant_' . $this->username);
        $this->database = 'tenant_' . $this->username;
        Artisan::call('tenants:artisan migrate --tenant=' . $this->id);
    }
```

**Comment by masterix21** [comment]
How can you call `$this->id` if `createDatabase()` is called during the `creating` event?
