### ISSUE TITLE
can i use  this package with mongodb??

### ISSUE THREAD

**Issue by iamabhilashkumar** [spatie/laravel-multitenancy#270]
I am getting below error after switching my database to mongodb Call to a member function prepare() on null

**Comment by iamabhilashkumar** [comment]
Hi Any update on this question ??? Please help..

**Comment by masterix21** [comment]
Hi @iamabhilashkumar,

I'm sorry but I don't use MongoDB, and the package isn't tested with MongoDB. Feel free to create a PR that fixes the bug, if exists one.

Thanks.
