### ISSUE TITLE
NoCurrentTenant exception is not being handled correctly

### ISSUE THREAD

**Issue by rahuls1071** [spatie/laravel-multitenancy#272]
i have setup multitenancy and expecting that when there is NoCurrentTenant exception is thrown , it should redirect to login route. But that is not happening. 

Below is my Exception Hander register method.

`public function register()
    {
        $this->reportable(function (NoCurrentTenant $e) {
            //report($e);
            return redirect('/saml2/laraveltestidp/login');
        });
    }
`

But even after multiple tries it still shows below error only

> Spatie\Multitenancy\Exceptions\NoCurrentTenant
The request expected a current tenant but none was set.

Please help

**Comment by masterix21** [comment]
Hi, please post your full error stacktrace.

Thanks

**Comment by rahuls1071** [comment]
Below is stack trace

> Spatie\Multitenancy\Exceptions\NoCurrentTenant::make
vendor/spatie/laravel-multitenancy/src/Exceptions/NoCurrentTenant.php:11














<?php

 

namespace Spatie\Multitenancy\Exceptions;

 

use Exception;

 

class NoCurrentTenant extends Exception

{

    public static function make()

    {

        return new static('The request expected a current tenant but none was set.');

    }

}

**Comment by rahuls1071** [comment]
Below is stack trace

> Spatie\Multitenancy\Exceptions\NoCurrentTenant::make
vendor/spatie/laravel-multitenancy/src/Exceptions/NoCurrentTenant.php:11

`<? php

namespace Spatie\Multitenancy\Exceptions;
use Exception;

class NoCurrentTenant extends Exception
{
    public static function make()
    {
       return new static('The request expected a current tenant but none was set.');
    }
}`

**Comment by shankarGdev** [comment]
Same issue,

Laravel 8.x

registered in `Handler.php`

```PHP
    public function register()
    {
        $this->reportable(function (Throwable $e) {

        });

        $this->reportable(function (NoCurrentTenant $e) {
            return Api::asError(401)->withHttpCode(401)->withMessage('Unauthenticated')->build();
        });
    }
```

but still getting **500 error** instead of defined response.

**Comment by masterix21** [comment]
@shankarGdev, please enable the debugging in your Laravel Application, then post your stack trace here.

Thanks

**Comment by foresighthub** [comment]
I was having this issue, because I had forgotten to import the NoCurrentTenant class.
