### ISSUE TITLE
Jobs not running (Horizon + Redis)

### ISSUE THREAD

**Issue by muarachmann** [spatie/laravel-multitenancy#273]
Hello, +1 for such package. However, I noticed jobs are not working I keep getting errors of the sort and `queues_are_tenant_aware_by_default` is **true** by default. Looks like its not capable of seeing the database at one point in time.

Sending Notification to users
```
 Invalid catalog name: 1046 No database selected (SQL: select * from `users` where `user`.`id` ....
```

However in the job SendGeneralNotification

```
<?php

namespace App\Jobs;

use App\Models\User;
use App\Notifications\GeneralNotification;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldBeUnique;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Spatie\Multitenancy\Jobs\TenantAware;

class SendGeneralNotification implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    // users which will be notified
    private array $usersIds;

    // data containing message
    private array $data;

    /**
     * Create a new job instance.
     * @param array $usersIds
     * @param array $data
     * @return void
     */
    public function __construct(array $usersIds, array $data)
    {
        $this->data = $data;
        $this->usersIds = $usersIds;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        if (!empty($this->usersIds)) {
            foreach ($this->usersIds as $id) {
               Log::error($user);
                $user = User::findOrFail($id);
                $user->notify(new GeneralNotification($id, $this->data));
            }
        } else {
            User::chunk(200, function($users) {
                foreach ($users as $user) {
                    $user->notify(new GeneralNotification($user->id, $this->data));
                }
            });
        }
    }
}
```
PS: My queue driver is `redis` my database config is set to this

```
    'connections' => [

        'tenant' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => null,
            'username' => env('DB_USERNAME', 'test'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],

        'landlord' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_LANDLORD_URL'),
            'host' => env('DB_LANDLORD_HOST', '127.0.0.1'),
            'port' => env('DB_LANDLORD_PORT', '3306'),
            'database' => env('DB_LANDLORD_DATABASE', 'test'),
            'username' => env('DB_LANDLORD_USERNAME', ''),
            'password' => env('DB_LANDLORD_PASSWORD', ''),
            'unix_socket' => env('DB_LANDLORD_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],
    ],

```

Any help would be appreciated. 
PS: login the current tenant shows the correct db and connection but yet the connection is like kind of lost.

**Comment by rabrowne85** [comment]
Hi @muarachmann,

I was facing something similar recently and was able to solve it by ensuring that the notification class implements the `TenantAware`. You seem to referencing the `use Spatie\Multitenancy\Jobs\TenantAware;` but you're not "implementing" it.

In your code try this:

```php
use Spatie\Multitenancy\Jobs\TenantAware;

class SendGeneralNotification implements ShouldQueue, TenantAware
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;
```

**Comment by muarachmann** [comment]
@rabrowne85  thanks for your reply, I had already tried those alternatives to no avail, just to be clear I am having the jobs table in the tenant app. Can I see your configuration or so? thanks

**Comment by masterix21** [comment]
@muarachmann, can you move the jobs table in the landlord database for test?

**Comment by muarachmann** [comment]
> @muarachmann, can you move the jobs table in the landlord database for test?

@masterix21 moving it and changing the queue database connection to `landlord` there works but honestly I don't know why and IMO seems to me the database connection is lost temporarily. I just can't catch the instance, this happens for various tables, e.g sending notifications to users using jobs, processing a large file in background using jobs. 

If I do `$user->notify(new GeneralNotification(...))` in a controller it works perfectly however, with in a job this same code doesn't work in the handler method even thought it is `TenantAware`. When it tries to query the users table, looks like the database is null, and this is true because we set it null here `database.connections.tenant.database = null` when I hard code it, it selects that db and works fine. However, what if I am in another tenant say `developer.domain.test` .

**Comment by muarachmann** [comment]
@rabrowne85 tried to no avail... I ended up using https://tenancyforlaravel.com/docs/v3/introduction/ for now though spatie's is easier to setup IMO.

**Comment by b4oshany** [comment]
I'm also experiencing this problem. Is there a solution to this?

**Comment by alexv96** [comment]
Did you solve the problem? The other question I have a multi tenant app, should I work the jobs in the central database or per tenant?

**Comment by ettiennelouw** [comment]
Also getting this same error, for the last 2 weeks.

**Comment by RobertCordes** [comment]
I'm having trouble as well. I'm using Redis as my queue connection. When I use sync, everything works fine.
