### ISSUE TITLE
Documenting Multi-tenant & Landlord login solution

### ISSUE THREAD

**Issue by sausin** [spatie/laravel-multitenancy#276]
Been using the package for a while and things work reasonably well with the multi-tenant side of things now. However, there seems to be no consensus (in the issues that have been resolved as well) as to how to approach a setup where in the landlord user can also login to the system.

As a resolution to this issue, I'll attempt a PR that can guide people through the process of setting things up along these lines. Below are the things that would be good to have functional in a consistent fashion:

- Landlord user using the same model (`App\User`) to login
  - The `App\User` model doesn't use the trait `UsesTenantConnection` to allow for flexible connection
  - The `domain` for the landlord will be sent via headers or cookies to let the system know which database connection to use
  - Alternatively, regular tenants would be coming in via a sub-domain
- `actingAs` setup. Once authenticated, it would be great to have the landlord (with relevant permissions) act as a tenant
  - This would allow for great support when any of the tenants are stuck on anything

For the 2nd part of the problem, it's of course possible to have a user (or a group of users) from the landlord database added to the tenants (via queues) so they can just login.

However, if an 'actingAs` becomes possible the whole process would be super seamless. Any pointers on how to achieve this would be awesome.

**Comment by masterix21** [comment]
Hi @sausin, a PR to improve the documentation is much appreciated. Thanks for your effort.

**Comment by keithmclaughlin** [comment]
Any more on this?

**Comment by sausin** [comment]
@keithmclaughlin couldn't really figure out a nice solution on this. Happy to get ideas and can help with updating documentation subsequently
