### ISSUE TITLE
Compatibility with Octane?

### ISSUE THREAD

**Issue by binaryfire** [spatie/laravel-multitenancy#280]
Hi guys,

Just wondering if this package is compatible with Octane? I'm trying to find a way to use Swoole with a multi tenant / multi domain app.

Cheers

**Comment by masterix21** [comment]
Hi @binaryfire 

Yes, the package support Octane.

**Comment by binaryfire** [comment]
@masterix21 Awesome. Thanks!

**Comment by adarmanto** [comment]
I used Laravel v10 + Octane (frankenphp) works fine.

But when trying to apply it to my project using laravel-multitenany, I got this error when trying to login using laravel authentication:

![image](https://github.com/spatie/laravel-multitenancy/assets/26041956/ab9a71ff-a22d-4a70-baa5-50f98443d985)

My setup:
- Laravel v10.40.0
- spatie/laravel-multitenancy v3.1.0 using multiple databases
- Octane v2.2.7
- `User` model `UsesLandlordConnection`

Any ideas about what's happening, guys? thanks

**Comment by masterix21** [comment]
Hi @adarmanto, I don't know because FrankenPHP support is still in beta. I will take a look at it when it is stable.
