### ISSUE TITLE
Database Not Selected for landlord

### ISSUE THREAD

**Issue by arslanakram1** [spatie/laravel-multitenancy#289]
I'm trying to implement the laravel multitenancy. My configuration is according to the documentation but when I try to log in without a tenant. For example, My URL is http://virtualhost.com and my tenant URL is http://tenant.virtualhost.com.
When I  try to access the database on tenant URL its working fine but on the landlord URL its gives the error: -

![Screenshot from 2021-09-13 17-14-44](https://user-images.githubusercontent.com/73931889/133081854-8fbef356-eba2-46b9-bc4c-9f1f50d9178a.png)

Multitenancy.php
![Screenshot from 2021-09-13 17-18-47](https://user-images.githubusercontent.com/73931889/133082187-f7fdafd8-d3c2-4f06-827d-b8dbfef137f6.png)

database.php
![Screenshot from 2021-09-13 17-20-14](https://user-images.githubusercontent.com/73931889/133082321-a1e716dc-c5d1-479d-8dbe-cf64be127604.png)

**Comment by parthjani7** [comment]
How does your `DomainTenantFinder` look like ?

**Comment by arslanakram1** [comment]
@parthjani7 


    public function findForRequest(Request $request):?Tenant
    {
        $host = $request->getHost();

        return $this->getTenantModel()::whereDomain($host)->first();
    }
}

**Comment by parthjani7** [comment]
can you also put your other files here i.e. (Landlord model , routes, Kernel etc.)

**Comment by arslanakram1** [comment]
@parthjani7  I got it solved by documentation
All models in your project should either use the UsesLandlordConnection or UsesTenantConnection, depending on if the underlying table of the models lives in the landlord or tenant database.
