### ISSUE TITLE
Command to migrate seeders does not work

### ISSUE THREAD

**Issue by alexv96** [spatie/laravel-multitenancy#304]
I created an app, saw the documentation and ran a command that apparently was for seeders but apparently it only migrates what is in the database/migrations folder. 

The idea is to run a seed in a specific tenant. 

![image](https://user-images.githubusercontent.com/33232796/140190667-512bf494-acf5-44aa-b557-694ba12f5be9.png)

![image](https://user-images.githubusercontent.com/33232796/140190742-4ed27499-2339-4edb-989a-76f351264c83.png)

I created a command where I tell it already enters the tenant X, and from there I want to call what would be the action of the seeder, but as you see in the image says that it is forbidden to use --class and with the normal command does not run the seeder.

**Comment by masterix21** [comment]
Try with:

```php
Artisan::call('tenants:artisan', [
    'artisanCommand' => 'migrate --seed --class=TenantDatabaseSeeder'
])
```

**Comment by chris-ware** [comment]
The --class parameter isn't available when using the migrate command, its only on the db:seed command.

**Comment by michaelhume** [comment]
I have bit of a strange experience with this as well. 

when I run `tenants:artisan "db:seed --class=MockDataSeeder"` it always invokes the main DatabaseSeeder class and seems to ignore the --class option. I've tried a number of variations on the command without any success.

Just curious @alexv96 if you were able to have success with this?

**Comment by masterix21** [comment]
hi @michaelhume, check here.
```
Usage:
  db:seed [options] [--] [<class>]
```

Try with `tenants:artisan "db:seed MockDataSeeder`

**Comment by michaelhume** [comment]
Thanks @masterix21 .. turned out to be a different issue - PEBKAC.
