### ISSUE TITLE
multitenancy with Jetstream / Fortify - database selection / session issue

### ISSUE THREAD

**Issue by CodeAdminDe** [spatie/laravel-multitenancy#305]
Hello together,

## Initial situation

I want to make a Laravel application multitenant capable with the 'spatie/laravel-multitenancy' package and use multiple databases (landlord, tenant1, tenant2, ...). The app is a Jetstream installation (installed without --team option) and uses Livewire as a base. 'database' is used as session driver (Jetstream default).

## Steps performed

I followed the steps in the installation guide at https://spatie.be/docs/laravel-multitenancy/v2/installation/base-installation to install the package, setup the config and database connections and added the `UsesTenantConnection/UsesLandlordConnection` traits to my models. 
Since all routes should be tenant aware, I added the package middlewares to the "web" route group.

For testing purposes I've created a tenant incl. database manually ('tenant1.localhost').

## Issue

The sessions are written to / read from the landlord database and not - as I would expect - to / from the tenant databases. 
This can be recreated by calling 'http://tenant1.localhost' as this fails until I perform the migration of the session table for the landlord database. Also sessions of other tenants are written to the landlord database as soon as the migration was done.

![grafik](https://user-images.githubusercontent.com/53627251/140996135-306666c9-427b-4e37-8d62-8ccca40d55f9.png)

Furthermore, I noticed that Livewire also tries to write tenant aware data to the landlord database. (Tested by saving changes at the default jetstream profile information component).

![grafik](https://user-images.githubusercontent.com/53627251/140997290-4e564b2f-82f6-4bde-8f7b-2a2d8004c4bf.png)

How can I get Fortify(?) to store / read the sessions tenant aware in the respective tenant database? (Changing the driver to file would solve the issue supposedly, but this is not an option for other reasons at all).

How do I get Livewire (or globally all components) to use the correct databases as well?

I hope the description of the issue is clear enough and appreciate any " push in the right direction". 
Otherwise, please ask questions and I'll try to answer them as best I can.

Thanks in advance!

**Comment by masterix21** [comment]
Did you try to use `SESSION_CONNECTION=landlord` in your .env file?

**Comment by CodeAdminDe** [comment]
> Did you try to use `SESSION_CONNECTION=landlord` in your .env file?
> 
> I'm closing here becuase isn't a package issue, but feel free to continue the talk here.

Sorry for the long response time. Life got in the way. :/

I didn't .. but now i've tried `SESSION_CONNECTION=tenant` which does the trick. :+1:  Fortify now uses the tenant databases. :-) (Of course that means it does not work when no tenant is loaded, but that's an issue i'll handle later on. :-) )

The issue left is Livewire, it behaves like mentioned above... do you know how to get livewire to use the correct database connection as well? Or at least a tip in which direction i need to go?

Thanks in advance! :-)

**Comment by CodeAdminDe** [comment]
## UPDATE

The second issue wasn't livewire related...

I'm using `unique` and `exists` within my validation rules and they require database lookups.
These lookups are made against the default (`landlord`) connection by default. 

Solution: Added the connection name (`tenant`) for each rule that needs a database lookup for tenant data.

For anyone who runs into the same issue: The official documentation describes how to explicitly specify a different database connection for validation:

* `exists` rule: https://laravel.com/docs/8.x/validation#specifying-a-custom-column-name
* `unique` rule: https://laravel.com/docs/8.x/validation#rule-unique

**Comment by CodeAdminDe** [comment]
> @CodeAdminDe Could you show me how your rules look like? :)

Do you mean a sample validation rule? Sure!

This simple `$input` validation is our example. It just validates the *name* and *email* attribute of the `$input` array:

```php
Validator::make($input, [
            'name' => ['required', 'string', 'max:255', new Name],
            'email' => ['required', 'string', 'email:strict,dns,filter', 'max:255', 'unique:users'],
        ])->validate();
```

Take a closer look at the `unique` validation of the email attribute. 
We're just validating that the attribute is unique within the users table while using the **default** database connection.


But, because our users are stored within the tenant database, the **tenant** database connection need to specified explicit:

```php
Validator::make($input, [
            'name' => ['required', 'string', 'max:255', new Name],
            'email' => ['required', 'string', 'email:strict,dns,filter', 'max:255', 'unique:tenant.users'],
        ])->validate();
```

As mentioned, the validation against a specific database connection is described within the offical laravel documentaion (see links above).

I hope this has brought some clarity.
