### ISSUE TITLE
PrefixCacheTask is overwriting prefixes on redis sessions

### ISSUE THREAD

**Issue by recognizerHD** [spatie/laravel-multitenancy#310]
Hello, I've been migrating my project to use multitenancy and I think I'm stuck on one final piece. I can't use the EnsureValidTenantSession as the session should be tenant unaware. A single user could manage several tenants and switch easily between them. I've got this almost working except when it saves the session, it prefixes the session key with the tenant information: 

![image](https://user-images.githubusercontent.com/1222899/144162450-c04d2d22-9687-4f8d-8d66-9e066c33de90.png)

I'm using redis for sessions and it looks like the PrefixCacheTask is what replaces the prefix. I do wish to keep the class as other things within the tenant databases will be cached and I would like to keep this functionality.

If you could point me in the right direction, that would be great.

**Comment by masterix21** [comment]
I think you should create a custom middleware to check the session, for example, creating a session with all user's tenant ids.
