### ISSUE TITLE
VerifyEmail send wrong signed url when queued

### ISSUE THREAD

**Issue by hanicab** [spatie/laravel-multitenancy#318]
Hello,

I have an issue with the package when using VerifyEmail notification as queued.

the url sent to users is the landlord url (root domain) and not the tenant url.

this bug is only if the VerifyEmail is queued, but work correctly if not queued.

example :
if not queued : https://tenant.mydomain.com/fr/dash/email/verify/19/d519beaa6abec64...
if queued : https://mydomain.com/fr/dash/email/verify/19/d519beaa6abec64...

I have tried to resolve the problem by myself but not working.

can you please help me ? 

php 8
laravel 8
queues_are_tenant_aware_by_default => true
spatie/laravel-multitenancy v2

**Comment by BartMommens** [comment]
That seems odd, are you using additional packages like Laravel/Fortify for example?
Posting some code would also help other members determin a potential issue.

**Comment by masterix21** [comment]
Hi @hanicab. If you are using a job that doesn't implement the `TenantAware` interface (because you can't or isn't part of your code), you could add your job to the multitenancy config, in the array list `tenant_aware_jobs` like so:
```php
'tenant_aware_jobs' => [
    VerifyEmail::class,
],
```

Please try and give us feedback.

Thank you

**Comment by hanicab** [comment]
@BartMommens thank you for your reply, yes I use laravel/ui ^3.2 package
@masterix21 thank you for your reply, I have tried to add the job to the multitenancy config but not working, still the same problem :(
I think the problem is in the URL::temporarySignedRoute() function of laravel, can you please test from your side ?

**Comment by BartMommens** [comment]
@hanicab  Sorry for my late reply,
I don't have any experience with the Laravel/ui package, but it's possible that you have to extend VerifyEmail::class.
And within this class you could rewrite the verification url based on the domain of your current tenant?

I've added some information about it below. Second article might get you started.

https://laravel.com/docs/8.x/verification
https://wildangunawan.medium.com/customize-laravel-8-email-verification-url-with-your-spa-url-50010479813

Hopefully you get some useful information from this.

Also, try posting some of your code so other users can take a look at what you are doing and what's going on in order to create a better response to your problem.

**Comment by hanicab** [comment]
@BartMommens  Thank you very much for your reply.

After some tests, I found that the problem is the route() function of laravel, it not working correctly with the spatie multitenancy package when called in queued jobs even if thee job is tenant aware.

You can test that, by calling the route() function in any queued job, you will see that the returned url is the landlord domain and not the tenant domain.

```
use Illuminate\Contracts\Queue\ShouldQueue;
use Spatie\Multitenancy\Jobs\TenantAware;
use Illuminate\Support\Facades\Log;

class TestJob implements ShouldQueue, TenantAware
{
    // ..
    public function handle()
    {
        Log::debug(route('home'));
        // https://landlord-domain.com/home
    }
 }
```

**Comment by BartMommens** [comment]
Hmmm, I don't know if it changes something but what if you set your default connection in

config/database.php to tenant?


```
use Illuminate\Support\Str;

return [

    /*
    |--------------------------------------------------------------------------
    | Default Database Connection Name
    |--------------------------------------------------------------------------
    |
    | Here you may specify which of the database connections below you wish
    | to use as your default connection for all database work. Of course
    | you may use many connections at once using the Database library.
    |
    */

    #'default' => env('DB_CONNECTION', 'mysql'),
    'default' => 'tenant',
    
    //rest of config
];
```

**Comment by hanicab** [comment]
@BartMommens  The same problem :(

**Comment by hanicab** [comment]
@masterix21 That works ! thank you
But I think it is not practical to add this piece of code in all the jobs, so I tried to improve this by adding this code to boot() function of AppServiceProvider :

```
Queue::before(function (JobProcessing $event) {
    if(app('currentTenant')){
        \URL::forceRootUrl("tenant-base-url");
    }
});
```

**Comment by masterix21** [comment]
Create a task to switch the URL 😉

**Comment by francois-soapbox** [comment]
Same here, forcing the root url may cause issues verifying temporary urls, right?

**Comment by francois-soapbox** [comment]
This seems to work:
```
<?php

namespace App\Support\Multitenancy\Tasks;

use Illuminate\Support\Facades\URL;
use Spatie\Multitenancy\Models\Tenant;
use Spatie\Multitenancy\Tasks\SwitchTenantTask;

class SwitchRootUrlTask implements SwitchTenantTask
{
    public function makeCurrent(Tenant $tenant): void
    {
        $scheme = request()->getScheme();

        $this->forceRootUrl("{$scheme}://{$tenant->domain}");
    }

    public function forgetCurrent(): void
    {
        $this->forceRootUrl(config('app.url'));
    }

    protected function forceRootUrl(string $url): void
    {
        URL::forceRootUrl($url);
    }
}
```

**Comment by masterix21** [comment]
Great :) I'm closing here. Thanks

**Comment by MattWiseParking** [comment]
perhaps if you didnt want to add the SwitchRootUrlTask as this would have a global impact, instead add a middleware to the job, in the middleware you can change the root url.
