### ISSUE TITLE
SwitchTenantDatabaseTask is not setting the tenant connection as default.

### ISSUE THREAD

**Issue by dyanakiev** [spatie/laravel-multitenancy#319]
Hello,

I'm using this package for some time now, and i wanted to share a bug i found.

I'm using different databases for each of my tenants.

My `database.php` config looks something like this
```php
<?php 
return [
'default' => 'undefined',
'connections' => [
     'core' => [...]
     'tenant' => [...]
]
```

With this configuration when the default is not defined as the `tenant` connection, the tenant cannot access its database.
I think my configuration is valid and i don't see it documented that my `tenant` database should be the default one also.

I have solved the issue for myself with my own SwitchTenantDatabaseTask and setting in there the `database.default`
```php
<?php
...
config([
    "database.default" => $tenantConnectionName??'undefined', <-- this (could also set the originalDefault when forgetting current tenant)
    "database.connections.{$tenantConnectionName}.database" => $databaseName,
]);
 ```

The reason why I'm also opening this issue, is to ask if im doing something wrong and the provided database.php configuration should be working without me creating my own SwitchTenantDatabaseTask as i expected that laravel will know to use the tenant database, but it doesn't and i have to set it as default in the task?

**Comment by dyanakiev** [comment]
As i was reading the docs i have missed this section
```
https://spatie.be/docs/laravel-multitenancy/v2/installation/using-multiple-databases#preparing-models
All models in your project should either use the `UsesLandlordConnection` or `UsesTenantConnection`, depending on if the underlying table of the models lives in the landlord or tenant database.
```
So yes if i set `UsesTenantConnection` to each tenant model, this won't be an issue, but i guess the `SwitchTenantDatabaseTask` is to ease the task of setting `UsesTenantConnection` in each models?

**Comment by masterix21** [comment]
You're wrong because using both connections (core and tenant, for you), you have no way to understand if a model uses the core or the tenant connection. It isn't the right choice to keep an invalid default connection because all commands and any parts of your code will evaluate it before.

I'm closing here because it isn't related to a package issue. Thanks.
