### ISSUE TITLE
MadeTenantCurrentEvent doesn't seem to work.

### ISSUE THREAD

**Issue by mxm1070** [spatie/laravel-multitenancy#340]
The [MadeTenantCurrentEvent ](https://spatie.be/docs/laravel-multitenancy/v2/advanced-usage/listening-for-events#content-spatiemultitenancyeventsmadetenantcurrentevent)doesn't seem to work.

I'm listening for it in my EventServiceProvider:
```php
\Spatie\Multitenancy\Events\MadeTenantCurrentEvent::class => [
    \App\Listeners\SetupTenantTheme::class,
]
```

```php
<?php

namespace App\Listeners;

use Spatie\Multitenancy\Events\MadeTenantCurrentEvent;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;

class SetupTenantTheme
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  \Spatie\Multitenancy\Events\MadeTenantCurrentEvent  $event
     * @return void
     */
    public function handle(MadeTenantCurrentEvent $event)
    {
        ray($event->tenant);
    }
}
```

When I load the home page of a tenant nothing is printed. If put a ray call inside the MakeTenantCurrentAction I do see the tenant in ray, but my listener doesn't pick it up:
```php
public function execute(Tenant $tenant)
{
    event(new MakingTenantCurrentEvent($tenant));

    $this
        ->performTasksToMakeTenantCurrent($tenant)
        ->bindAsCurrentTenant($tenant);

    event(new MadeTenantCurrentEvent($tenant));

    ray($tenant);

    return $this;
}
```

If I listen for all the events in my app, MadeTenantCurrentEvent is not in there:
```php
public function boot()
{
    Event::listen('*', function ($event) {
        ray($event);
    });
}
```

If I fire the event manually in a route it works fine:
```php
event(new MadeTenantCurrentEvent(Tenant::find(1)));
```

I know the event is firing from putting the ray call inside MakeTenantCurrentAction, but it seems like it's before my app is listening for it. I suspect the other 3 events also aren't picked up.

**Comment by masterix21** [comment]
Why don't you use a custom task to switch the theme?

**Comment by mxm1070** [comment]
It's just preference. It's a task that needs to be done after all the other tasks because I need to retrieve data from the tenant database connection to setup the theme which I can't do because inside the tasks the tenant connection hasn't been setup yet. I could set it up manually, but the events are there so I would like to use them.

Right now the tenant isn't set until after all the tasks are run and this line:
```php
app()->instance($containerKey, $tenant);
```
is run inside
``` 
Spatie\Multitenancy\Models\Tenant->makeCurrent->MakeTenantCurrentAction->execute->bindAsCurrentTenant
```

You can see inside MakeTenantCurrentAction
```php
public function execute(Tenant $tenant)
{
    event(new MakingTenantCurrentEvent($tenant));

    $this
        ->performTasksToMakeTenantCurrent($tenant)
        ->bindAsCurrentTenant($tenant);

    event(new MadeTenantCurrentEvent($tenant));

    return $this;
}
```
The event should fire immediately after this, but it just doesn't. So I could make task that manually sets up the connection like:

```php
DB::usingConnection(config('multitenancy.tenant_database_connection_name'), function() {
    ThemeLoader::activeTheme()->bootTheme();
});
```
But again, the events are there so I would like to use them. The way I'm getting around it is to use my own tenant model and just override the makeCurrent method
```php
public function makeCurrent(): BaseTenant
{
    $tenant = parent::makeCurrent();
    ThemeLoader::activeTheme()->bootTheme();
    return $tenant;
}
```
I just find it really weird that none of the 4 tenant events fire in my app.

**Comment by markieo1** [comment]
We are experiencing the same issue. For now we are switching to tasks for this. But we think it should be resolved anyway.

**Comment by mr-mr7** [comment]
solved this issue?
I also have same issue
can any one help me
