### ISSUE TITLE
Any database queries executed after 'executing code for tenants in landlord context' will throw an exception

### ISSUE THREAD

**Issue by hanicab** [spatie/laravel-multitenancy#343]
Hello,

I have a problem with the package, I think thats a bug.

When executing code for tenants in landlord context, any database queries (for landlord tables) after that will throw an exception because when the package forget the last current tenant, the database name will be null instead of the landlord database name. 

```php
Route::delete('/api/{tenant}/flush-cache', function (Tenant $tenant) {

    $result = $tenant->execute(fn (Tenant $tenant) => cache()->flush());

    AnyLandlordTable::update(['key'=>'value']) // This code will throw an exception "no database selected"

    return json_encode(["success" => $result]);
});
```
Best regards,

**Comment by masterix21** [comment]
Does your `AnyLandlordTable` model implements the `UsesLandlordConnection` trait?

**Comment by masterix21** [comment]
I'm closing here due to inactivity and because I think isn't related to a package issue. Anyway, feel free to continue the talk here.
