### ISSUE TITLE
php artisan tenants:artisan "queue:work" not working

### ISSUE THREAD

**Issue by isaacdarcilla** [spatie/laravel-multitenancy#348]
### Discussed in https://github.com/spatie/laravel-multitenancy/discussions/347

<div type='discussions-op-text'>

<sup>Originally posted by **isaacdarcilla** March 26, 2022</sup>
I have jobs stored in tenant database. Now, when I run command `php artisan tenants:artisan "queue:work"`  it does not process the queue. How can I resolve this?

![image](https://user-images.githubusercontent.com/22732118/160223168-8ee998fa-7c4c-43f5-a3bd-8bf71d2697fe.png)

![image](https://user-images.githubusercontent.com/22732118/160223178-a72dcc0c-15a4-4368-bfcb-1bebfdfc420c.png)
</div>

**Comment by francoism90** [comment]
@isaacdarcilla Did you tried this https://github.com/spatie/laravel-multitenancy/issues/273#issuecomment-891696327?

**Comment by isaacdarcilla** [comment]
@francoism90 yes I implemented the class. However, when I run the comman, this is what I got.

[2022-03-28 09:28:20] local.ERROR: Call to a member function beginTransaction() on null {"exception":"[object] (Error(code: 0): Call to a member function beginTransaction() on null at C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Concerns\\ManagesTransactions.php:175)
[stacktrace]
#0 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Concerns\\ManagesTransactions.php(141): Illuminate\\Database\\Connection->handleBeginTransactionException(Object(Error))
#1 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Concerns\\ManagesTransactions.php(115): Illuminate\\Database\\Connection->createTransaction()
#2 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Concerns\\ManagesTransactions.php(23): Illuminate\\Database\\Connection->beginTransaction()
#3 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\DatabaseQueue.php(222): Illuminate\\Database\\Connection->transaction(Object(Closure))
#4 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(331): Illuminate\\Queue\\DatabaseQueue->pop('default')
#5 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(340): Illuminate\\Queue\\Worker->Illuminate\\Queue\\{closure}('default')
#6 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(145): Illuminate\\Queue\\Worker->getNextJob(Object(Illuminate\\Queue\\DatabaseQueue), 'default')
#7 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(117): Illuminate\\Queue\\Worker->daemon('database', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#8 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'default')
#9 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#10 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#12 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#13 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(614): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#14 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(136): Illuminate\\Container\\Container->call(Array)
#15 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\symfony\\console\\Command\\Command.php(288): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Illuminate\\Console\\OutputStyle))
#16 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Illuminate\\Console\\OutputStyle))
#17 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\symfony\\console\\Application.php(974): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Illuminate\\Console\\OutputStyle))
#18 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\symfony\\console\\Application.php(291): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Illuminate\\Console\\OutputStyle))
#19 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\symfony\\console\\Application.php(167): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Illuminate\\Console\\OutputStyle))
#20 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(92): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Illuminate\\Console\\OutputStyle))
#21 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(184): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Illuminate\\Console\\OutputStyle))
#22 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(263): Illuminate\\Console\\Application->call('queue:work', Array, Object(Illuminate\\Console\\OutputStyle))
#23 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(261): Illuminate\\Foundation\\Console\\Kernel->call('queue:work', Array, Object(Illuminate\\Console\\OutputStyle))
#24 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\spatie\\laravel-multitenancy\\src\\Commands\\TenantsArtisanCommand.php(30): Illuminate\\Support\\Facades\\Facade::__callStatic('call', Array)
#25 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Spatie\\Multitenancy\\Commands\\TenantsArtisanCommand->handle()
#26 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#27 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#28 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#29 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(614): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#30 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\spatie\\laravel-multitenancy\\src\\Commands\\Concerns\\TenantAware.php(34): Illuminate\\Container\\Container->call(Array)
#31 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\spatie\\laravel-multitenancy\\src\\Models\\Tenant.php(89): Spatie\\Multitenancy\\Commands\\TenantsArtisanCommand->Spatie\\Multitenancy\\Commands\\Concerns\\{closure}(Object(Spatie\\Multitenancy\\Models\\Tenant))
#32 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\spatie\\laravel-multitenancy\\src\\Commands\\Concerns\\TenantAware.php(34): Spatie\\Multitenancy\\Models\\Tenant->execute(Object(Closure))
#33 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\LazyCollection.php(655): Spatie\\Multitenancy\\Commands\\TenantsArtisanCommand->Spatie\\Multitenancy\\Commands\\Concerns\\{closure}(Object(Spatie\\Multitenancy\\Models\\Tenant), 0)
#34 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Traits\\EnumeratesValues.php(740): Illuminate\\Support\\LazyCollection->Illuminate\\Support\\{closure}()
#35 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Traits\\EnumeratesValues.php(453): Illuminate\\Support\\LazyCollection->reduce(Object(Closure), 0)
#36 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\spatie\\laravel-multitenancy\\src\\Commands\\Concerns\\TenantAware.php(35): Illuminate\\Support\\LazyCollection->sum()
#37 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\symfony\\console\\Command\\Command.php(288): Spatie\\Multitenancy\\Commands\\TenantsArtisanCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#38 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#39 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\symfony\\console\\Application.php(974): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#40 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\symfony\\console\\Application.php(291): Symfony\\Component\\Console\\Application->doRunCommand(Object(Spatie\\Multitenancy\\Commands\\TenantsArtisanCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#41 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\symfony\\console\\Application.php(167): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#42 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(92): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#43 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#44 C:\\Users\\Isaac\\Desktop\\Dev\\Laravel\\school-aide-saas\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#45 {main}
"}

**Comment by isaacdarcilla** [comment]
So, I think it's working now. I have different error now, I did configured the `queue.php` config because its pointing in the wrong database connection. I just have to save the queue jobs to the master database, not the tenants.

**Comment by masterix21** [comment]
What's your new error?

**Comment by isaacdarcilla** [comment]
Just some SMTP error, its working now. Thanks!

**Comment by masterix21** [comment]
Ok, I'm closing it. Thanks
