### ISSUE TITLE
Unable to install the package in a new laravel project

### ISSUE THREAD

**Issue by cherosoullis** [spatie/laravel-multitenancy#362]
When trying to install package in a new laravel project ("laravel/framework": "^9.2") I get the following error:
  Problem 1
    - illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.0.13) does not satisfy that requirement.
    - Root composer.json requires spatie/laravel-multitenancy 2.0 -> satisfiable by spatie/laravel-multitenancy[2.0.0].
    - Conclusion: don't install laravel/framework v9.3.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.3.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.4.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.4.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.5.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.5.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.6.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.7.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.8.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.8.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.9.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.2.0 (conflict analysis result)
    - spatie/laravel-multitenancy 2.0.0 requires illuminate/support ^8.0 -> satisfiable by illuminate/support[v8.0.0, ..., 8.x-dev].
    - Only one of these can be installed: illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v9.2.0, ..., 9.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^9.2 -> satisfiable by laravel/framework[v9.2.0, ..., 9.x-dev].

I am using Windows and php version 8.0.13

**Comment by masterix21** [comment]
Hi @cherosoullis, take a look at your PHP version.

I'm closing here because is not a package issue.

**Comment by ManissDev** [comment]
Install the latest version.

So run:
`composer require spatie/laravel-multitenancy`

Instead of:
`composer require "spatie/laravel-multitenancy:^2.0"`
