### ISSUE TITLE
DB Transactions

### ISSUE THREAD

**Issue by moisish** [spatie/laravel-multitenancy#371]
When you switch to a different database per tenant and use database transactions, the DatabaseTransactionsManager is using the default connection and therefore the rollback is not working since it's doing it on the wrong database\

```
DB::transaction(function () {
                $this
                    ->updateDetails()
                    ->updatePermissions()
            });
````

```
Illuminate\Database\DatabaseTransactionsManager {#428
  #transactions: Illuminate\Support\Collection {#429
    #items: array:1 [
      0 => Illuminate\Database\DatabaseTransactionRecord {#403
        +connection: "landlord"
        +level: 1
        #callbacks: []
      }
    ]
    #escapeWhenCastingToString: false
  }
  #callbacksShouldIgnore: null
}
```

Is there a better way to use transactions from having to add everywhere

```
DB::connection($this->tenantDatabaseConnectionName())->transaction(function () {
})
```

**Comment by moisish** [comment]
Is there a better way to use transactions from having to add everywhere 

 ```
 DB::connection($this->tenantDatabaseConnectionName())->transaction(function () {
});
```

What are the issues

**Comment by masterix21** [comment]
`DB::transaction(...)` uses your default connection. Set your env with the tenant connection as default connection, but IMHO, is better to keep the landlord there, using `DB::connection('tenant')->transaction(...)`.

**Comment by moisish** [comment]
I read your comment on this https://github.com/spatie/laravel-multitenancy/issues/319 which is why I didn't want to change the default connection

**Comment by moisish** [comment]
I came up with a solution to override the database manager so when there is a tenant it's always using tenant's connection but this is still flexible to use the landlord connection while you are on a tenant

On a Service Provider you need to register 
```
    public function register()
    {
        $this->app->bind('db', function($app){
            return new DatabaseManager($app, $app['db.factory']);
        });
    }
```    


```
class DatabaseManager extends \Illuminate\Database\DatabaseManager
{
    use UsesMultitenancyConfig;

    public function tenant()
    {
        return $this->connection($this->tenantDatabaseConnectionName());
    }

    public function landlord()
    {
        return $this->connection($this->landlordDatabaseConnectionName());
    }

    /**
     * Dynamically pass methods to the default connection.
     *
     * @param  string  $method
     * @param  array  $parameters
     * @return mixed
     */
    public function __call($method, $parameters)
    {
        if (static::hasMacro($method)) {
            return $this->macroCall($method, $parameters);
        }

        if (Tenant::current()) {
            return $this->tenant()->$method(...$parameters);
        }

        return $this->landlord()->$method(...$parameters);
    }
}
```

@freekmurze is this an addition you will accept for a PR?

**Comment by freekmurze** [comment]
I also prefer to keep things how they are for now.
