### ISSUE TITLE
Not possible to use database transactions when switching tenant

### ISSUE THREAD

**Issue by Muffinman** [spatie/laravel-multitenancy#377]
I may be interpreting this wrong, but it seems to be like it's not currently possible to use `DatabaseTransactions` when switching tenants (useful during tests).

I believe this due to re-use of the [DatabaseTransactionManager](https://github.com/illuminate/database/blob/master/DatabaseTransactionsManager.php) between tenant connections.

## Aim

My aim is to run pest tests against the `landlord` and `tenant` database connections, without affecting the existing data in my MySQL database.

My thought was to call `beginDatabaseTransaction()` for each connection before refreshing the databases and re-running migrations etc. That way the `rollBack` can just undo everything the testing messed with.

Consider the following workflow:

1. Connection made to `tenant` DB
2. Transaction started and recorded in `DatabaseTransacationManager::$transactions` under `tenant` [connection name](https://github.com/illuminate/database/blob/master/DatabaseTransactionsManager.php#L41).
3. `app('db.transactions')` is defined is a singleton and is therefore re-used between connections.
4. Tenant is switched, a new instance of the DB Connection is attached [here](https://github.com/spatie/laravel-multitenancy/blob/main/src/Tasks/SwitchTenantDatabaseTask.php#L44), but the previous connection's transactions are not committed, rolled back, or otherwise cleared.
5. New Transaction attempted and stored against same connection name as above.
6. When rollbacks are attempted, transactions from previous tenant connection [still exist here](https://github.com/illuminate/database/blob/master/DatabaseTransactionsManager.php#L55) and rollbacks of these are also attempted.
7. MySQL errors with `SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT trans3 does not exist` or similar

Am I mis-reading this? I feel like there might be an obvious thing I'm missing.

**Comment by masterix21** [comment]
I’m using the package and Pest with no pain.

In the `Pest.php` I have the function tenant like so:
```php
function tenant(callable $callable, ?Tenant $tenant = null): void
{
    $tenant ??= Tenant::first();

    $tenant->execute(fn () => DB::connection('tenant')->transaction(function () use ($callable) {
        $callable();

        DB::connection('tenant')->rollBack();
    }));
}
```

So, in my tests:
```php
it(’works’, fn() => tenant(function() {
        // your tenant tests
});
```

**Comment by Muffinman** [comment]
Thanks @masterix21, that's an interesting approach. I will give that a try.

I presume you don't use the [docs testing transactions setup](https://spatie.be/docs/laravel-multitenancy/v2/advanced-usage/executing-code-for-tenants-and-landlords#content-testing-with-databasetransactions-for-tenant) in this case?
