### ISSUE TITLE
onFail function when no tenant is found for a given domain/subdomain.

### ISSUE THREAD

**Issue by andelwebsolutions** [spatie/laravel-multitenancy#391]
### Discussed in https://github.com/spatie/laravel-multitenancy/discussions/390

<div type='discussions-op-text'>

<sup>Originally posted by **andelwebsolutions** September  5, 2022</sup>
Hi, I would like to request a feature to redirect to a "main" domain/website (a marketing website for example) if no tenant is found for a given (sub-)domain.

Currenlty this is not possible I believe. Preferably this would be a "onFail" function that we could implement on our TenantFinder class to redirect the user (or do something else).</div>

**Comment by masterix21** [comment]
Can't you use a custom finder to handle it?

**Comment by jorisvanandel** [comment]
> Can't you use a custom finder to handle it?

I don't believe so. The "findForRequest()" method should return an optional Tenant, not a RedirectResponse.

**Comment by andelwebsolutions** [comment]
Ok so I fixed this with an abort statement that receives a redirect.

See my findForRequest() implementation below, maybe it will help someone.

```
    public function findForRequest(Request $request): ?Tenant
    {
        $host = $request->getHost();

        list($subDomain) = explode('.', $host, 2);

        if (! $tenant = $this->getTenantModel()::whereDomain($subDomain)->first()) {
            abort(redirect('{{ MARKETING_WEBSITE_URL }}'));
        }

        return $tenant;
    }
```
