### ISSUE TITLE
Custom Tenant model not working due to type safety

### ISSUE THREAD

**Issue by jellingsen** [spatie/laravel-multitenancy#398]
I'm running into a problem when using a custom Tenant model.

PHP: 8.1
Larvel: 9.24.0
MultiTenancy: 2.3.8

When I almost any built-in function for tenants i get the following error:

`Argument #1 ($tenant) must be of type Spatie\Multitenancy\Models\Tenant, App\Models\Tenant given`

I've updated the config file to use the custom model.

Example:
```
Tenant::all()->eachCurrent(function(Tenant $tenant) {
    // the passed tenant has been made current
    $this->line(Tenant::current()->is($tenant) ? $tenant->name . ' is current' : $tenant->name . 'failed'); // returns true;
});
```

**Comment by riasvdv** [comment]
Make sure your custom Tenants models extends from the base package Tenant model.

**Comment by HijenHEK** [comment]
@riasvdv , even with extending the base package its not working here , custom interface causes type safety errors too.
