### ISSUE TITLE
i have problem when run php artisan

### ISSUE THREAD

**Issue by MostafaDev12** [spatie/laravel-multitenancy#414]
Target [Spatie\Multitenancy\Tasks\SwitchTenantTask] is not instantiable while building [Spatie\Multitenancy\Actions\MakeTenantCurrentAction].

**Comment by masterix21** [comment]
Please post an example of your code :)

**Comment by MostafaDev12** [comment]
i fixed this was interface and u was use it like class 
i got other problem 

SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected 

app.php



 'default' => 'tenant',
 
 
    'tenant' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => null,
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => false,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],
        
        
         'landlord' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
          //  'database' => env('DB_DATABASE', 'vooerp_landlord'),
            'database' => 'vooerp_landlord',
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => false,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],
        
        
        
        
        
        but i think error from this page 
        Spatie\Multitenancy\Actions\MakeTenantCurrentAction.php
        
        
        
        <?php

namespace Spatie\Multitenancy\Actions;

use Spatie\Multitenancy\Events\MadeTenantCurrentEvent;
use Spatie\Multitenancy\Events\MakingTenantCurrentEvent;
use Spatie\Multitenancy\Models\Tenant;
use Spatie\Multitenancy\Tasks\SwitchTenantTask;
use Spatie\Multitenancy\Tasks\TasksCollection;

class MakeTenantCurrentAction 
{
    protected  $tasksCollection;



    public function __construct(TasksCollection $tasksCollection)
    {
        $this->tasksCollection = $tasksCollection;
    }


    
    
    public function execute(Tenant $tenant)
    {
        event(new MakingTenantCurrentEvent($tenant));

        $this
            ->performTasksToMakeTenantCurrent($tenant)
            ->bindAsCurrentTenant($tenant);

        event(new MadeTenantCurrentEvent($tenant));

        return $this;
    }

    protected function performTasksToMakeTenantCurrent(Tenant $tenant): self
    {
        
      // i get error here from this arrow function 
     
     //    $this->tasksCollection->each(fn (SwitchTenantTask $task) => $task->makeCurrent($tenant));
         
        $this->tasksCollection;

        return $this;
    }

    protected function bindAsCurrentTenant(Tenant $tenant): self
    {
        $containerKey = config('multitenancy.current_tenant_container_key');

        app()->forgetInstance($containerKey);

        app()->instance($containerKey, $tenant);

        return $this;
    }
}

**Comment by MostafaDev12** [comment]
php artisan tenants:cache:clear --tenant=1
php artisan tenants:artisan cache:clear --tenant=1
php artisan tenants:artisan optimize --tenant=1
php artisan tenants:optimize --tenant=1
php artisan tenants:optimize

all same error
how i can use command right way
