### ISSUE TITLE
Cache cleared for all tenants instead of current tenant

### ISSUE THREAD

**Issue by hanicab** [spatie/laravel-multitenancy#419]
Hello,

When I execute the code bellow, the cache is cleared for all tenants instead of the current tenant.

`$tenant->execute(fn(Tenant $tenant) => cache()->flush()); `

is this normal ?

My configuration :
laravel-multitenancy v3
Laravel v9
PHP 8.1

I use the default task \Spatie\Multitenancy\Tasks\PrefixCacheTask::class
default cache prefix : "my_app_"

Best regards

**Comment by masterix21** [comment]
From: https://laravel.com/docs/9.x/cache

> Flushing the cache does not respect your configured cache "prefix" and will remove all entries from the cache. Consider this carefully when clearing a cache which is shared by other applications.
