### ISSUE TITLE
Current tenant model not refreshed in container before each job (stale model properties)

### ISSUE THREAD

**Issue by ionutantohi** [spatie/laravel-multitenancy#422]
When a tenant is made current, there is a check to see if tenant we want to make current is already loaded. 

<img width="354" alt="image" src="https://user-images.githubusercontent.com/4609521/205852368-75c1586c-c5e8-47f1-a311-8175ff4544a1.png">

While this somehow makes sense, it **might** cause an issue in jobs, because jobs are processed by **long running processes**.

There was a back and forth around this check. Initially was added in #111 then removed in #115 and added back in 85c4e5c111c400f0db849302d56c22fbac21e9ce (cc @masterix21)

@telkins you asked in your pr #111 whether or not is a good idea. Let me give you an example.

Say we have the following tenant
id: 1
name: My tenant
**stripe_plan_id: abc**

Now, if we dispatch a job, for this tenant, then
- the worker will pick up the job
- there is no current tenant, then the tenant made current (loaded into container)
- job is processed

**Now, let's say that some info at tenant level are changed (by an user in his account etc)**

**stripe_plan_id: xyz**

When a second job is dispatched for the same tenant
- the worker will pick the job
- but since a tenant is already loaded into container and is the same (by looking at its id) it just returns early. But that means when calling `Tenant::current` inside the job, on second job `stripe_plan_id` is still `abc`. 

Note: The tenant is queried every time and before each job in `MakeQueueTenantAwareAction@listenForJobsBeingProcessed` but the object returned by `findTenant` (fresh from db) is never set to container because of id match.

Possible workarounds?
- remove the `isCurrent` check entirely, but I am not sure if that's ok. 
- update `isCurrent` check to also look at the tenant/model properties and return true only if all model properties are identical
- introduce a `forceMakeCurrent` method which should be called from `MakeQueueTenantAwareAction` which should bypass `isCurrent` check
- other?

**Comment by masterix21** [comment]
Hi @ionutantohi, please create a repository to test the issue. Thanks

**Comment by masterix21** [comment]
@freekmurze, one fix to this issue is to change the `MakeQueueTenantAwareAction.php` like so:

```php
class MakeQueueTenantAwareAction
{
    /// ...

    protected function listenForJobsBeingProcessed(): static
    {
        app('events')->listen(JobProcessing::class, function (JobProcessing $event) {
            $this->getTenantModel()::forgetCurrent();

            if (array_key_exists('tenantId', $event->job->payload())) {
                $this->findTenant($event)->makeCurrent();
            }
        });

        return $this;
    }

    protected function listenForJobsRetryRequested(): static
    {
        app('events')->listen(JobRetryRequested::class, function (JobRetryRequested $event) {
            $this->getTenantModel()::forgetCurrent();

            if (array_key_exists('tenantId', $event->payload())) {
                $this->findTenant($event)->makeCurrent();
            }
        });

        return $this;
    }

    /// ...
}
```

What do you think about?

**Comment by masterix21** [comment]
@ionutantohi: PR's merge is on the way to fixing the issue. I'll keep you in the loop.

**Comment by masterix21** [comment]
@ionutantohi issue fixed by 3.0.2. Thanks for your time on it.

**Comment by ionutantohi** [comment]
Thanks @masterix21. I confirm it works as expected on 3.0.2

**Comment by moisish** [comment]
The fix on 3.0.2 has created a breaking change. I think this should not be solved as per 3.0.2 and you should refresh your tenant on your job to make sure you get the latest information from the database in the case of tenant changes

**Comment by moisish** [comment]
```When a second job is dispatched for the same tenant the worker will pick the job but since a tenant is already loaded into container```

On the second job the framework will boot again which means the container does not have anything loaded. Is my understanding wrong?

**Comment by ionutantohi** [comment]
No, the framework will not boot again before each job.

The framework is booted once, when `php artisan queue:work` process/worker starts. Then all jobs executed by this worker are handled on the same framework instance. That's why you need to restart your workers after each code change

<img width="669" alt="image" src="https://user-images.githubusercontent.com/4609521/221799562-367edcfb-db66-4d41-ada9-13e315f9cf6b.png">

**Comment by moisish** [comment]
Right, makes sense.

The solution produced a breaking change. Can you check my proposed solution on the comment bellow ? 

https://github.com/spatie/laravel-multitenancy/pull/438#issuecomment-1447755235
https://github.com/spatie/laravel-multitenancy/issues/446
https://github.com/spatie/laravel-multitenancy/issues/444

**Comment by masterix21** [comment]
Try again with the release 3.0.3. Thanks!
