### ISSUE TITLE
The "--path" option does not exist.

### ISSUE THREAD

**Issue by MostafaDev12** [spatie/laravel-multitenancy#423]
everything work fine 

but when i use

 \Artisan::call("tenants:artisan migrate --path=database/migrations/tenant  --tenant=1"); 

i get this error 
The "--path" option does not exist.

when i use this one it work 
 \Artisan::call("tenants:artisan migrate  --tenant=1"); 
but use --path  or --database 

i get error 

 Symfony \ Component \ Console \ Exception \ RuntimeException
The "--path" option does not exist.

 Symfony \ Component \ Console \ Exception \ RuntimeException
The "--database " option does not exist.

**Comment by masterix21** [comment]
Replace with:
```php
\Artisan::call('tenants:artisan', [
    'artisanCommand' => 'migrate --path=database/migrations/tenant',
    '--tenant' => 1, 
]);
```

Please give us a feedback. Thanks!

**Comment by masterix21** [comment]
I'm closing here because the issue isn't related to the package, but feel free to reply. Thanks
