### ISSUE TITLE
Can't force CommentNotificationSubscription class to use Tenant connection when using Multitenancy?

### ISSUE THREAD

**Issue by dambridge** [spatie/laravel-multitenancy#428]
I'm using Spatie Laravel Comments, and have extended the Comment and Reaction models to account for the Tenant connection. However, when trying to do the same with CommentNotificationSubscription, I get the following error when loading the component:

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'landlord.comment_notification_subscriptions' doesn't exist` which shows it's still using the **default** landlord connection.

My extended model for the class is:

```php
class MyCommentNotificationSubscription extends CommentNotificationSubscription
{
    use HasFactory;
    use UsesTenantConnection;

    protected $table = 'comment_notification_subscriptions';
}
```

In my `multitenancy` config:
```php
'tenant_aware_jobs' => [
        SendNotificationsForApprovedCommentJob::class,
        SendNotificationsForPendingCommentAction::class,
    ],
```

**Comment by dambridge** [comment]
(bump) any thoughts on this thus far? i'm stuck and making no progress :(

**Comment by masterix21** [comment]
Hi @dambridge. Have you changed the `'comment_notification_subscription' => CommentNotificationSubscription::class,` in the `comments.php` config file?

**Comment by dambridge** [comment]
> Hi @dambridge. Have you changed the `'comment_notification_subscription' => CommentNotificationSubscription::class,` in the `comments.php` config file?

Yes, I have.

**Comment by masterix21** [comment]
@dambridge please take a look here https://github.com/spatie/laravel-multitenancy/issues/429#issuecomment-1419875296

I think the issues are related, but I'm not sure: please keep me updated. Thanks!
