### ISSUE TITLE
Queue driver 'sync' generates "Call to a member function prepare() on null"

### ISSUE THREAD

**Issue by Libero-Software** [spatie/laravel-multitenancy#444]
Laravel 10
Jetstream / Sanctum / Scout / Socialite
Laravel Multi Tenancy / Permission /  Activity Log / Media library Pro / Query Builder

When calling a job with the `queue_driver=sync` the following error is thrown: `Call to a member function prepare() on null`. The PDO is null. It looks like it doesnt know which (tenant) connection to use.

When changing session driver to: `file`, it works. But this is not an option.

When changing the queue driver to `redis`, the problem is solved.

In `multitenancy.php` the `queues_are_tenant_aware_by_default` is set to `true`. Also defining the jobs in the `tenant_aware_jobs` array does not work with driver 'sync'.

Are the session_driver and the queues related? (For example, when using `session_driver=file`, is the tenant connection saved in this session file?). 

Summary:
- When using `sync queue` with `session file` it works. (but not an option)
- When using `sync queue` with `session database` it **fails**
- When using `sync redis` with `session database` it works.

Is this behaviour to be expected? Or is there something wrong in my application (settings).

**Comment by masterix21** [comment]
Take a look here: https://github.com/spatie/laravel-multitenancy/issues/442

Please add me to your repository: I will help you.

**Comment by masterix21** [comment]
Try to create your own `SwitchDatabaseTask` like so:

```php
class SwitchDatabaseTask implements SwitchTenantTask
{
    use UsesMultitenancyConfig;

    protected ?string $originalDefaultConnection;

    protected ?array $originalTenantDatabase;

    public function makeCurrent(Tenant $tenant): void
    {
        $this->originalDefaultConnection = config('database.default');
        $this->originalTenantDatabase = config('database.connections.tenant.database');

        $this->setup($tenant);
    }

    private function setup(Tenant $tenant)
    {
        config()->set([
            'database.default' => $this->tenantDatabaseConnectionName(),
            'database.connections.tenant.database' => $tenant->database,
        ]);

        DB::purge($this->tenantDatabaseConnectionName());
    }

    public function forgetCurrent(): void
    {
        config([
            'database.default' => $this->originalDefaultConnection,
            'database.connections.tenant.database' => $this->originalTenantDatabase,
        ]);

        DB::purge($this->tenantDatabaseConnectionName());
    }
}
```

Give me a feedback. Thanks
