### ISSUE TITLE
syntax error, unexpected 'TasksCollection' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by ojha007** [spatie/laravel-multitenancy#45]
i am getting unexcepted issue from \vendor\spatie\laravel-multitenancy\src\Actions\MakeTenantCurrentAction.php:13

Laravel Framework 7.12.0
PHP 7.4.7

**Comment by freekmurze** [comment]
The package doesn't contain a syntax error. You don't have PHP 7.4 to handle your web requests or cli executions.

**Comment by ojha007** [comment]
PHP 7.4.7 (cli) (built: Jun  9 2020 13:36:15) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

**Comment by freekmurze** [comment]
https://freek.dev/1598-how-to-check-which-version-of-php-you-are-running

**Comment by ojha007** [comment]
i do have php 7.4 
![demo-11](https://user-images.githubusercontent.com/34395682/84517418-0177a180-acef-11ea-80ed-0156291d3ec0.PNG)

**Comment by freekmurze** [comment]
Did you check both methods mentioned in the blogpost?
