### ISSUE TITLE
Support for custom primary key on Tenant model

### ISSUE THREAD

**Issue by yitznewton** [spatie/laravel-multitenancy#457]
Greetings, and thank you for your wonderful project.

I am using the package in a Laravel app built on top of a legacy project's database, so the tenant table already existed with its columns named a particular way. Most things worked with normal configuration adjustments; however, there are places in the package code which assume that the primary key of the tenant model is `id`, such as:

https://github.com/spatie/laravel-multitenancy/blob/e7dbf0dcd99cf15a5510764cda8a6558d64ae308/src/Actions/MakeQueueTenantAwareAction.php#L35

This is not the only such example. I was able to make it work by supplying my model with a `getIdAttribute()` method which delegates to my primary key, but it seems to me the better solution would be changing the package code to reference the key abstractly, such as using Eloquent's `Model::getKey()` method::

```php
return ['tenantId' => Tenant::current()?->getKey()]; 
```

Would you be amenable to this change? And can you suggest a strategy for designing the tests? My initial thought was to create a new tenant table with customized names, but since there would be a significant amount of setup to support that, I wanted to confirm before doing that work.

**Comment by masterix21** [comment]
Hi @yitznewton, a PR is welcome: feel free to do it.
