### ISSUE TITLE
Tenant Not Set (Vapor + Octane)

### ISSUE THREAD

**Issue by Carlwirkus** [spatie/laravel-multitenancy#466]
From what I understand, when you run use octane with laravel vapor, the application is running in a CLI environment because of the swoole client. The TenantFinder class is never called because of the `runningInConsole()` check. I would imagine this is not intentional?  

My workaround has just been to set the tenant via middleware.  Is there any reason the tenant isn't set via middleware in the first place?

Is there a better check that could be done here to determine if the application is running in the console & not being served by the swoole client?

```php
//vendor/spatie/laravel-multitenancy/src/Multitenancy.php

    protected function configureRequests(): self
    {
        if (! $this->app->runningInConsole()) {
            $this->determineCurrentTenant();
        }

        return $this;
    }
```

**Comment by masterix21** [comment]
Hi, I can't help you because I'm not using Vapor with Octane, but I'm sure that the package works with Octane only. I'm closing here, but feel free to keep us updated.
