### ISSUE TITLE
When dispatching a Tenant Aware Job in sync mode from a test, any prior/current DB transaction is cleared

### ISSUE THREAD

**Issue by peterabarry** [spatie/laravel-multitenancy#476]
We have extensive use of the plugin and of tests and of Jobs.

We encountered a regression which affects unit testing but not production ( because we only us sync in unit tests). 

The basic flow is:
* Start a transaction and do some work in normal tenant aware work in a web process
* Dispatch a job to do some background work ( but in test this will run sync ) 
* The event handling classes in multitenancy.php will always clear the current tenant ( even if the the job is sync and the tenant is already the same one bound) this clearing also appears to reset / clear DB state in the current transaction ( which does make sense for security when clearing tenant).

The issue basically is that if in sync mode the plugin should check if the current tenant  connection is already the same one the sync job wants and if it is it should not clear the existing one. 

I have not yet written a repro that is clear for you and I see some other potential dupes but not yet sure if they are dupes.

The change I made temporarily to test the fix which does fix the issue is:

![image](https://github.com/spatie/laravel-multitenancy/assets/963982/17da895f-531f-4c08-bbf4-800d73232f07)

**Comment by masterix21** [comment]
Try again with the release 3.0.3. Thanks!

**Comment by masterix21** [comment]
I wanted to let you know that I'm closing here due to inactivity. Feel free to continue the discussion if the issue still exists. Thanks.
