### ISSUE TITLE
Database alternative

### ISSUE THREAD

**Issue by benrolfe** [spatie/laravel-multitenancy#48]
Rather than using this code to lookup a row from a database table:

`return $this->getTenantModel()::whereDomain($host)->first();`

...is it possible to populate the model manually? My use case is that I have multiple tenant config files which I would prefer to use. _Ie: '`config/tenants/nike.php`', '`config/tenants/apple.php`'._

For example:

`return config('tenants.' . $host);`

**Comment by freekmurze** [comment]
You can use a custom tenant finder

https://docs.spatie.be/laravel-multitenancy/v1/basic-usage/automatically-determining-the-current-tenant/
