### ISSUE TITLE
where can i store my configuration ? 

### ISSUE THREAD

**Issue by ojha007** [spatie/laravel-multitenancy#49]
i got stuck in a suiation where i need set different configuration to different tenant 
so where can i keep those configuration . should i add colum on tenants table or make new table on landlord db.

**Comment by masterix21** [comment]
There are a lot of ways to solve your problem, but these depend on your approach. All your ideas are valid but aren't dependents by the Spatie package.

You can use a Config model in the tenant database, or you can write storage/tenants/{your-tenant-id}/config.php. Make your choice.
