### ISSUE TITLE
Update documentation at https://spatie.be to `v3`

### ISSUE THREAD

**Issue by josecl** [spatie/laravel-multitenancy#510]
The installation process of https://spatie.be/docs/laravel-multitenancy is failing.

It shows the documentation for `v1` instead of the current `v3`.

**Comment by freekmurze** [comment]
Should be back now, thanks for reporting 👍

**Comment by josecl** [comment]
Last week it was fixed,
but now https://spatie.be/docs/laravel-multitenancy is using `v2` docs instead `v3`.

**Comment by freekmurze** [comment]
Back now, it seems that there's some memory issue with our docs import script. I hope I can track it down soon.
