### ISSUE TITLE
Issue with the has function on different connections

### ISSUE THREAD

**Issue by PittacusW** [spatie/laravel-multitenancy#525]
Hello,

I have two models, one on landlord connection, one in the tenant connection. These models are related with the hasMany relationship.

On the parent model, i have this function:

```php
public function childs() {
    return $this->hasMany(Child::class);
  }
```

Now, on the controller, i call this:

```php
public function list() {
    $records = Parent::has('childs')
                            ->orderBy('code')
                            ->get();

    return response()->json(compact('records'));
  }
```

But the query throws an error because it tries to find "childs" on the same connection as "parent". Is there a workaround this?

**Comment by masterix21** [comment]
Relations between landlords and tenants aren't available. You can retrieve children only when your tenant is already configured as current, so:

```php
Parent::first()->execute(function (Parent $parent) {
      $children = $parent->children()->orderBy('code')->get();
});
```
