### ISSUE TITLE
Custom Tenant Finder using authenticated user

### ISSUE THREAD

**Issue by henryavila** [spatie/laravel-multitenancy#53]
Hi.
In my case, The Tenant is linked to User and not to domain (All tenants will access the app from the same domain).
But when I run `Auth::user()` in `TenantFinder@findForRequest` I always get null.

How can I access The authenticated user inside TenantFinder?

**Comment by masterix21** [comment]
Skip the finder and add two listeners for these events:
- Illuminate\Auth\Events\Login
- Illuminate\Auth\Events\Logout

When the login event will be fired, do your $tenant->makeCurrent(), and when the logout event will be fired, do your $tenant->forgot().

I think it’s better for you, try and give me feedback.

**Comment by sandulat** [comment]
@masterix21 If I do the `$tenant->makeCurrent()` in the login event listener, the tenant is being set, however, after I'm redirected, it is not being persisted and it becomes null. Is there any step that I'm missing? Or is this something on my side?

**Comment by masterix21** [comment]
If you call `request()->auth()` before the StartSession middleware, you'll get `null` always. I can suggest using another approach: instead of work with a Finder, write a middleware (in web, after StartSession) to find your tenant. It will work.

**Comment by masterix21** [comment]
Last but not least, add a listener to `Illuminate\Auth\Events\Authenticated` event... it's another solution ;)

**Comment by henryavila** [comment]
Just to register, the middleware approach gave me the needed flexibility. Worked perfectly.
I set the tenant before the `return $next($request);`

**Comment by dambridge** [comment]
Sorry for the necro bump, just curious to see what you ended up doing. I too want to abandon the whole subdomain thing and ultimately be able to attach users to multiple tenants. 

Question: if we just check for a tenant id in middleware, are we not losing some part of the identification pipeline this package needs?

**Comment by masterix21** [comment]
@dambridge, the package works if you set a tenant "as current": it does not care if you do it from a middleware or from a task.
