### ISSUE TITLE
Custom cache driver missing when switching Tenant

### ISSUE THREAD

**Issue by markieo1** [spatie/laravel-multitenancy#533]
Hi,

We are using Laravel Octane.
Now we want to start using the [Laravel Octane Cache](https://laravel.com/docs/11.x/octane#the-octane-cache). 
This can be done by for example putting the following code in `cache.php`:
```php
'octane' => [
    'driver' => 'octane',
]
```
And in the controller:
```php
Cache::store('octane')->put('framework', 'Laravel', 30);
```

When you do this, the following error happens:
```
Cache store [octane] is not defined.
```

In the `OctaneServiceProvider` this driver/store is added on boot. 
```php
    protected function registerCacheDriver()
    {
        if (empty($this->app['config']['octane.cache'])) {
            return;
        }


        $store = $this->app->bound('octane.cacheTable')
                        ? new OctaneStore($this->app['octane.cacheTable'])
                        : new OctaneArrayStore;


        Event::listen(TickReceived::class, fn () => $store->refreshIntervalCaches());


        Cache::extend('octane', fn () => Cache::repository($store));
    }
```
from: [OctaneServiceProvider.php](https://github.com/laravel/octane/blob/a5dc6c1aa747fc4e8f3d471c5658d9b6a23f6660/src/OctaneServiceProvider.php#L160-L173)

This is only done on boot of the application. In the [PrefixCacheTask.php](https://github.com/spatie/laravel-multitenancy/blob/main/src/Tasks/PrefixCacheTask.php) in the method `setCachePrefix` the whole instance of the `cache` is cleared. This causes the `OctaneStore`/`OctaneArrayStore` to be forgotten.

When we do this in `php artisan tinker`, not `tenants:artisan` the issue is not happening. Then we are able to use the above code and use the Octane Cache store.

I expect the `Octane` cache store to be available even when switching tenants.

**Comment by masterix21** [comment]
Please post a demo repo to test the issue.

**Comment by markieo1** [comment]
This issue is still not resolved.
