### ISSUE TITLE
Problem to install in Laravel 11

### ISSUE THREAD

**Issue by wagnerbugs** [spatie/laravel-multitenancy#546]
When I try to run the command  after install laravel (`composer create-project laravel/laravel tenant`)

`composer require "spatie/laravel-multitenancy:^3.0"`

return

Problem 1
    - Root composer.json requires spatie/laravel-multitenancy 3.0 -> satisfiable by spatie/laravel-multitenancy[3.0.0].
    - spatie/laravel-multitenancy 3.0.0 requires illuminate/support ^9.0|^8.0 -> found illuminate/support[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    
What am I doing wrong?

**Comment by masterix21** [comment]
A package conflict. This is not an issue, I'm closing here.
