### ISSUE TITLE
Decouple domain from logic

### ISSUE THREAD

**Issue by eightfivelabs** [spatie/laravel-multitenancy#55]
Thanks for your work on the package.

The base package seems to be slightly coupled to a domain based tenant e.g. `tenant.domain.com` in that the initial landlord migration creates a column called `domain`. It is easy enough for the user to change the tenant identification logic from `getHost()` and change the migration to rename the landlord table identification column to `tenant_identifier` (or something similar), but wonder if the change to the column name should be made in this base package?

Thanks

**Comment by masterix21** [comment]
It seems a customization and not a package related issue. You have the tenant_identifier, and I have ”host” and a table called ”domains”.

So, isn’t possible to create a package for all, and I think that Spatie worked over a package customizable by all.
