### ISSUE TITLE
NeedsTenant with route model binding

### ISSUE THREAD

**Issue by jetapps-team** [spatie/laravel-multitenancy#550]
I would expect that checking the existence of the tenant would be before trying to pull data from the DB
Unfortunately, the check is performed after binding the route model, and if I'm in the main application I'll get a SQL error instead of a NoCurrentTenant error

**Comment by masterix21** [comment]
Please explain better your issue with an example. Thanks

**Comment by michaelklopf** [comment]
I just came across the - I think - same problem. You have a route like this

```php
        Route::get(
            '{tenant}/documents/{document}',
            DocumentPage::class
        );
```

And a Livewire component with a mount like this

```php
    public function mount(Document $document)
    {
        $this->document = $document;
    }
```

which results in the error

```
SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected (Connection: tenant, SQL: select * from `documents` where `id` = 16 limit 1)
```

This should be the same for a controller function, but I didn't test that case. Is it possible to get route model binding while using this package?

**Comment by masterix21** [comment]
Do you use our tenant middleware in your route?

**Comment by michaelklopf** [comment]
Yes I do

```php
    Route::middleware(['tenant'])->group(function () {
        Route::get(
            '{tenant}/documents/{document}',
            DocumentPage::class
        );
    });
```
