### ISSUE TITLE
Spatie\Multitenancy\Concerns\UsesMultitenancyConfig should be moved to ImplementsTenant?

### ISSUE THREAD

**Issue by thumbtech** [spatie/laravel-multitenancy#551]
Due to `$this->getMultitenancyActionClass` in ImplementsTenant trait, `Spatie\Multitenancy\Concerns\UsesMultitenancyConfig` is always necessary if `makeCurrent()` is called.

HOWEVER `Spatie\Multitenancy\Concerns\UsesMultitenancyConfig` is currently only called for by either UsesLandlordConnection or UsesTenantConnection traits.

Shouldn't `use UsesMultitenancyConfig` be moved directly into ImplementsTenant (and removed from UsesLandlordConnection and UsesTenantConnection) so that those connection traits can remain optional (and config values left null)?

IOW UsesLandlordConnection or UsesTenantConnection trait is currently a dependency for ImplementsTenant trait, when it seems like it should be the other way round?

**Comment by masterix21** [comment]
Hi @thumbtech.

`ImplementtsTenant` is used when your model implements the tenant features. `UsesTenantConnection` is used when your models use the tenant connection. So, why should we remove it? I don't understand. 

I'm closing here because this is not an issue.

Thanks.

**Comment by thumbtech** [comment]
Well, when in tenant model we have

```
use ImplementsTenant;
```

WITHOUT

```
use UsesLandlordConnection;
```

an error is thrown with makeCurrent() in ImplementsTenant trait ...

ImplementsTenant trait depends on UsesLandlordConnection trait because 

```
use UsesMultitenancyConfig;
```

NOT in ImplementsTenant

Is this dependency necessary? In my app I have no need for UsesLandlordConnection trait, and in config want to keep

```
'landlord_database_connection_name' => null,
```
