### ISSUE TITLE
Session store not set on request

### ISSUE THREAD

**Issue by sbc640964** [spatie/laravel-multitenancy#556]
Hi

I use with EnsureValidTenantSession middleware on api routes
and laravel throws error "Session store not set on request".

I see this, because the API request (with sanctom tokens) does'nt store the session in requests.

and EnsureValidTenantSession file contains this: `$request->session()` in line: 17 and more

**Comment by masterix21** [comment]
Hi @sbc640964.

Your message has the answer: remove the EnsureValidTenantSession from the API because your token guarantees the tenant.

**Comment by sbc640964** [comment]
@masterix21, I mean the route that has a tenant (subdomain)

**Comment by masterix21** [comment]
Please explain better your issue. Thanks
