### ISSUE TITLE
Handling multiple databases with different database user

### ISSUE THREAD

**Issue by TheAdnan** [spatie/laravel-multitenancy#563]
I have two tenants that use two different databases, and each database has its own dedicated user. How can I set the `DB_USERNAME` to be dynamic, like `DB_DATABASE`?

**Comment by mateusztumatek** [comment]
Probably you can extend `Spatie\Multitenancy\Models\Tenant` with your own implementation that will also include db_username field in this table.

Than you have to also extend `SwitchTenantDatabaseTask` to change also database user name.  Remember to keep null in config/database.php in tenant configuration to all fields that are dynamic.
