### ISSUE TITLE
Tenant Aware Queues - No database selected

### ISSUE THREAD

**Issue by moisish** [spatie/laravel-multitenancy#564]
I have this very odd issue where I cannot reproduce with all of my queue notifications.

The issue exists on 4.0.1 and 4.0.2 but not on version 4.0.0

https://github.com/spatie/laravel-multitenancy/compare/4.0.0...4.0.2

```

PDOException: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:407
--
```

I am trying to investigate and pinpoint the issue with the possibility of a PR to fix it.

**Comment by moisish** [comment]
Using redis with horizon

**Comment by masterix21** [comment]
@moisish, I have closed the issue because there is no information on how to debug it. If you can create a repository with all instructions to catch the problem, I can re-open it. 

Thanks
