### ISSUE TITLE
Failed to install the package

### ISSUE THREAD

**Issue by onemoreahmad** [spatie/laravel-multitenancy#6]
Hi, I'm not sure if the package is ready or not yet, but I'm trying to install it and it failed, here are some screenshots. Thanks.

<img width="879" alt="Screen Shot 2020-05-13 at 5 56 59 PM" src="https://user-images.githubusercontent.com/1885785/81829354-7a92a600-9543-11ea-8fe6-3cff34bdb8c0.png">
<img width="1392" alt="Screen Shot 2020-05-13 at 5 57 49 PM" src="https://user-images.githubusercontent.com/1885785/81829373-7f575a00-9543-11ea-8233-4752c5537208.png">

**Comment by freekmurze** [comment]
There is no 1.0 tagged yet
