### ISSUE TITLE
Switch the tenant on the same domain

### ISSUE THREAD

**Issue by sandulat** [spatie/laravel-multitenancy#61]
Hello!

I'm building an app that will be accessible for users from a single domain. A user can access multiple tenants.

How would you switch the tenant on the session level? 

I've tried to manually store the tenant id in the session, when the `MadeTenantCurrentEvent` is fired. I've created a custom `TenantFinder` that would read this id from the session and detect the tenant. However, the session is not yet initialized when my custom `TenantFinder` is being executed, and I am not able to read the id from the session.

I believe that it's linked to https://github.com/spatie/laravel-multitenancy/issues/53.

Thank you very much!

**Comment by masterix21** [comment]
Hi Sandulat, 

could be a solution to use the path as tenant finder?

Ex.
https://your-domain.test/tenant1/
https://your-domain.test/tenant2/
https://your-domain.test/tenantN/
...

**Comment by sandulat** [comment]
@masterix21 In fact, this was the only solution I could figure out. It solves my requirement and doesn't introduce the unnecessary (in my case) "subdomain" complexity. Thank you very much!
