### ISSUE TITLE
New tenant registration + Passport

### ISSUE THREAD

**Issue by dambridge** [spatie/laravel-multitenancy#62]
As discussed in #29 I have likely a simple question. When registering a new tenant, should we be calling `php artisan passport:install` each time to generate keys and clients as part of the initilization?

**Comment by masterix21** [comment]
Hi @dambridge, it's logic dependent. 

If you have a separated users logic tenant by tenant, I can suggest to call `php artisan tenants:artisan "passport:install"`.

If your users logic is included in your landlord, it isn't needed.

**Comment by dambridge** [comment]
@masterix21 In my registration handler, I'm basically going to do this then:

```
Artisan::call('tenants:artisan "migrate --seed" --tenant=' . $this->tenant->id);
Artisan::call('php artisan passport:install');
```

**Comment by masterix21** [comment]
Yes, it seems ok What are your concerns?

**Comment by dambridge** [comment]
Per #23 , there are issues I had running Artisan directly.

Also, I just tried it but the Passport tables were still installed in the landlord database.

**Comment by masterix21** [comment]
Have you moved the passport migrations inside the tenant directory?

**Comment by dambridge** [comment]
Yes. Well, the default migrations folder is the tenant directory, so that's where they are. Must be using the wrong connection somehow, but the other migrate command runs just fine.

**Comment by dambridge** [comment]
Ah, hold up. This is the culprit methinks (in the default Passport migrations):

```
public function getConnection()
    {
        return config('passport.storage.database.connection');
    }
```

**Comment by masterix21** [comment]
Change it:
exec('cd ' . base_path() . ' && php artisan tenants:artisan "migrate --seed" --tenant=' . $tenant->id);

with:
exec('cd ' . base_path() . ' && php artisan tenants:artisan "migrate --seed --connection=tenant" --tenant=' . $tenant->id);

**Comment by dambridge** [comment]
I published the Passport config and set the connection to 'tenant', migrations ran properly. However, NOW I'm getting an error when trying to create a token for the user:

`Class 'App\Tasks\PersonalAccessClientTenantAware' not found`

when trying

`$token = $user->createToken('Troovy API')->accessToken;`

**Comment by dambridge** [comment]
Oh God. Nothing to see here. Forgot to import classes. Thanks @masterix21 .
