### ISSUE TITLE
Best practices for Passport and MultiTenancy

### ISSUE THREAD

**Issue by dambridge** [spatie/laravel-multitenancy#63]
First off, I hope I have not become an annoyance in here! I have created a Chrome extension that originally leveraged password grant authentication and a standard URL to authenticate. Now, with subdomain-based tenants, I'm not clear on what the best approach might be. 

I am trying to require a user to only have to provide email and password when logging in via the extension; however, without knowing the subdomain or manually entering it, I'm hitting a wall on how to determine which tenant this user belongs to and, indeed, switching the db connection to that tenant as well.

Again, apologies if this is noise in here, just wondering if someone else is dealing with this. I realize it's out of scope for the package itself.

**Comment by dambridge** [comment]
In my current implementation, when registering users, I add a record in the Landlord database as well, as I wanted a quick way to see the entire user base of the app somewhere. I could change my setup so that Passport installs in the Landlord db instead of Tenant, associate a token request with the user's tenant, and go from there. The only issue I see there now is that my original desire to allow users to join multiple tenants would no longer be a thing.

**Comment by masterix21** [comment]
Create a relationship between tenant and user inside your landlord database. 

Next, if you create a login in your landlord website, it could be valid for all your subdomains (if your cookie is valid). 

What are the problems?

**Comment by freekmurze** [comment]
Closing this as this is not an issue with the internals of the package.

Feel free to keep the conversion going.
