### ISSUE TITLE
Generating route using route()

### ISSUE THREAD

**Issue by ivalkenburg** [spatie/laravel-multitenancy#65]
When generating routes using route() helper inside a queued job or mail, it will generate the non scoped route. For example: tenant is acme with the domain acme.localhost and I will send a user a password recovery email implementing ShouldQueue with a link inside the mail/notification using the route helper function. The route helper will actually return the route using the root domain (localhost) instead of acme.localhost because of how the routes are setup. 

So my question is if there is any elegant way to handle this problem without having to write my own UrlGenerator implementation and instead use a switch task?

**Comment by masterix21** [comment]
Hi @ivalkenburg,

you need a task that switch your URL. Try with it:
```php
class SwitchRouteUrlTask implements SwitchTenantTask
{
    private $originalUrl;

    public function makeCurrent(Tenant $tenant): void
    {
        $this->originalUrl = config('app.url');

        $protocol = Str::before($this->originalUrl, '://');

        Config::set('app.url', "{$protocol}://{$tenant->domain}");
        URL::forceRootUrl(config('app.url'));
    }

    public function forgetCurrent(): void
    {
        Config::set('app.url', $this->originalUrl);
    }
}
```

**Comment by ivalkenburg** [comment]
Thanks, this seems to work great.

**Comment by masterix21** [comment]
@ivalkenburg ok, if the problem has been solved, please close the issue. Thanks :)
