### ISSUE TITLE
Static functions and DB Facade

### ISSUE THREAD

**Issue by josiahmann** [spatie/laravel-multitenancy#67]
Hey team,

Loving the package so far.

Have you created anything for automatically setting the connection when using the DB:: facade? Would you just add that to the "switch_tenant_tasks" or override the original Database Provider?

**Comment by masterix21** [comment]
Hi @josiahmann, check here: https://docs.spatie.be/laravel-multitenancy/v1/using-tasks-to-prepare-the-environment/switching-databases/

**Comment by josiahmann** [comment]
Thanks,

I am using the SwitchTenantDatabaseTask, but the DB facade was returning the landlord db... maybe I just need to change my default connection to 'tenant'? That seems to do the trick...

**Comment by masterix21** [comment]
Yes, i'm talking of it here: https://github.com/spatie/laravel-multitenancy/pull/59

I think that if you use a tenant, it should be the default connection (and not the landlord), but changing the default connection seems to be wrong for @freekmurze, but at the moment seems to be a solution (for me).
