### ISSUE TITLE
Tenant multi domain testing

### ISSUE THREAD

**Issue by CasperBE** [spatie/laravel-multitenancy#68]
Hi team,
First of all thanks for this amazing package!
I'm fairly new to Laravel and now trying to rewrite an old project in Laravel with this multitenancy package.
Part of rewriting the project is trying to do things better, which for one involves adding tests.
I've got Laravel and multitenancy up and running, and I've got my first green tests. But now I'm stuck at testing for a subdomain returning the right status code.
For example, I create one tenant with domain `one.tenancytest.test` and I assert for a status 200 on `one.tenancytest.test` and a status 500 on `doesnotexist.tenancytest.test`
The first one works, but the second assertion fails as it also returns status 200.
My tests and setup are here: [https://github.com/CasperBE/tenancytest](https://github.com/CasperBE/tenancytest)
`\Spatie\Multitenancy\Http\Middleware\NeedsTenant::class` has been added to the `App/Http/Kernel.php` file
All the steps I've made to get to this point are in the `README.md` file.
I hope that someone can help me out here!
Thanks in advance,
Jasper

**Comment by masterix21** [comment]
Hi @CasperBE,

try to use the task mentioned here
https://github.com/spatie/laravel-multitenancy/issues/65#issuecomment-651411277

And tell me if it works.

Thanks

**Comment by CasperBE** [comment]
Thanks for you response.
I did add the SwitchRouteUrlTask which does work for the first part of the test. For the second part (test calling a non-existing tenant) I've implemented a part of the task in the test. Now it's all green, thanks again for your help!
I've updated the test in the repo [https://github.com/CasperBE/tenancytest](https://github.com/CasperBE/tenancytest)
