### ISSUE TITLE
How to make telescope tenant aware?

### ISSUE THREAD

**Issue by aminraeisi** [spatie/laravel-multitenancy#70]
How can I make telescope tenant aware? here is the part that throws error because 'mysql' is no longer available but instead the name is dynamic:

```php
'driver' => env('TELESCOPE_DRIVER', 'database'),

    'storage' => [
        'database' => [
            'connection' => env('DB_CONNECTION', 'mysql'),
            'chunk' => 1000,
        ],
    ],
```

**Comment by masterix21** [comment]
My suggestion is to keep working telescope on the landlord connection. Next, create a tag for Telescope when you switch a tenant.

I will create a TelescopeSwitchTenantTask in the next PR, and I hope that will be merged.

**Comment by masterix21** [comment]
@aminraeisi try something like this:
```php
class SwitchTenantTelescopeTask implements SwitchTenantTask
{
    protected ?array $originalTelescopeTagUsing;

    public function makeCurrent(Tenant $tenant): void
    {
        $this->originalTelescopeTagUsing = Telescope::$tagUsing;

        Telescope::$tagUsing = [];
        Telescope::tag(fn () => [ $tenant->host ]);
    }

    public function forgetCurrent(): void
    {
        Telescope::$tagUsing = $this->originalTelescopeTagUsing;
        Telescope::tag(fn () => [ 'landlord' ]);
    }
}
```

**Comment by aminraeisi** [comment]
Thanks for your time! What does this supposed to do? is it for tagging the telescope entries (assuming I need to move the telescope migrations to landlord)?

**Comment by masterix21** [comment]
Yes!

I think that the best way to use Telescope is in only one database (landlord), then when you need to track a request or anything else about a Tenant, you can simply add a "tag" to Telescope. Will works like a charm :)

**Comment by aminraeisi** [comment]
It worked! Please update `$tenant->host` to `$tenant->domain` as it made me spend 1 hour to find out why it is not tagging them :rofl:

**Comment by masterix21** [comment]
Haha, sorry, I made a mistake because I'm using "host" and not "domain" in my project.

Thanks.

**Comment by aminraeisi** [comment]
Thanks for that! one more thing, It did not tag the non-tenant requests. I can put space to detect them but it would be better if the default is landlord.

**Comment by masterix21** [comment]
Doesn't works using "landlord" as tag?

**Comment by aminraeisi** [comment]
Each tenant has subdomain and visiting tenant1.site.com will tag the request with `tenant1.site.com` but when I go to the main site.com the request does not get any tags and I want to get 'landlord' tag for it.

**Comment by masterix21** [comment]
Ok. What happen if you add `Telescope::tag(fn () => [ 'landlord' ]);` to your AppServiceProvider boot method?

**Comment by aminraeisi** [comment]
That adds the landlord tag to all the requests even if it is a tenant request. So I need to remove it somehow when it is on the tenant? Or we don't have tasks to run when no tenant is selected? I mean when the request is to the main landlord site?

**Comment by aminraeisi** [comment]
Adding this to AppServiceProvider worked:

```php
!Tenant::current() ? Telescope::tag(fn () => ['landlord']): '';
```

So it will only add the landlord tag if we do not have a current tenant. Thanks a lot for your help.

**Comment by masterix21** [comment]
Well ;)
