### ISSUE TITLE
Testing Issue

### ISSUE THREAD

**Issue by sausin** [spatie/laravel-multitenancy#74]
Hi!

Thanks for the wonderful work on this package! The integration with the app in progress went quite well and things are working well on the actual app (I think!).

One snag that I seem to have hit is with testing. All the tests were working correctly before integration with this package. I made the following changes to get things working:

- Added the following method to the `TestCase.php` file

```php
public function setUp(): void
{
    parent::setUp();

    Tenant::find(1)->makeCurrent();
}
```

- Updated the `multitenancy.php` config file so it would have the test database information for `landlord` and `tenant`
```php
'tenant_database_connection_name' => env('DB_CONNECTION_TENANT', null),
'landlord_database_connection_name' => env('DB_CONNECTION_LANDLORD', null),
```
- The `.env.testing` file defines these variables with information for the databases and the same connections are defined in the `database.php` config file

Currently, most of the tests are working, but some are throwing up random errors. The thing that is common in all tests where failures are occurring is the use of `DatabaseTransactions` trait.

Checking further, I found that the trait is infact not working. If some entries are created / deleted in the tests, they do not get reverted.

Any help would be great to have :-)

**Comment by masterix21** [comment]
hi @sausin, can you post a test example, please?

**Comment by sausin** [comment]
Sure! Please see below an example test on the reset route:

```php
<?php

namespace Tests\Feature\Controllers\Auth;

use App\User;
use Illuminate\Auth\Notifications\ResetPassword;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Str;
use Tests\TestCase;

class ForgotPasswordControllerTest extends TestCase
{
    use DatabaseTransactions;

    /** @test */
    public function it_resends_verification_email()
    {
        Event::fake();
        Notification::fake();

        $u = User::create([
            'name' => Str::random(10),
            'email' => $e = Str::random(10).'@example.com',
            'phone_number' => 00001112345,
            'password' => Hash::make('password'),
        ]);

        $this->postJson('/password/email', ['email' => $e])
            ->assertOk();

        Notification::assertSentTo($u, ResetPassword::class);
    }
}
```

I have a unique constraint on the `phone_number` field. The test runs fine the first time (as there is no entry for the above `phone_number`. Running it again, it throws up errors that the unique constraint got violated (because the previous run did not end in rollback of the transaction).

The test was running fine before (hundreds of times).

A simple workaround in the above example would be to use a random number on the field, but that wouldn't solve the issue that the `DatabaseTransactions` features aren't functioning.

Thanks!

**Comment by sausin** [comment]
Just to add some info to the discussion, I did some more digging and investigations are listed below:

- the `beginDatabaseTransaction` method in the `DatabaseTransactions` trait is not able to get results from `connectionsToTransact`. In the setup listed above, the connections array is empty

- Adding this `protected $connectionsToTransact = ['tenant_testing_connection'];` to the `TestCast.php` provides the trait method the necessary info, but it makes no difference. The transaction feature still doesn't work

**Comment by sausin** [comment]
Okay, so diving into the codebase of laravel, I think I have located the issue. The transactions are actually being reported corresponding to the `landlord` database and not the `tenant` database.

Got this by looking at the workings inside the `rollBack` method in `ManagesTransactions` class. I am guessing that something is happening in this package which is messing up the database reporting.

**Comment by masterix21** [comment]
@sausin DB facade use your default connection, but doesn't prohibiting to specify a connection:
```php
DB::connection('tenant')->transaction(function () {
	return DB::connection('tenant')->select(DB::raw('SHOW TABLES'));	
});
```

Try and tell me if it works.

**Comment by sausin** [comment]
@masterix21 Not sure I understand correctly, but manually specifying the transaction in each test could work but then I would need to update all of my tests (1000+). Also, the default connection was specified as the `tenant` connection. Changing it to the `landlord` connection makes no difference either.

Also the issue from laravel framework linked above indicates that specifying the connection to transact should work and is in fact 'working' but the transactions are being counted on the incorrect connection so the end result is not as expected.

If you meant something else, please let me know!

**Comment by masterix21** [comment]
If you need to use a tenant connection as default, use "tenant" as the default connection. See the PR: https://github.com/spatie/laravel-multitenancy/pull/59.

We are talking with @freekmurze from many weeks, but there are a lot of things that don't convince him and others that are uncleared for me.

**Comment by sausin** [comment]
@masterix21 Using the `tenant` as default connection doesn't change anything on this issue unfortunately. It would definitely be awesome to get some thoughts on this from @freekmurze

**Comment by masterix21** [comment]
@sausin isn't simple to help somebody without the code (your test code above said nothing of your problem), anyway I hope that @freekmurze could help you.

Have you already tried to use `RefreshDatabase` instead of `DatabaseTransactions`? It seems that `DatabaseTransactions` has been removed from Laravel documentation (but it's available in the API). 

In the meanwhile, try to extend your TestCase (for the tenant) with:

```php
    protected function setUp(): void
    {
        parent::setUp();

        DB::connection('tenant')->beginTransaction();
    }

    protected function tearDown(): void
    {
        DB::connection('tenant')->rollBack();

        parent::tearDown();
    }
```

**Comment by sausin** [comment]
@masterix21 Indeed, the recommended way is to use `RefreshDatabase` in the docs. However, for my test setup `DatabaseTransactions` is exactly what I need to use. Under the hood, `RefreshDatabase` (as I understand it) makes a choice between using `DatabaseTransactions` or `DatabaseMigrations`.

Thanks for the tip above! I'm trying it with some mixed results right now. Will report back :+1:

**Comment by sausin** [comment]
@masterix21 the above tip was definitely an improvement, thanks! Tests seem to be working when run in isolation but failing when run in a batch. Wow, this is just :cry:

**Comment by masterix21** [comment]
@sausin, great. Do you have a full example to understand if it depends on the spatie/laravel-multitenancy package? If you can, please create a repository on GitHub with a testable project to understand better: it should help us. Thanks.

**Comment by sausin** [comment]
@masterix21 I'll try to setup a repo with tests

**Comment by masterix21** [comment]
@sausin, I have an update for the past problem. If you see the `DatabaseTransactions` trait, it has:
```php
protected function connectionsToTransact()
{
    return property_exists($this, 'connectionsToTransact')
               ? $this->connectionsToTransact : [null];
}
```

It means that if you specify a property called connectionsToTransact in your test, the trait will begin a transaction for all connections of array:
```php
protected $connectionsToTransact = [
    'landlord',
    'tenant',
];
```

Had you already tried it before using `setUp()` and `tearDown()`?

**Comment by sausin** [comment]
@masterix21 I've already tried this, as mentioned [above](https://github.com/spatie/laravel-multitenancy/issues/74#issuecomment-654287880), with no success

**Comment by masterix21** [comment]
Sorry, you're right

**Comment by sausin** [comment]
The consequently [observed behaviour](https://github.com/spatie/laravel-multitenancy/issues/74#issuecomment-654576048) is what's really strange. I don't understand how that's happening.

I've also hit some random bugs which make no sense to me (and as I mentioned above, most of the relevant tests just pass when run independently).

Trying to setup a repo so that the discussion can be easier :+1:

**Comment by masterix21** [comment]
Ok, I have simulated all your examples, and now I'm synced with you. 

> * the `beginDatabaseTransaction` method in the `DatabaseTransactions` trait is not able to get results from `connectionsToTransact`. In the setup listed above, the connections array is empty

Yes, you're right. There are no nicely solutions at the moment. The only way seems to be to create a copy 1:1 of `DatabaseTransactions` trait with a new name (for example `TenantAwareDatabaseTransactions`) to call your `$this->beginDatabaseTransaction()` as follow:
```php
    use TenantAwareDatabaseTransactions;

    protected function setUp(): void
    {
        parent::setUp();

        Tenant::first()->makeCurrent();

        $this->beginDatabaseTransaction();
    }
```

**Comment by freekmurze** [comment]
Closing this, as it seems to have been answered.

**Comment by sausin** [comment]
@freekmurze We've not been able to resolve the issue being noted in the comment [above](https://github.com/spatie/laravel-multitenancy/issues/74#issuecomment-654361321).

Also, even when the manually specifying the transactions in the `TestCase` class (thanks @masterix21 for the tip), the tests haven't reached passing stage (unlike before when they were all passing even when run randomly across many runs).

**Comment by masterix21** [comment]
@sausin, I found a great solution.

Try to use the following `TestCase.php`:
```php
namespace Tests;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\Event;
use Spatie\Multitenancy\Concerns\UsesMultitenancyConfig;
use Spatie\Multitenancy\Events\MadeTenantCurrentEvent;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication, DatabaseTransactions, UsesMultitenancyConfig;

    protected function connectionsToTransact()
    {
        return [
            $this->landlordDatabaseConnectionName(),
            $this->tenantDatabaseConnectionName(),
        ];
    }

    protected function setUp(): void
    {
        parent::setUp();

        Event::listen(MadeTenantCurrentEvent::class, function () {
            $this->beginDatabaseTransaction();
        });
    }
}
```

I have already tried, and it seems that it works very well. If you confirm it, we will upgrade the documentation.

Thanks

**Comment by sausin** [comment]
@masterix21 This setup is great :smiley: and simplifies things quite a bit. I just had to add `Tenant::first()->makeCurrent();` in the `setUp` method at the end for things to work. Another thing that has been required is an overridden middleware class:

```php
<?php

namespace App\Http\Middleware;

use Closure;
use Spatie\Multitenancy\Http\Middleware\EnsureValidTenantSession as MiddlewareEnsureValidTenantSession;

class EnsureValidTenantSession extends MiddlewareEnsureValidTenantSession
{
    public function handle($request, Closure $next)
    {
        if (app()->environment() === 'testing') {
            return $next($request);
        } else {
            return parent::handle($request, $next);
        }
    }
}
```

I still have some weird errors. Setting up the test repo is long overdue (my bad :disappointed:). I'll try to do it asap

**Comment by masterix21** [comment]
Ok, now is better to close the issue, because for me has been solved. If you need more help for it, please reply anyway to it.

Thank you.

**Comment by sausin** [comment]
Yes sure, thanks a lot for all the help @masterix21

**Comment by sausin** [comment]
@masterix21 So the last set of issues pending for me involve `dispatch`. I have a model `App\SomeModel` which has observer on `creating`, `created` and `updating` events.

On the `created` event, I am dispatching a job which takes the model as input. This setup works fine in reality (using the web interface of the app) but the tests fail with this error

```php
Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [App\SomeModel].
````
The `created` method looks like this:
```php
public function created(SomeModel $someModel): void
{
    dispatch(new DoSomethingWithNewModel($someModel))->onQueue('do-something');
}
```

If I comment out the dispatch line, the tests work fine.

Appreciate the help :smiley:

**Comment by ArtisanTinkerer** [comment]
I was also experiencing this problem. 

A quick test of the solution provided by @masterix21 is looking good, nice one. 

Definitely would be good to have a testing section in the docs.

**Comment by freekmurze** [comment]
Feel free to send PRs to the docs. Each page contains a edit button that allows you to create a PR quickly 👍

**Comment by sausin** [comment]
@freekmurze PR #101 is in place

**Comment by masterix21** [comment]
Thank you @sausin

**Comment by sausin** [comment]
Least I could've done :+1:

**Comment by RuthBouhaddi** [comment]
> ```
> DB::connection('tenant')->transaction(function () {
> 	return DB::connection('tenant')->select(DB::raw('SHOW TABLES'));	
> });
> ```
