### ISSUE TITLE
Scheduled Job issue

### ISSUE THREAD

**Issue by ChrisCook1906** [spatie/laravel-multitenancy#82]
Hi --
I have the package set up and things are working as expected....with the exception of my scheduled jobs.

I have queues enabled by default to be tenant aware:
`'queues_are_tenant_aware_by_default' => true`

I have the middleware added to app/http/kernel:
```php
// middlewaregroups / web:
\Spatie\Multitenancy\Http\Middleware\NeedsTenant::class,
\Spatie\Multitenancy\Http\Middleware\EnsureValidTenantSession::class
```

In App\Console\Kernel, I have a scheduled job:
`$schedule->job(new UpdateMatrix())->everyFiveMinutes();`

The job runs twice but only the main database updates.

In my cronjob (which executes the Scheduler) I have applied the tenants:artisan prefix.

For the UpdateMatrix job above, I have added TenantAware
class UpdateMatrix implements ShouldQueue, TenantAware..

What am I missing?

**Comment by masterix21** [comment]
Hi @ChrisCook1906, how does scheduled your jobs? All jobs are scheduled using the Laravel default logic (tenant not-aware). Have you implemented a logic that replaces the original one? Please post your code to help me to understand. Thanks

**Comment by ChrisCook1906** [comment]
I'm running the standard Scheduler function in App/Console/Kernel:
`protected function schedule(Schedule $schedule)
    {
        $schedule->job(new UpdateMatrix())->hourly();
    }`

The job, UpdateMatrix, has the proper TenantAware function implemented.  All of my other queued jobs are working correctly, except for those dispatched via the Schedule function in (App/Console/Kernel).

**Comment by masterix21** [comment]
Ok, sorry for my questions but I'd like to understand: in your `UpdateMatrix` do you use `Tenant::makeCurrent()`?

**Comment by ChrisCook1906** [comment]
No.  In the `UpdateMatrix` job, I implement the following:
`use Spatie\Multitenancy\Jobs\TenantAware;`

`class UpdateMatrix implements ShouldQueue, TenantAware
{......}`

**Comment by masterix21** [comment]
@ChrisCook1906, I tried but seems that works like a charm. What am I wrong?

```php
// app/console/Kernel.php
protected function schedule(Schedule $schedule)
{
    if (Tenant::current()) {
        $schedule->job(TenantNoopJob::class)->everyMinute();
        return;
    }

    $schedule->job(LandlordNoopJob::class)->everyMinute();
}
```

```php
//
// TenantNoopJob
class TenantNoopJob implements ShouldQueue, TenantAware
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function handle()
    {
        Log::info('TenantNoopJob - '. Tenant::current()->domain .' - '. now());
    }
}

// 
// LandlordNoopJob
class LandlordNoopJob implements ShouldQueue, NotTenantAware
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function handle()
    {
        Log::info('LandlordNoopJob - '. now());
    }
}
```

![example](https://user-images.githubusercontent.com/6555012/88442535-22b2ce00-ce15-11ea-9845-e55f12dfb154.gif)

**Comment by masterix21** [comment]
@ChrisCook1906, do you have found a solution to the issue?

**Comment by ChrisCook1906** [comment]
@masterix21 Yes.  Thank you.
