### ISSUE TITLE
when there's a `Failed tenant job` it will be inserted in landlord database

### ISSUE THREAD

**Issue by abderrazzak-oxa** [spatie/laravel-multitenancy#91]
there's two database `for tenant` and `for landlord`

#### Event:
``
public function __construct(TestModel $model)
{
    $this->model = $model;
}
``

#### Listener function:
`
public function handle(TestEvent $event): void
    {
        throw new \Exception("Test record failed jobs");
    }
`

-> database of landlord has failed_jobs table
-> database of tenant has failed_jobs table

### result:
in the tenant failed_jobs table is empty
in the landlord failed_jobs table is:
`
Exception: Test record failed jobs in D:\fullpath\ListenerFile.php:53
Stack trace:
...
`

**Comment by freekmurze** [comment]
I'd accept a PR with tests that fixes this.

**Comment by abderrazzak-oxa** [comment]
#### I think the problem is from config => ***config.failed.database***
- So this database name must be changed when there's an switch_tenant_tasks event
- So it's not a bug from this package 
- i should do this from my code

this is the source code of laravel when there's a failed job:
<br>
`\laravel\framework\src\Illuminate\Queue\QueueServiceProvider.php`

```
    protected function registerFailedJobServices()
    {
        $this->app->singleton('queue.failer', function ($app) {
            $config = $app['config']['queue.failed'];

            if (isset($config['driver']) && $config['driver'] === 'dynamodb') {
                return $this->dynamoFailedJobProvider($config);
            } elseif (isset($config['table'])) {
                return $this->databaseFailedJobProvider($config);
            } else {
                return new NullFailedJobProvider;
            }
        });
    }
```

```
    protected function databaseFailedJobProvider($config)
    {
        return new DatabaseFailedJobProvider(
            $this->app['db'], $config['database'], $config['table']
        );
    }
```

- So you can close this issue because the problem is not in package, the problem is in my code
And Thank You So Much

**Comment by abderrazzak-oxa** [comment]
You can also change the failed job tenant database from `SwitchTenantDatabaseTask` @freekmurze
