### ISSUE TITLE
Can't migrate when using Laravel Telescope.

### ISSUE THREAD

**Issue by ArtisanTinkerer** [spatie/laravel-multitenancy#94]
I get this error:

```Base table or view already exists: 1050 Table 'telescope_entries'```

Presumably this is because the telescope migration is running against the tenants. Is there a way to get this to run against the landlord?

**Comment by abderrazzak-oxa** [comment]
You need to execute this command for tenants:

`php artisan tenant:artisan 'migrate'`

**Comment by ArtisanTinkerer** [comment]
Just to add a bit more detail.

I am getting this error when running: ``` php artisan tenants:artisan "migrate --database=tenant"```

This is the output:

```
root@3346909808d6:/var/www/crm# php artisan tenants:artisan "migrate --database=tenant"

Running command for tenant `one` (id: 1)...
---------------------------------------------------------
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (0.14 seconds)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (0.15 seconds)
Migrating: 2018_08_08_100000_create_telescope_entries_table
Migrated:  2018_08_08_100000_create_telescope_entries_table (0.56 seconds)
Migrating: 2019_08_19_000000_create_failed_jobs_table
Migrated:  2019_08_19_000000_create_failed_jobs_table (0.06 seconds)
Migrating: 2020_07_20_084618_create_contacts_table
Migrated:  2020_07_20_084618_create_contacts_table (0.13 seconds)
Migrating: 2020_07_20_155442_create_messages_table
Migrated:  2020_07_20_155442_create_messages_table (0.21 seconds)

Running command for tenant `two` (id: 2)...
---------------------------------------------------------
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (0.13 seconds)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (0.1 seconds)
Migrating: 2018_08_08_100000_create_telescope_entries_table

   Illuminate\Database\QueryException 

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'telescope_entries' already exists (SQL: create table `telescope_entries` (`sequence` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `batch_id` char(36) not null, `family_hash` varchar(255) null, `should_display_on_index` tinyint(1) not null default '1', `type` varchar(20) not null, `content` longtext not null, `created_at` datetime null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')


```

Both tenant one and two did not have any table before running the migration.

**Comment by abderrazzak-oxa** [comment]
Yes i think this table `telescope_entries` is already exists in the tenant number 2,

so please try this: `php artisan tenant:artisan "migrate:fresh --database=tenant"`

**Comment by ArtisanTinkerer** [comment]
I don't think it is. When I run this command I ensure that neither tenant have any tables in.
The landlord only contains the tenants table.

I get the same error, in the same place, using the fresh command.

When I examine the databases, after running the command, I can see:
**one:**
```
failed_jobs
migrations
password_resets
users
```

**two:**
```
migrations
password_resets
users
```

**landlord:**
```
migrations
telescope_entries
telescope_entries_tags
telescope_monitoring
tenants
```

So the process is correctly creating the telescope tables in the landlord but it is doing it for every tenant?

**Comment by masterix21** [comment]
Hi @ArtisanTinkerer.

Move Telescope migrations inside the "database/migrations/landlord" path and next run your landlord migration again:
```sh
php artisan migrate --path=database/migrations/landlord --database=landlord
```

**Comment by ArtisanTinkerer** [comment]
Do I really want to move things from the vendor directory into my app?

**Comment by masterix21** [comment]
`php artisan vendor:publish --tag=telescope-migrations`

and next move Telescope migrations from `database/migrations` to `database/migrations/landlord`, and inside that path you will move all migrations landlord-reserved.

**Comment by ArtisanTinkerer** [comment]
I did this:

- ```php artisan vendor:publish --tag=telescope-migrations```
- moved Telescope migrations from database/migrations to database/migrations/landlord
- ```php artisan tenants:artisan "migrate --database=tenant"```

Same result.

**Comment by masterix21** [comment]
Are you sure that you have moved all Telescope migrations? Post your `database` folder contents, please.

**Comment by ArtisanTinkerer** [comment]
![migrations](https://user-images.githubusercontent.com/13234475/88518760-e637cb80-cfe8-11ea-873b-3732016dd89f.png)

There is only one migration file for Telescope:

https://github.com/laravel/telescope/tree/d6d6269e0945f7c93aa3ff83dbc11de07abebf9f/src/Storage/migrations

**Comment by masterix21** [comment]
Do you have tried using
`php artisan tenants:artisan "migrate:fresh --database=tenant"`?

**Comment by ArtisanTinkerer** [comment]
I start with three completely empty database (none of the databases have any tables in).

1. I do this:
``` php artisan migrate --path=database/migrations/landlord --database=landlord ```
This  is the result:
```
Migration table created successfully.
Migrating: 2018_08_08_100000_create_telescope_entries_table
Migrated:  2018_08_08_100000_create_telescope_entries_table (0.62 seconds)
Migrating: 2020_07_24_114830_create_landlord_tenants_table
```
2. Then I add the records to the tenants table.
3. Then I migrate the tenants:
```
php artisan tenants:artisan "migrate --database=tenant"

```

```
Running command for tenant `one` (id: 1)...
---------------------------------------------------------
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (0.14 seconds)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (0.1 seconds)
Migrating: 2018_08_08_100000_create_telescope_entries_table

   Illuminate\Database\QueryException 

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'telescope_entries' already exists (SQL: create table `telescope_entries` (`sequence` bigint unsigned not null auto_increment

```

4. If I run (which is pointless, because I started with empty databases):
```
php artisan tenants:artisan "migrate:fresh --database=tenant"
````
```
Running command for tenant `tesco` (id: 1)...
---------------------------------------------------------
Dropped all tables successfully.
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (0.14 seconds)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (0.1 seconds)
Migrating: 2018_08_08_100000_create_telescope_entries_table

   Illuminate\Database\QueryException 

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'telescope_entries'
```

**Somehow the 2018_08_08_100000_create_telescope_entries_table migration is getting run for each tenant.**

**Comment by masterix21** [comment]
Ok, now I have understood. Please add to your `AppServiceProvider.php` the following line in your `register()` method:
```php
Telescope::ignoreMigrations();
```

**Comment by ArtisanTinkerer** [comment]
Yes, great. That works now. Thanks.

**Comment by DeveloperBekzod** [comment]
If your telescope tables located another database you should drop it.

php artisan db:wipe --database=telescope
