### ISSUE TITLE
Tenant migration command adds tables to landlord database.

### ISSUE THREAD

**Issue by herecomeslucky0145** [spatie/laravel-multitenancy#95]
command: php artisan tenants:artisan "migrate" --tenant=1
output: Running command for tenant `tenant1` (id: 1)...
But all the tables are added to landlord database. 
Here's my landlord connection.
![image](https://user-images.githubusercontent.com/35728183/88546945-ca5e1500-d03c-11ea-9824-8230c3827f33.png)
Here's my tenant connection.
![image](https://user-images.githubusercontent.com/35728183/88547032-e792e380-d03c-11ea-9ef7-54ff59caef4b.png)

I am new to the package and cannot figure out it on my own. Thank you

**Comment by masterix21** [comment]
Hi @herecomeslucky0145, are you using `Spatie\Multitenancy\Tasks\SwitchTenantDatabaseTask::class` task?

**Comment by herecomeslucky0145** [comment]
@masterix21 yes.

**Comment by masterix21** [comment]
Yes.

Please post the output of:
```php
echo config('multitenancy.tenant_database_connection_name');
```

**Comment by herecomeslucky0145** [comment]
In database.php I have set default as  'default' => env('DB_CONNECTION', 'tenant')
Also, DB_connection = tenant
Here's the output. And the output is same before and after running the migrations.
![image](https://user-images.githubusercontent.com/35728183/88550196-fda2a300-d040-11ea-9889-9cf840eec7f1.png)

**Comment by masterix21** [comment]
Please post your config/multitenancy.php file.

**Comment by herecomeslucky0145** [comment]
@masterix21 the issue is solved now. Thank you for the help. The culprit was config cache and I was too dumb to figure it out first. Thank you again.

**Comment by masterix21** [comment]
Great ;)
