### ISSUE TITLE
How to configure for testing?

### ISSUE THREAD

**Issue by ArtisanTinkerer** [spatie/laravel-multitenancy#97]
I'm trying to test in the standard Laravel way with PHPSTORM, PHPUnit and sqlite in memory database (RefreshDatabase trait).

I am trying to assert that a record has been created in the landlord database (actually I am trying to TDD a command which creates a tenant). I assumed that the connected database would be the landlord one but it does not contain a tenants table.

```
\DB::select('SHOW TABLES')

result = {array} [6]
 0 = {stdClass} [1]
  Tables_in_landlord = "contacts"
 1 = {stdClass} [1]
  Tables_in_landlord = "failed_jobs"
 2 = {stdClass} [1]
  Tables_in_landlord = "messages"
 3 = {stdClass} [1]
  Tables_in_landlord = "migrations"
 4 = {stdClass} [1]
  Tables_in_landlord = "password_resets"
 5 = {stdClass} [1]
  Tables_in_landlord = "users"

env('DB_CONNECTION')
sqlite

\DB::connection()
landlord
```

PHPUnit.xml
```
 <server name="DB_CONNECTION" value="sqlite"/>
 <server name="DB_DATABASE" value=":memory:"/>
```

This is showing the structure for a tenant database. How should I configure so that I am testing against a landlord database?

**Comment by masterix21** [comment]
You can't switch a :memory: database

**Comment by ArtisanTinkerer** [comment]
How do you do any automated testing then? 

Somehow I need to configure two databases (landlord and one tenant) and be able to test against them.

**Comment by masterix21** [comment]
Yes, sure: it's what we already done in our tests. You can use MySQL.

**Comment by ArtisanTinkerer** [comment]
I think using MySQL will be a last resort. I want to run in memory, so that my tests run quickly.

**Comment by masterix21** [comment]
If you'll find a solution, keep us updated. Thanks

**Comment by freekmurze** [comment]
Closing this as this is not a problem for the package tests, and it's also not an issue in our projects. If you find a solution, feel free to post it below, might be helpful for others.

**Comment by ArtisanTinkerer** [comment]
How to you TDD when using this package? Using MySQL instead of SQLite?

**Comment by masterix21** [comment]
yes

**Comment by freekmurze** [comment]
Me too, I find that using MySQL is far more easier that SQLite. In SQLite certain functions (and json handling) doesn't exist or is a bit different than in MySQL.

**Comment by masterix21** [comment]
IMHO it's better to test your application with the same database that you will use in the production environment: it will improve the test experience, and the feedback is more near to real.

**Comment by ArtisanTinkerer** [comment]
OK, I'm going to give it a go. 

I'd love to see your testing config (phpunit.xml, database.php) for running tests against landlords and tenants.

**Comment by ArtisanTinkerer** [comment]
I have a tenant db and a landlord db set up for testing (MySQL). How do you switch in a test?

**Comment by masterix21** [comment]
Using `Tenant::first()->makeCurrent()` and `Tenant::current()->forget()`, or if you like:
```php
Tenant::first()->execute(function () {
// all your tenant-aware tests :)
});
```

**Comment by ArtisanTinkerer** [comment]
I am doing that in a test:

```
Tenant::first()->makeCurrent();
```

When I look a the connection, it is still connected to the landlord:

```
result = {Illuminate\Database\MySqlConnection} [18]
 resolvers = {array} [0]
 pdo = {Doctrine\DBAL\Driver\PDOConnection} [0]
 readPdo = null
 database = "landlord"
```

and ``` \DB::select('SHOW TABLES') ```
Shows tables from the landlord.

Am I doing something silly?

**phpunit**
```
<server name="DB_CONNECTION" value="landlord"/>
 <server name="DB_DATABASE" value="landlord"/>
```

**database.php**

```
'landlord' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('LANDLORD_DB_HOST'),
            'port' => env('LANDLORD_DB_PORT'),
            'database' => env('LANDLORD_DB_DATABASE'),
            'username' => env('LANDLORD_DB_USERNAME'),
            'password' => env('LANDLORD_DB_PASSWORD'),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],

        'tenant' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('TENANT_DB_HOST'),
            'port' => env('TENANT_DB_PORT'),
            'database' => env('TENANT_DB_DATABASE'),
            'username' => env('TENANT_DB_USERNAME'),
            'password' => env('TENANT_DB_PASSWORD'),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],

```

**.env**
```
DB_CONNECTION=landlord
LANDLORD_DB_HOST=mysql
LANDLORD_DB_PORT=3306
LANDLORD_DB_DATABASE=landlord
LANDLORD_DB_USERNAME=default
LANDLORD_DB_PASSWORD=secret

TENANT_DB_HOST=mysql
TENANT_DB_PORT=3306
TENANT_DB_DATABASE=null
TENANT_DB_USERNAME=default
TENANT_DB_PASSWORD=secret
```

**Comment by ArtisanTinkerer** [comment]
I can see in ```SwitchTenantDatabaseTask``` where it is swapping the db:

```
 DB::purge($tenantConnectionName); //tenant
```

But after this ```DB:connection()``` still returns the landlord database (which is the default in database.php).

I must have something wrong somewhere.

**Comment by jartaud** [comment]
@ArtisanTinkerer Actually MySQL is faster than SQlite:

- Use  `DatabaseTransactions`
- Migrate your test DB `php artisan migrate --database=mysql_testing`

**Pros**
You can use any MySQL function like `DATE_FORMAT, tmp.category_name->>"$.'.$lang.'" as fmt_category_name`

**Cons**
You have to migrate your test DB `php artisan migrate --database=mysql_testing` just like your local DB



---------------------
I'm getting :


```
Time: 3.13 minutes, Memory: 596.00 MB
OK (1508 tests, 7787 assertions)
```
from a 4 years old HP running Ubuntu Budgie 18.04 with HDD

**Comment by gssoftnepal** [comment]
Hi, `php artisan test` runs fine, but when I try to run `php artisan test -p` it throws errors. Any suggestions?

**Comment by masterix21** [comment]
@gssoftnepal what's the error?

**Comment by gssoftnepal** [comment]
I am using **Laravel Sail** with multiple databases, when I run `php artisan test -p`, I get this error `Illuminate\Database\QueryException: SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'sail'@'%' to database '_test_4' (SQL: drop database if exists `_test_4`)`

**Comment by jartaud** [comment]
> I am using **Laravel Sail** with multiple databases, when I run `php artisan test -p`, I get this error `Illuminate\Database\QueryException: SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'sail'@'%' to database '_test_4' (SQL: drop database if exists `_test_4`)`

You need to run `sail artisan test`

**Comment by gssoftnepal** [comment]
At first I ran `sail shell` and then ran `php artisan test`. This runs fine. I also ran `sail artisan test` in my local terminal, it also runs fine, but when I run `php artisan test -p` or `sail artisan test -p`, all of my tests fail and I get this error:  `Illuminate\Database\QueryException: SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'sail'@'%' to database '_test_4' (SQL: drop database if exists _test_4)`

**Comment by adarmanto** [comment]
I just want to share how to configure the unit tests in my environment using Laravel v9 (as I was a bit lost about):

[How to configure the unit tests for spatie/laravel-multitenancy package](https://gist.github.com/adarmanto/44e4b94eb570da05a619fd44c8dd9c05)

On your test you need to replace `RefreshDatabase` with `TenantAware` :

```php
namespace Tests\Feature;

use Tests\TestCase;
use App\Models\Tenant;
use Tests\Concerns\TenantAware;

class ExampleTest extends TestCase
{
    use TenantAware;

    public function testExample()
    {  
        $this->assertTrue(Tenant::checkCurrent());
    }
}
```

**Comment by valh1996** [comment]
@adarmanto Just a small point, how do you deal with the fact that when you do `php artisan test`, it will create a tenant and its database, but the second time you run this command it will not work because the `testing_tenant_db` database already exists?

**Comment by adarmanto** [comment]
@valh1996 in your case, you can skip creating the tenant database on testing like so:

```php
if (! app()->runningUnitTests()) {
    // Skip the tenant DB creation
}
```

**Note**: this is one of my reason to put the tenant DB creation into Queue so either I can mock it to skip it while testing and also test it as as [my example](https://gist.github.com/adarmanto/44e4b94eb570da05a619fd44c8dd9c05#file-tests-feature-examplewithoutcurrenttenanttest-php).

**Comment by valh1996** [comment]
@adarmanto Thank you. 

I ended up just adding `IF NOT EXISTS` when creating a new database:
```php
DB::connection($this->tenantDatabaseConnectionName())->statement("CREATE DATABASE IF NOT EXISTS {$this->getDatabaseName()}");
```

Let me ask you another question, how do you deal with laravel built-in asserts like `$this->assertAuthenticated();`, it always uses the landlord connection. Any idea please?

**Comment by adarmanto** [comment]
@valh1996 I put the authentication tables (users, password_reset, etc) into the landlord database, but set the `tenant` connection as my default DB and there is no issue when running default-generated tests from [Starter Kit](https://laravel.com/docs/9.x/starter-kits#breeze-and-inertia) (using Inertia in my case). Don't forget to use `Spatie\Multitenancy\Models\Concerns\UsesLandlordConnection` trait in any models that use `landlord` connection.

**Comment by valh1996** [comment]
@valh1996 I see, I use landlord as default connection. I have authentication at the landlord level, then in each tenant. Thanks for you response.
