### ISSUE TITLE
TenantAware with custom Tenant Finder in queues

### ISSUE THREAD

**Issue by henryavila** [spatie/laravel-multitenancy#98]
Hi, In my case, I'm using a middlewaare to define the middleware (as pointed at #53 ).

The problem is that When I queue a simple Send mail, it always throw a `Spatie\Multitenancy\Exceptions\CurrentTenantCouldNotBeDeterminedInTenantAwareJob`.

How can I set a custon Tenant Finder for queue?

**Comment by masterix21** [comment]
Hi @henryavila,

could be related to https://github.com/spatie/laravel-multitenancy/pull/78?

**Comment by freekmurze** [comment]
@henryavila Try upgrading to the latest version of the package. If it still fails, please open an new issue mentioning which version of the package you are using.
