### ISSUE TITLE
Multiple database setup issue

### ISSUE THREAD

**Issue by sausin** [spatie/laravel-multitenancy#99]
A new issue has come up after introduction of #92

I have a `mysql` database setup which has `tenant` and `landlord` databases and another set on `sqlite` (used for testing). Before introduction of the above PR I was able to migrate and seed these databases by just specifying the connections on the artisan commands.

I.e. the below commands all worked without issues:

```sh
php artisan migrate:fresh --path=database/migrations/landlord
php artisan tenants:artisan "migrate:fresh --seed --database=tenant"
```
for mysql. And:

```sh
php artisan migrate:fresh --path=database/migrations/landlord --database=testing_landlord
php artisan tenants:artisan "migrate:fresh --seed --database=testing_tenant"
```
for sqlite setup. However, since the connections must be specified in the config file now this setup no longer works without having to change the config file before working on each database.

If this is the intended behavior going forward, it would be great to know the correct way to work through this issue.

**Comment by masterix21** [comment]
Don't you ever change your landlord connection anyway if you switch from `landlord` to `testing_landlord`?

I tried to simulate your code: the SQLite migration for landlord works, but without switching the landlord connection to `testing_landlord`, my system can't switch to the right tenant database. 

Why can't you use an environment variable to set up the landlord/tenant database connection? Should switch easier using .env and phpunit.xml.

Please help me to understand.

**Comment by sausin** [comment]
@masterix21 Thanks for your reply.

So the tests are run on the `sqlite` connection while I "use" the application in local environment on the `mysql` connection. The setup described in the original post worked before the referenced PR.

If there is a convenient way to continue using like before, that would be great. My workaround at the moment _is_ to change the environment variables to get things to work.

**Comment by masterix21** [comment]
Yes, I think you have already found the best solution: switching to environment variables, you'll retake full control of your code (using .env and phpunit.xml). 

```php
// config/multitenancy.php
'landlord_database_connection_name' => env('DB_CONNECTION_LANDLORD', 'landlord');
'tenant_database_connection_name' => env('DB_CONNECTION_TENANT', 'tenant'),
```
